#! /bin/tcsh

set GRM=/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/FINANCE/GRM_kp_sp/gram_finance_kp_sp.grm


/opt/ParSem_db/bin/linux64/xip -grm  $GRM -tr -f -sentence -sentencenum -inpututf8 $1 $2 $3 $4 $5 $6 $7













