#!/bin/sh
#set -x
rm -rf Test.class

# GRMDIR is used in grammar files and it must be defined
GRMDIR=../../grammar/english/entity;export GRMDIR
UNAME=`uname`
if [ "$UNAME" = "Linux" ]; then
	# only neccesary on Linux, due to bugs in the Linux native library loading mechanism
	LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/grondeau/linux
fi
javac -classpath ../../java/dist/jxip.jar Test.java 
java -mx32 -classpath ../../java/dist/jxip.jar:. Test $GRMDIR/englishEntity.grm 

