#!/bin/sh
set -x
clean 
rm -f test.o

ROOT=../..
LIBDIR=$ROOT/lib/linux/staticLib
#LIBDIR=$ROOT/lib/linux.debug/staticLib

g++ -c -DNTMCONNECTION -DXMLINPUT -DXIPSTLUSE -DXIPLIBXML -DXIPSTLAPI -DUNIX -DXIPSTDC -I$ROOT/include -o test.o  test.cxx
g++ -mt -L$LIBDIR test.o -o test -lxip  -lm -lpthread -lz -lstdc++

rm -f test.o
