#!/bin/sh
set -x

LD_LIBRARY_PATH=$LIBDIR;export LD_LIBRARY_PATH
ROOT_XIP=`pwd`/../../GRAMMARS;export ROOT_XIP
#VALGRIND=/home/grondeau/tools/valgrind/3.0.1/bin/valgrind
VALGRIND=/opt/ParSem/tools/valgrind/3.3.0/bin/valgrind

$VALGRIND --tool=memcheck --leak-check=yes -v --num-callers=10 --log-file=res ./test
