#define yy_create_buffer regex__create_buffer
#define yy_delete_buffer regex__delete_buffer
#define yy_scan_buffer regex__scan_buffer
#define yy_scan_string regex__scan_string
#define yy_scan_bytes regex__scan_bytes
#define yy_flex_debug regex__flex_debug
#define yy_init_buffer regex__init_buffer
#define yy_flush_buffer regex__flush_buffer
#define yy_load_buffer_state regex__load_buffer_state
#define yy_switch_to_buffer regex__switch_to_buffer
#define yyin regex_in
#define yyleng regex_leng
#define yylex regex_lex
#define yyout regex_out
#define yyrestart regex_restart
#define yytext regex_text
#define yywrap regex_wrap

#line 20 "xerox/fst/re.lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /opt/ParSem/cvs_repo/parSem/fst/dev/src/fst/xerox/fst/re.lex.yy.c,v 1.4 2005/03/04 15:45:30 grondeau Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
static yyconst short int yy_accept[284] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  114,  113,  113,  105,
      100,   10,   10,    1,  105,    1,   86,  105,   83,  103,
       52,   53,   72,   73,   95,   74,   94,   89,   97,  101,
        9,   59,   98,   60,   99,   50,   54,   91,   55,   93,
       96,   92,  105,   77,   71,   90,    8,    5,    6,    6,
        1,    8,  108,  109,  109,  106,  107,  107,    4,  113,
        4,  113,  103,  113,  113,  103,  113,  113,  110,  110,
      113,    3,    3,  111,  112,  112,    0,  100,   10,    1,

        0,  104,    0,    1,    1,    1,   87,   88,  103,  103,
      103,  103,    0,  103,    0,    0,    0,    0,   44,   18,
        0,    0,    0,    0,   64,   66,    0,    0,    0,    0,
       12,   68,   67,    0,    0,    0,   69,   65,    0,    0,
       14,  103,   17,   40,   58,   36,   41,   28,    0,   35,
       27,    0,    0,    0,    0,    0,    0,   16,   15,    0,
       56,   57,   70,    0,   13,    5,    6,    0,  109,  107,
        4,    0,    4,  103,    0,  110,  110,    0,  110,  110,
      112,    0,    1,    1,    1,    1,  103,    0,  103,    0,
        0,    0,    0,    0,    0,    0,   24,   43,    0,    0,

       39,   63,    0,   79,   78,    0,    0,   62,   81,   61,
        0,    0,   19,   32,   42,   23,   31,    0,   49,   46,
        0,    0,   11,  102,    0,  103,    0,    1,    1,  103,
      103,   21,    0,   20,    0,    0,   38,   30,    0,   37,
        0,   29,   76,   75,   85,    0,   84,   82,   80,   45,
        0,   47,    0,    0,    0,    1,    1,  103,   26,   22,
       34,   25,   33,    0,   48,    0,    7,    7,    0,    1,
        0,    0,    0,    0,    0,    0,    0,    0,   51,    2,
        0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    4,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   24,   24,   24,   24,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       37,   38,   39,   37,   40,   37,   37,   41,   42,   43,
       37,   44,   37,   37,   37,   45,   37,   37,   37,   37,
       46,   47,   48,   49,   50,   51,   37,   52,   37,   37,

       53,   37,   37,   37,   54,   37,   37,   55,   56,   57,
       58,   59,   37,   60,   61,   62,   63,   37,   37,   64,
       37,   37,   65,   66,   67,   68,    1,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    2,    2,    3,    3,    2,    4,    5,    2,    6,
        2,    6,    2,    2,    2,    2,    2,    2,    2,    2,
        6,    6,    6,    6,    2,    2,    2,    6,    2,    6,
        2,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    2,    2,    2,    2,    2,
        2,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    2,    2,    7,    2
    } ;

static yyconst short int yy_base[303] =
    {   0,
      821,  820,    0,    0,   67,   74,   79,   81,   83,   85,
       88,   91,  117,    0,  819,  818,  817,  816,   94,   96,
      843,  842,  103,  107,    0,    0,  846,  855,  806,  855,
      113,  855,  840,    0,  179,  226,   83,  286,  855,  177,
      170,  855,  855,  855,  826,  813,  347,  821,  181,  855,
      855,  175,  288,  809,  293,  320,  820,  169,  855,  356,
      855,  855,    0,  772,  855,  855,  855,  192,  855,  833,
        0,  795,  855,  855,  831,  855,  855,  830,   71,  187,
      855,  289,  298,  413,  301,  347,    0,  210,  855,  829,
      213,  855,  855,  855,  855,  828,  790,  219,  855,    0,

      298,  855,  825,    0,  481,  318,  855,  855,  366,  387,
      388,  402,    0,  415,  800,  194,  797,  344,  855,  796,
      807,  137,  806,  805,  855,  855,  767,  803,  802,  784,
      855,  855,  855,  790,  799,  798,  855,  855,  797,  257,
      855,  425,  179,  786,  855,  855,  855,  855,  785,  779,
      855,  742,  724,  705,  689,  624,    0,  855,  855,  339,
      855,  855,  855,  620,  855,  228,  855,  651,  855,  855,
      193,  304,  855,  428,  447,  855,  681,  461,  463,  546,
      855,  634,  556,    0,    0,  420,  615,  616,  619,  296,
      619,  666,  654,  638,   91,  650,  855,  855,  644,  638,

      855,  855,  637,  855,  855,  616,  619,  855,  855,  855,
      613,  612,  855,  855,  855,  855,  855,  573,  855,  855,
      497,  498,  855,  855,  625,  631,  420,  442,  632,  644,
      645,  855,  433,  855,  430,  425,  855,  855,  423,  855,
      420,  855,  855,  855,  855,  379,  855,  855,  855,  855,
      357,  855,  632,  472,  376,  648,  649,  661,  855,  855,
      855,  855,  855,  350,  855,  550,  855,  395,  352,  662,
      339,  344,  324,  310,  296,  195,   62,  323,  855,  855,
      362,  391,  855,  692,  699,  706,  713,  720,  727,  734,
      741,  748,  755,  761,  764,  770,  776,  783,  786,  792,

      799,  806
    } ;

static yyconst short int yy_def[303] =
    {   0,
      284,  284,  283,    3,  285,  285,  286,  286,  287,  287,
      288,  288,  283,   13,  284,  284,  284,  284,  289,  289,
      290,  290,  291,  291,  284,  284,  283,  283,  283,  283,
      283,  283,  283,  292,  293,  283,  283,  294,  283,  295,
      283,  283,  283,  283,  283,  283,  283,  283,  295,  283,
      283,  283,  295,  283,  295,  283,  283,  283,  283,  283,
      283,  283,  296,  283,  283,  283,  283,  283,  283,  283,
      292,  283,  283,  283,  283,  283,  283,  283,  297,  297,
      283,  293,  295,  294,  295,  295,  296,  298,  283,  283,
      298,  283,  283,  283,  283,  283,  283,  283,  283,  292,

      293,  283,  293,   36,  283,   36,  283,  283,  299,  299,
      299,  295,   84,  295,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  295,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  300,  283,  283,  283,
      283,  283,  283,  296,  283,  283,  283,  283,  283,  283,
      297,  297,  283,  295,  298,  283,  283,  298,  298,  298,
      283,  283,  283,  183,  183,   36,  299,  299,  295,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  295,  283,  183,  183,  299,
      299,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  183,  183,  299,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  183,
      283,  283,  283,  283,  283,  283,  283,  301,  283,  283,
      302,  283,    0,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283
    } ;

static yyconst short int yy_nxt[924] =
    {   0,
       30,   31,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   40,   40,   40,   50,   51,   52,   53,   54,   55,
       56,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   57,   58,   59,   60,   61,
       62,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   63,   64,   65,   66,   68,   68,
       69,   70,   71,  172,   71,   68,   68,   69,   70,   71,
      279,   71,   74,   75,   74,   75,   77,   78,   77,   78,
       80,   28,   28,   80,   28,   28,  173,   89,   90,   89,

       90,  107,   72,   91,  240,   91,   95,   96,  241,   72,
       95,   96,  108,   81,   98,   98,   81,   28,   28,   28,
       28,   28,   28,   82,   83,   28,   84,   28,   83,   28,
       28,   28,   28,   28,   28,   28,   28,   85,   83,   83,
       83,   28,   28,   28,   85,   28,   85,   28,   83,   86,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   28,   28,   28,   28,   28,   28,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   87,   28,   28,   28,  102,  113,  115,  158,  172,
      283,  199,  143,  166,  166,  172,  116,  114,  117,  200,

      118,  142,  144,  145,  114,  146,  114,  213,  142,  214,
      142,  191,  173,  176,  177,  159,  179,  180,  173,  178,
       98,   98,  178,  278,  192,  103,  100,  100,  100,  166,
      166,  100,  100,  104,  100,  105,  100,  104,  100,  100,
      100,  100,  100,  100,  100,  100,  106,  104,  104,  104,
      100,  100,  100,  106,  100,  106,  100,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  100,  100,  100,  100,  100,  100,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      100,  100,  100,  100,  110,  102,  110,  283,  111,  111,

      110,  110,  283,  110,  102,  110,  172,  113,  142,  232,
      283,  211,  111,  142,  111,  142,  147,  142,  114,  212,
      142,  142,  142,  280,  280,  114,  233,  114,  142,  173,
      142,  111,  110,  111,  110,  103,  110,  149,  186,  277,
      160,  160,  160,  160,  103,  186,  150,  186,  151,  276,
      111,  110,  111,  110,  121,  275,  113,  160,  160,  160,
      160,  194,  280,  280,  122,  123,  124,  114,  125,  126,
      195,  152,  196,  127,  114,  113,  114,  274,  153,  154,
      155,  156,  161,  273,  162,  174,  188,  272,  128,  129,
      130,  280,  280,  188,  131,  188,  113,  113,  267,  271,

      132,  133,  134,  163,  135,  136,  137,  188,  188,  138,
      139,  113,  140,  269,  188,  188,  188,  188,  265,  264,
      163,  110,  114,  110,  113,  111,  111,  110,  110,  114,
      110,  114,  110,  263,  113,  189,  262,  113,  261,  111,
      186,  111,  189,  260,  189,  142,  259,  186,  114,  186,
      176,  177,  142,  255,  142,  114,  178,  114,  111,  110,
      111,  110,  256,  110,  179,  180,  176,  177,  226,  256,
      178,  256,  178,  266,  266,  267,  268,  111,  110,  111,
      110,  100,  183,  183,  109,  109,  183,  183,  183,  184,
      183,  184,  183,  185,  185,  184,  184,  183,  184,  183,

      184,  183,  183,  183,  183,  183,  183,  185,  183,  185,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  185,  184,  185,  184,
      183,  184,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  185,  184,  185,  184,  176,
      177,  266,  266,  267,  268,  178,  100,  100,  100,  252,
      251,  100,  100,  228,  100,  105,  100,  228,  100,  100,
      100,  100,  100,  100,  100,  100,  229,  228,  228,  228,
      100,  100,  100,  229,  100,  229,  100,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,

      228,  100,  100,  100,  100,  100,  100,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      100,  100,  100,  100,  113,  283,  253,  253,  113,  250,
      249,  248,  234,  253,  253,  230,  231,  247,  246,  189,
      113,  100,  230,  231,  230,  231,  189,  235,  189,  236,
      254,  114,  257,  113,  113,  245,  244,  254,  114,  257,
      114,  257,  243,  242,  258,  231,  239,  238,  270,  257,
      113,  258,  231,  258,  231,  270,  257,  270,  257,  237,
      227,  258,  270,  227,  176,  225,  224,  222,  258,  270,
      258,  270,   28,   28,   28,   28,   28,   28,   28,   67,

       67,   67,   67,   67,   67,   67,   73,   73,   73,   73,
       73,   73,   73,   76,   76,   76,   76,   76,   76,   76,
       79,   79,   79,   79,   79,   79,   79,   88,   88,   88,
       88,   88,   88,   88,   92,   92,   92,   92,   92,   92,
       92,   94,   94,   94,   94,   94,   94,   94,  100,  100,
      221,  100,  100,  100,  100,  101,  101,  220,  101,  101,
      101,  101,  109,  109,  109,  109,  109,  109,  112,  112,
      164,  164,  164,  164,  164,  164,  171,  171,  219,  171,
      171,  171,  171,  175,  175,  175,  175,  175,  175,  175,
      187,  187,  223,  223,  223,  218,  217,  223,  223,  281,

      281,  281,  281,  281,  281,  281,  282,  282,  282,  282,
      282,  282,  282,  216,  215,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  198,  197,  193,  190,  101,
      182,  181,  176,  170,  169,  168,  167,  165,  157,  148,
      141,  120,  119,   99,   97,  283,   93,   93,   29,   29,
       29,   29,   29,   29,   27,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283
    } ;

static yyconst short int yy_chk[924] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    5,    5,   79,    5,    6,    6,    6,    6,    6,
      277,    6,    7,    7,    8,    8,    9,    9,   10,   10,
       11,   11,   11,   12,   12,   12,   79,   19,   19,   20,

       20,   37,    5,   19,  195,   20,   23,   23,  195,    6,
       24,   24,   37,   11,   31,   31,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   35,   40,   41,   58,   80,
       49,  122,   52,   68,   68,  171,   41,   40,   41,  122,

       41,   49,   52,   52,   40,   52,   40,  143,   49,  143,
       49,  116,   80,   88,   88,   58,   91,   91,  171,   88,
       98,   98,   91,  276,  116,   35,   36,   36,   36,  166,
      166,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   38,   82,   38,   53,   38,   38,

       38,   38,   55,   38,  101,   38,  172,   83,   53,  190,
       85,  140,   38,   55,   38,   53,   53,   53,   83,  140,
       55,   85,   55,  278,  278,   83,  190,   83,   85,  172,
       85,   38,   38,   38,   38,   82,   38,   56,  106,  275,
      160,  160,  160,  160,  101,  106,   56,  106,   56,  274,
       38,   38,   38,   38,   47,  273,   86,   60,   60,   60,
       60,  118,  281,  281,   47,   47,   47,   86,   47,   47,
      118,   56,  118,   47,   86,  109,   86,  272,   56,   56,
       56,   56,   60,  271,   60,   86,  109,  269,   47,   47,
       47,  282,  282,  109,   47,  109,  110,  111,  268,  264,

       47,   47,   47,  160,   47,   47,   47,  110,  111,   47,
       47,  112,   47,  255,  110,  111,  110,  111,  251,  246,
       60,   84,  112,   84,  114,   84,   84,   84,   84,  112,
       84,  112,   84,  241,  142,  114,  239,  174,  236,   84,
      186,   84,  114,  235,  114,  142,  233,  186,  174,  186,
      175,  175,  142,  227,  142,  174,  175,  174,   84,   84,
       84,   84,  228,   84,  178,  178,  179,  179,  174,  228,
      178,  228,  179,  254,  254,  254,  254,   84,   84,   84,
       84,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,

      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  180,
      180,  266,  266,  266,  266,  180,  183,  183,  183,  222,
      221,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  187,  188,  225,  225,  189,  218,
      212,  211,  191,  253,  253,  187,  188,  207,  206,  189,
      226,  229,  187,  188,  187,  188,  189,  191,  189,  191,
      225,  226,  229,  230,  231,  203,  200,  253,  226,  229,
      226,  229,  199,  196,  230,  231,  194,  193,  256,  257,
      258,  230,  231,  230,  231,  256,  257,  256,  257,  192,
      226,  258,  270,  182,  177,  168,  164,  156,  258,  270,
      258,  270,  284,  284,  284,  284,  284,  284,  284,  285,

      285,  285,  285,  285,  285,  285,  286,  286,  286,  286,
      286,  286,  286,  287,  287,  287,  287,  287,  287,  287,
      288,  288,  288,  288,  288,  288,  288,  289,  289,  289,
      289,  289,  289,  289,  290,  290,  290,  290,  290,  290,
      290,  291,  291,  291,  291,  291,  291,  291,  292,  292,
      155,  292,  292,  292,  292,  293,  293,  154,  293,  293,
      293,  293,  294,  294,  294,  294,  294,  294,  295,  295,
      296,  296,  296,  296,  296,  296,  297,  297,  153,  297,
      297,  297,  297,  298,  298,  298,  298,  298,  298,  298,
      299,  299,  300,  300,  300,  152,  150,  300,  300,  301,

      301,  301,  301,  301,  301,  301,  302,  302,  302,  302,
      302,  302,  302,  149,  144,  139,  136,  135,  134,  130,
      129,  128,  127,  124,  123,  121,  120,  117,  115,  103,
       97,   96,   90,   78,   75,   72,   70,   64,   57,   54,
       48,   46,   45,   33,   29,   27,   22,   21,   18,   17,
       16,   15,    2,    1,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "xerox/fst/re.lex"
#define INITIAL 0
/* Copyright (c) 1993-97 by Xerox Research Centre Europe.  All rights reserved. */
/* Created by Pasi Tapanainen. */
/* $Id: re.lex.yy.c,v 1.4 2005/03/04 15:45:30 grondeau Exp $ */
/****************************************************************
 *
 *                          RE.TEMPLATE.LEX
 *			    old name: RE.LEX
 *
 *      Changes (1998-1999) by Tamas Gaal:
 *           - renamed to "re.template.lex" to enable the generation (by
 *	     conditional compilation/copy) of two versions, one for fst,
 *	     one for xfst (subset of fst). 
 *           - changes in restart, buffer handling, to cope with the separation
 *	     of the interface.lex and the re.lex parts.
 *			      
 *	An old regular expression grammar is (partly) in start state <REGEXP>.
 *	Several new start states has been added for command line input.
 *			Pasi Tapanainen
 *			Oct. 1, 1993
 *
 ****************************************************************/
/** 99-6 tried: %array */
#line 27 "xerox/fst/re.lex"

#include <stdio.h>
#if defined _WINDOWS
#include <windows.h>
#include <io.h>
#ifndef __GNUC__
#include <direct.h>
#endif
#endif

#ifndef _WINDOWS
#include <unistd.h>
#endif
#include <ctype.h>
#include <string.h>

#if (defined(MAC_OS) || defined(__MWERKS__))
#include <unix.h>
#include "codewarrior.h"
#endif

#include "fst/fsm_io.h"
#include "fst/fsm-package.h"
#include "fst/comm-def.h"
#include "fst/define.h"
#include "fst/re.lex.h"
#include "fst/regex.tab.h"
#include "fst/warning.h"

#include "fst/lex-aux.h"
#include "fst/fsm-fst-x.h"

#define NL()		++(regex_file_info->line_number)
#define NEWLINE_IN_EOF() { if ((print_prompt>0) && (yyin == stdin)) fputs("\n",stdout); }
/*********** #define PREPARE_FALSE_EOF() { if ((print_prompt>0) && (yyin == stdin)) unput(' '); } */\

#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n' \
			&& c != '\r' ; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' || c == '\r') \
			buf[n++] = (char) c; \
                if ( c == '\r') \
                 { c = getc(yyin); \
                   (c == '\n' ? buf[n++] = c : ungetc(c, yyin)); } \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

static void cond_unput (char value);
void PREPARE_FALSE_EOF(void) { if ((print_prompt>0) && (yyin == stdin)) cond_unput(' '); } 

static finfo regex_file_info_info={0,0,0,{0}};
finfo *regex_file_info=&regex_file_info_info;		/* Current file + line */
int one_liner=0;		/* NewLine terminates the command. */
int one_regex=0;		/* read only one regex */
int remember_to_clean=0;	/* if error, regex have to be cleaned... */
int print_prompt=0;		/* effect on printing the prompt. */
int regex_fake_eol=0;		/* effect on printing the prompt. */ 
char lost_char;  /* To keep track of what follows ; at the end of a regular
                   expression. */

/*AK static*/ int LexEOF=0;
static char *LastName;

/* TG  */
static int unput_allowed = TRUE;
static int warn_missing_semic_EOF_allowed = TRUE;

static void regex_prompt(int);
static int parser_error(void);

/* breakbound	[<>(){]|\[|\] */
/* 
   breakbound, breakspecial, breakword, breaksymbol serve for the
   {word} Xerox regular expression notation - as in the xfst program -
   where almost any text can be between the {} braces, except for the
   } closing brace. Replaced by a simpler definition of breakword.
   See below. 2003-05-14 LK
*/
/* breakspecial	{digit}|{letter}|{other}|{breakbound}|{oper}|{mark}|{space}|[;] */
/* nonquote	(([^\n%"]|([%].))*|([^;%"]|([%].))*) */
/* word		({letter}|{digit}|[-0?.'])+ */
#define REGEXP 1
#define REGEXP0 2
#define FORCE_REGEX_EOF 3
#define FORCE_REGEX_ERROR 4
#define REGEX_NAME 5

#define ATOMI 6
#define NRO 7
#define SYM_NAME 8

#define READ_LINE 9
#define BIN_CHECK 10
#define GENERATE_ERROR 11
#define RE_ONE_LINE 12

#line 818 "xerox/fst/re.lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 172 "xerox/fst/re.lex"

#line 971 "xerox/fst/re.lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 284 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 855 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 173 "xerox/fst/re.lex"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 180 "xerox/fst/re.lex"
{	yyless(0);

			       /* This state is used to check whether
			        * the file is in a binary format or
			        * not.  BINARY is returned when a
				* binary character is detected,
				* something else otherwise.  Anything
				* that is read, is returned back to
				* the stream.  */

				return(BINARY);
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 192 "xerox/fst/re.lex"
{	yyless(0); return(SOMETHING_ELSE);	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 194 "xerox/fst/re.lex"
{	strcpy(LastName, yytext + (*yytext == ' '));

				/* We make a name for the net.  It
				 * contains the first line, but no
				 * semicolons or spaces at the end.
				 * The leading blank is not copied (it
				 * exists always).  */

				if (!one_liner && (yytext[yyleng-1] != ';'))
				  strcpy(LastName + yyleng, " ...");
				yyless(0);
				BEGIN(REGEXP);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 207 "xerox/fst/re.lex"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 208 "xerox/fst/re.lex"
{	NL();
				if (one_liner)
				  {
				    BEGIN(FORCE_REGEX_EOF);
				    PREPARE_FALSE_EOF();
				    return(END);
				  }
				else
				  regex_prompt(0);
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 218 "xerox/fst/re.lex"
{
				NL();
				BEGIN(FORCE_REGEX_EOF);
				PREPARE_FALSE_EOF();

			       /* An escape from <REGEXP> mode.  This
				* is allowed only after a regular
				* expression has been read.  Thus we
				* can use END as an alphabet too.
				* i.e. "END a END;" is a regular
				* expression but "END;" stops <REGEXP>
				* mode.  We read the newline characted
				* here, but FORCE_REGEX_EOF needs to
				* read something from stream if there
				* is not a real EOF.  It is not a
				* problem while reading files, but
				* from (interactive) keyboard it would
				* require a new line to be typed, so
				* we push a space to the input stream
				* (and hope that it is harmless).  */

				return(END);
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 241 "xerox/fst/re.lex"
{	yyless(0);
				cond_unput(' '); /* Nasty, but don't remove
					unless you know what you are doing */
				if (LastName)	BEGIN(REGEX_NAME);
				else		BEGIN(REGEXP);

			       /* REGEXP0 is a state where reader is
				* before any regular expression is
				* read or after the expression is read
				* (see SEMIC).  This is the place
				* where special commands should be
				* placed (i.e. END if exists).
				* Everything that could be part of a
				* regular expression is returned into
				* the stream in this state.  */

			}
	YY_BREAK
case YY_STATE_EOF(REGEXP0):
#line 258 "xerox/fst/re.lex"
{	BEGIN(FORCE_REGEX_EOF);
				LexEOF=1;
				return(END);
			}
	YY_BREAK
case YY_STATE_EOF(REGEXP):
#line 262 "xerox/fst/re.lex"
{	BEGIN(FORCE_REGEX_EOF);
				LexEOF=1;

			       /* No semicolon is given after the last
				* expression.  We return semicolon
				* here and the next call returns END.
				* This makes the error recovering a
				* little bit simplier.  */

				if (warn_missing_semic_EOF_allowed) /* 97-12-1 TG */
				 warn_missing_semic_EOF();
                                lost_char = yy_hold_char;
				return(SEMIC);
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 276 "xerox/fst/re.lex"
{	if (one_regex)
				{
					BEGIN(FORCE_REGEX_EOF);
					PREPARE_FALSE_EOF();
					regex_fake_eol=1;
				}
				else
				{
					BEGIN(REGEXP0);
				}
				lost_char = yy_hold_char;
				return(SEMIC);
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 289 "xerox/fst/re.lex"
{	NL();
				if (one_liner)
				{
					BEGIN(FORCE_REGEX_EOF);
					PREPARE_FALSE_EOF();

				       /* No semicolon in one-line
					* expression (from keyboard).
					* We force one semicolon here
					* and return END next.  This
					* is not considered as an
					* error, so no warnings are
					* printed.  */

                                        lost_char = yy_hold_char;
					return(SEMIC);
				}
				else
				  regex_prompt(1);
			}
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 310 "xerox/fst/re.lex"
return(EPSBR_LEFT);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 311 "xerox/fst/re.lex"
return(EPSBR_RIGHT);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 312 "xerox/fst/re.lex"
return(IN_CTX);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 313 "xerox/fst/re.lex"
return(IN_CTX_R);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 314 "xerox/fst/re.lex"
return(IN_CTX_L);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 315 "xerox/fst/re.lex"
return(IN_CTX_O);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 316 "xerox/fst/re.lex"
return(L_ARROW);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 317 "xerox/fst/re.lex"
return(R_ARROW);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 318 "xerox/fst/re.lex"
return(D_ARROW);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 319 "xerox/fst/re.lex"
return(L_ARROW_OPT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 320 "xerox/fst/re.lex"
return(R_ARROW_OPT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 321 "xerox/fst/re.lex"
return(D_ARROW_OPT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 322 "xerox/fst/re.lex"
return(AT_R_ARROW);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 323 "xerox/fst/re.lex"
return(R_ARROW_AT);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 324 "xerox/fst/re.lex"
return(AT_R_ARROW_OPT);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 325 "xerox/fst/re.lex"
return(R_ARROW_AT_OPT);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 326 "xerox/fst/re.lex"
return(AT_RIGHT_A);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 327 "xerox/fst/re.lex"
return(RIGHT_A_AT);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 328 "xerox/fst/re.lex"
return(AT_RIGHT_A_OPT);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 329 "xerox/fst/re.lex"
return(RIGHT_A_AT_OPT);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 330 "xerox/fst/re.lex"
return(AT_L_ARROW);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 331 "xerox/fst/re.lex"
return(L_ARROW_AT);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 332 "xerox/fst/re.lex"
return(AT_L_ARROW_OPT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 333 "xerox/fst/re.lex"
return(L_ARROW_AT_OPT);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 334 "xerox/fst/re.lex"
return(AT_LEFT_A);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 335 "xerox/fst/re.lex"
return(LEFT_A_AT);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 336 "xerox/fst/re.lex"
return(AT_LEFT_A_OPT);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 337 "xerox/fst/re.lex"
return(LEFT_A_AT_OPT);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 338 "xerox/fst/re.lex"
return(THREE_DOTS);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 339 "xerox/fst/re.lex"
return(L_DBL_ARROW);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 340 "xerox/fst/re.lex"
return(R_DBL_ARROW);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 341 "xerox/fst/re.lex"
return(D_DBL_ARROW);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 342 "xerox/fst/re.lex"
return(CTX_BOUNDARY);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 343 "xerox/fst/re.lex"
return(REP_SEP);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 345 "xerox/fst/re.lex"
return(BIN_ATFILE);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 346 "xerox/fst/re.lex"
return(REGEX_ATFILE);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 347 "xerox/fst/re.lex"
return(TEXT_ATFILE);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 348 "xerox/fst/re.lex"
return(SPACEDTEXT_ATFILE);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 349 "xerox/fst/re.lex"
return(PROLOG_ATFILE);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 350 "xerox/fst/re.lex"
return(BIN_ATFILE);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 352 "xerox/fst/re.lex"
return(RE2N_VAR_TOK);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 354 "xerox/fst/re.lex"
{ cond_unput(' '); return(LEFT_P); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 355 "xerox/fst/re.lex"
return(RIGHT_P);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 356 "xerox/fst/re.lex"
{ cond_unput(' '); return(LEFT_B); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 357 "xerox/fst/re.lex"
return(RIGHT_B);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 359 "xerox/fst/re.lex"
return(UP_LEFT_A);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 360 "xerox/fst/re.lex"
return(UP_RIGHT_A);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 361 "xerox/fst/re.lex"
return(DOUBLE_A);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 362 "xerox/fst/re.lex"
return(LEFT_A);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 363 "xerox/fst/re.lex"
return(RIGHT_A);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 365 "xerox/fst/re.lex"
return(X_OP);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 366 "xerox/fst/re.lex"
return(O_OP);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 367 "xerox/fst/re.lex"
return(IGNORE_INTERN);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 368 "xerox/fst/re.lex"
return(UPPER_SIDE);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 369 "xerox/fst/re.lex"
return(UPPER_SIDE);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 370 "xerox/fst/re.lex"
return(LOWER_SIDE);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 371 "xerox/fst/re.lex"
return(LOWER_SIDE);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 372 "xerox/fst/re.lex"
return(INVERT_FST);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 373 "xerox/fst/re.lex"
return(REVERS_FST);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 374 "xerox/fst/re.lex"
return(UP_LEFT_C);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 375 "xerox/fst/re.lex"
return(RIGHT_C);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 376 "xerox/fst/re.lex"
return(STAR);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 377 "xerox/fst/re.lex"
return(PLUS);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 379 "xerox/fst/re.lex"
return(MINUS);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 380 "xerox/fst/re.lex"
return(MINUS_UPPER);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 381 "xerox/fst/re.lex"
return(MINUS_LOWER);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 383 "xerox/fst/re.lex"
return(OR);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 384 "xerox/fst/re.lex"
return(UNION_UPPER);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 385 "xerox/fst/re.lex"
return(BIG_O_OP);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 386 "xerox/fst/re.lex"
return(UNION_UPPER);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 387 "xerox/fst/re.lex"
return(UNION_LOWER);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 388 "xerox/fst/re.lex"
return(UNION_LOWER);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 390 "xerox/fst/re.lex"
return(AND);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 391 "xerox/fst/re.lex"
return(MERGE_RIGHT);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 392 "xerox/fst/re.lex"
return(MERGE_LEFT);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 393 "xerox/fst/re.lex"
return(DOLLAR);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 394 "xerox/fst/re.lex"
return(DOLL_PER);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 395 "xerox/fst/re.lex"
return(DOLL_QM);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 396 "xerox/fst/re.lex"
return(SLASH);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 397 "xerox/fst/re.lex"
return(TILDE);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 398 "xerox/fst/re.lex"
return(B_SLASH);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 399 "xerox/fst/re.lex"
return(B_QUOTE);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 400 "xerox/fst/re.lex"
return(UP);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 401 "xerox/fst/re.lex"
return(PERIOD);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 402 "xerox/fst/re.lex"
return(COMMA);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 403 "xerox/fst/re.lex"
return(LINE);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 404 "xerox/fst/re.lex"
return(ZERO);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 405 "xerox/fst/re.lex"
return(EQUALS);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 406 "xerox/fst/re.lex"
return(QMARK);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 407 "xerox/fst/re.lex"
;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 408 "xerox/fst/re.lex"
return(COLON);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 410 "xerox/fst/re.lex"
{   remove_braces((unsigned char *) yytext);
				return(BREAKSYMB);
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 413 "xerox/fst/re.lex"
{	remove_percent((unsigned char *) yytext, 0);
				return(SYMBOL);
			}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 416 "xerox/fst/re.lex"
{	expand_quoted((unsigned char *) yytext);
				return(QUOTED_SYMBOL);
			}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 419 "xerox/fst/re.lex"
{	if (*yytext == '{' || *yytext == '"')
                                 {
                                   /* A stray { without matching }
				    or a stray ". 
				   */
                                   return(RERROR);
                                 }
                               else if (isgraph((int) *yytext))
				  {
				    /* This should not happen */
				    warn_charset(*yytext);
				  }
				else
				  {

				   /* We have some problems here.  We
				    * are either reading a binary file
				    * or there is missing characters
				    * in charcter sets.  Here, we
				    * assume that file format is
				    * already checked and thus we just
				    * ignore those suspicious
				    * characters.  */

				    warn_binary_char(*yytext);
				  }
			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 447 "xerox/fst/re.lex"
{	yyless(0); return(RERROR); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 448 "xerox/fst/re.lex"
{	NL(); yyless(0); return(RERROR); }
	YY_BREAK
case YY_STATE_EOF(FORCE_REGEX_ERROR):
#line 449 "xerox/fst/re.lex"
return(RERROR);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 451 "xerox/fst/re.lex"
{	yyless(0); return(END); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 452 "xerox/fst/re.lex"
{ NL();	yyless(0); return(END); }
	YY_BREAK
case YY_STATE_EOF(FORCE_REGEX_EOF):
#line 453 "xerox/fst/re.lex"
{	return(END);

				/* *********************************
				 * IMPORTANT
				 * *********************************
				 * Start states REGEXP0, REGEXP and
				 * FORCE_REGEX_EOF are ment to be used
				 * by REGEX.Y only.  The values they
				 * return i.e. END etc. are thus
				 * relevant for REGEX.Y only. 
				 * ******************************** */

			}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 467 "xerox/fst/re.lex"
{	NL();	return(RE_ONE_LINE);  }
	YY_BREAK
case YY_STATE_EOF(READ_LINE):
#line 468 "xerox/fst/re.lex"
{	LexEOF=1; return(END);	   }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 470 "xerox/fst/re.lex"
{ yymore();	parser_error();		}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 471 "xerox/fst/re.lex"
{ NL(); yymore();	parser_error();		}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 472 "xerox/fst/re.lex"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1809 "xerox/fst/re.lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(REGEX_NAME):
case YY_STATE_EOF(ATOMI):
case YY_STATE_EOF(NRO):
case YY_STATE_EOF(SYM_NAME):
case YY_STATE_EOF(BIN_CHECK):
case YY_STATE_EOF(GENERATE_ERROR):
case YY_STATE_EOF(RE_ONE_LINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 284 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 284 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 283);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 472 "xerox/fst/re.lex"

/****************************************************************
  Prompt
 ****************************************************************/

static char *regex_prompt_string; /* This is what you see... */

static void regex_prompt(int i)
{

  /* This is for regular expressions.  It probably should not be here
   * but I don't want to modify regex.y (and idiom.y) file, and it is
   * called anyway only from this file.  */

  if ((print_prompt>0) && !one_liner)
    {
      if (i)
	fputs("",stdout); /* ">> " */
      else
	fputs(regex_prompt_string,stdout);
    }
}

/****************************************************************
  Change the start state
 ****************************************************************/

void wait_for_regex()
{
  regex_prompt_string="";
  regex_prompt(0);
  BEGIN(REGEXP0);
}

void wait_for_END()
{

  /* We force here a "false" end of file.  It means that nothing is
   * read anymore, and always when LEX is called, END is returned.
   * This need not any special handling afterwards.  But note, that
   * input stream MAY contain one extra SPACE character.  Usually, it
   * should not cause any troubles.  Do not call this function, if it
   * does.  This function is mainly for regex.y.  */

  BEGIN(FORCE_REGEX_EOF);
  PREPARE_FALSE_EOF();
}

/****************************************************************
  Read something fixed
 ****************************************************************/

void regex_name(char *name)
{
  LastName = name;
}

/****************************************************************
  Read current line
 ****************************************************************/

static void clean_inputline()
{
  BEGIN(READ_LINE);
  yylex();
  BEGIN(GENERATE_ERROR);
}

/****************************************************************
  Recover from a REGEX error
 ****************************************************************/
void recover_regex_error()
{

  /* We have found an error here and next we try to prevent LEX to
   * read any further before we have stopped YACC.  If the error has
   * occured in the end of regular expression (i.e. yytext == ";"), we
   * return semicolon back to the input stream, because we don't want
   * to miss it and clear the next expression too (see. clean_regex).
   * */

  BEGIN(FORCE_REGEX_ERROR);
  if (*yytext == ';')	cond_unput(';');
  else			cond_unput(' ');
}

int clean_regex()
{

  /* We have now stopped YACC, and we clean the rest of the regular
   * expression.  When reading from keyboard (stdin) we remove only
   * the rest of the line (is it a good solution?).  */

  int i;

  if ((yyin == stdin) && (print_prompt > 0))
    {
      clean_inputline();
      BEGIN(REGEXP0);
      return(END);
    }
  else
    {
      BEGIN(REGEXP);
      while ((i=yylex()) != END)
	if (i == SEMIC) break;
      clean_inputline();
      return i;
    }
}

void stop_regex()
{

  /* We have detected too many errors and we want to stop reading
   * regular expressions.  Here we need only check if we are reading
   * keyboard (stdin) and then clean the rest of the line.  If we are
   * reading a file, we need not do anything here (just to close the
   * file later).  IF we are reading redirected file variable
   * print_prompt is supposed to be zero, and then we need to clean up
   * till next END.  */

  if ((yyin == stdin) && (print_prompt > 0))
    clean_inputline();
  else if (remember_to_clean)
    {
      BEGIN(REGEXP0);
      while (yylex() != END) ;
    }
}
/****************************************************************
  auxiliary I/O routines
 ****************************************************************/
int lex_read_from_string(char *str)
     /* This can be used for pushing small strings to lex buffer.
	Usually, you should use the function execute_string(char *). */
{
  int i=0;
  char *p;
  if (str)
    {
      p = str + (i=strlen(str));
      while (--p >= str) unput(*p);
    }
  return i;
}

int regex_lex_tg_read_from_string(char *str)
     /* This can be used for pushing small strings to lex buffer.
	 */
{
  int i=0, j;
  char *p;
  if (str)
    {
      p = str + (i=strlen(str));
      j = i;
      if  ((p >= str) && yy_current_buffer && yy_current_buffer->yy_ch_buf)
	{
	  yy_current_buffer->yy_ch_buf[j]='\0';
	  yy_current_buffer->yy_ch_buf[j+1]='\0'; /**** 99-5-18 */
	}
      while (--p >= str) 
	{
	  if (yy_current_buffer && yy_current_buffer->yy_ch_buf)
	    {
	      yy_current_buffer->yy_ch_buf[j-1]=*p;
	      j--;
	    }	  
	}
    }

  {
    yy_current_buffer->yy_n_chars=i;
    yy_load_buffer_state();
  }
  return i;
}

 /*  The Macintosh version uses the SIOUX interface package. The Sioux.c
 	 file sets the variable atEOF to 1 when it encounters an end-of-file.
 	 To continue reading from stdin one must reset atEOF to 0.
 	 This is a rather awful hack. Neede in re_lex_total_restart() and
 	 restart_if_necessary.
  */
#ifdef MAC_OS
extern int atEOF;
#endif

void re_lex_total_restart()
{
  /* After interruption anything is possible.
   * We have to restart everything.  */

  /*
    #ifdef DEBUG
    DEBUG_report_re_lex(" (re) re_lex_total_restart()");
    #endif
    */

  if (yyin != stdin) fclose(yyin);
  regex_restart(stdin);
  LexEOF=0;
#ifdef MAC_OS
  atEOF = 0;
#endif
  print_prompt = (*fst_IY_INTERACTIVE() ? 1 : 0); /*  Hope this is right.  */
}

void regex_restart_if_necessary()
{
  /* This function is supposed to be called always after reading from
   * keyboard (stdin) regular expressions (<REGEXP>) or any function
   * that may leave the end of file mark (<CTRL>-D) to the stdin.
   * NOTE: variable LexEOF must be set to 1, only if <<EOF>> is
   * encountered.  */
   
 /*  The Macintosh version uses the SIOUX interface package. The Sioux.c
 	 file sets the variable atEOF to 1 when it encounters an end-of-file.
 	 To continue reading from stdin one must reset atEOF to 0.
 	 This is a rather awful hack. 1998-10-30. LK
  */

  if (LexEOF)
    {
      if (yyin == stdin)
	{

	  /* End of file is found after (or before) reading a regular
	   * expression in <REGEXP> state from the keyboard.  Because
	   * we don't want to close the keyboard stream here, we
	   * restart LEX.  This is necessary if we want to continue
	   * reading for example in <COMMAND> state.  */

	  NEWLINE_IN_EOF();
	  regex_restart(yyin);
#ifdef MAC_OS
	  atEOF = 0;
#endif
	}
      LexEOF=0;
    }
}

static FILE *fopen_new(char *name)
{
  int c;
  FILE *f;
  if ((f = fopen(name, "r")))
    {
      if ((((c=fgetc(f)) == EOF) && !feof(f)) || ferror(f))
	{
	  fclose(f);

	  /* This happens in Solaris 2 when the file is a special file
	   * that cannot be read.  This is an ad-hoc solution to the
	   * problem.  */

	  return NULL;
	}
      else	/* Everything is ok.  Let's open the file again */
	{
	  fclose(f);
	  return fopen(name, "r");
	}
    }
  else		/* Cannot open the file.  */
    return NULL;
}

/*AK static* finfo *new_lex_buffer(finfo *fi, FILE *f, ifile *file) */
finfo *new_re_lex_buffer(finfo *fi, FILE *f, ifile *file, int line_offset)
{
  finfo *old;
  fi->file.name = strdup(file->name);
  fi->file.type = file->type;
  fi->line_number = /* 0; */ line_offset;
  old = regex_file_info;
  regex_file_info = fi;

  /* We open a new (text) stream for reading.  For that we have to
   * also make a new buffer for lex.  We return here the previous lex
   * buffer, so that it can be reset later by function old_re_input_file.
   * The old previous buffer may still contain something that is not
   * yet handled, especially when we read real files.  Only keyboard
   * (stdin) stream is usually unbuffered.  But not necessarily when
   * it is redirected (see main function in file fsc.c for more
   * details).  Variable print_prompt affects on whether the prompt is
   * printed or not.  When it is less than zero no prompts are
   * printed.  */

  yy_switch_to_buffer(yy_create_buffer(yyin=f,YY_BUF_SIZE));
  fi->buffer = YY_CURRENT_BUFFER;
  if (fi->buffer)
    fi->ch_buf = YY_CURRENT_BUFFER->yy_ch_buf;
  else
    fi->ch_buf = 0;
  return old;
}

/* static finfo *new_string_buffer(finfo *fi, ifile *file) made non-static,AK
 */
finfo *new_re_string_buffer(finfo *fi, ifile *file)
{
  finfo *old;
  fi->file.name = NULL;
  fi->file.type = STRING_IN;
  fi->line_number = 0;
  old = regex_file_info;
  regex_file_info = fi;
  yy_scan_string(file->name);
  fi->buffer = YY_CURRENT_BUFFER;
  if (fi->buffer)
    fi->ch_buf = YY_CURRENT_BUFFER->yy_ch_buf;
  else
    fi->ch_buf = 0;
  return old;
}

void old_re_lex_buffer(finfo *fi, finfo *actual_fi)
     /* Attention: this is FLEX-implementation-dependent: if the
	YY_CURRENT_BUFFER structure changes there this function should
	be revised.
	A FLEX buffer is deleted here: since yy_delete_buffer()
	deletes the YY_CURRENT_BUFFER structure, using free(), and
	also the storage pointed by its  yy_ch_buf field (that has
	the input string) if the latter has an updated value then
	free() will arbitrarily (and incorrectly) free something that
	will cause problems later. To prevent this, the creation-time
	yy_ch_buf field is restored! */
{
  if ( YY_CURRENT_BUFFER != fi->buffer) /*** Don't free if active! 98-12-11 TG */
    {
      yy_current_buffer->yy_ch_buf = actual_fi->ch_buf;
      yy_delete_buffer(YY_CURRENT_BUFFER);
    }
  yy_switch_to_buffer(fi->buffer);
  if (regex_file_info && regex_file_info->file.name) free(regex_file_info->file.name);
  regex_file_info = fi;
}

finfo *new_re_input_file(ifile *file, finfo *buffer)
{
  FILE *f;
  finfo *old;

  LexEOF = 0;

  switch (file->type)
    {
    case FILE_IN:
      if (*fst_IY_VERBOSE()) print_open_file(file->name);

      /* NOTE!!!!!  __Solaris_2__ */
      /* WARNING!!!!! */
      /* PROGRAM CRASHES HERE if not... !!!!! */
      /* The file type SHOULD be checked before opening it i.e. whether
       * the file is actually a directory or some other special file.  */

      if ((f = fopen_new(file->name)))
	{
	  print_prompt--;
	  old = new_re_lex_buffer(buffer, f, file, 0);
	  BEGIN(BIN_CHECK);
	  if (yylex() == BINARY)
	    {
	      warn_binary(file->name);
	      old_re_input_file(old, buffer);
	      return NULL;
	    }
	  else
	    return old;
	}
      else
	{
	  perror(file->name);
	  return NULL;
	}
      break;
    case PIPE_IN:
      if ((f = popen(file->name,"r")))
	{
	  print_prompt--;
	  old = new_re_lex_buffer(buffer, f, file, 0);
	  return old;
	}
      else
	{
	  perror(file->name);
	  return NULL;
	}
      break;
    case STRING_IN:
      print_prompt--;
      old = new_re_string_buffer(buffer, file);
      return old;
    default:
      parser_error();
      return NULL;
    }
}

int old_re_input_file(finfo *buffer, finfo *actual_buffer)
{

 /* Resetting an old stream and buffer for reading.  See above. */

  LexEOF=0;
  if (*fst_IY_VERBOSE() && regex_file_info->file.name)
    print_close_file(regex_file_info->file.name);
  if (buffer)
    {
      print_prompt++;
      switch (regex_file_info->file.type)
	{
	case FILE_IN:
	  fclose(yyin);
	  break;
	case PIPE_IN:
	  pclose(yyin);
	  break;
	case STRING_IN:
	  break;
	default:
          break;
	}
      old_re_lex_buffer(buffer, actual_buffer);
      return 1;
    }
  else
    {

      /* We can only hope that IF lex is ever called again, it is
       * now restarted properly.  */

      re_lex_total_restart();
      return 0;
    }
}

/****************************************************************
  This is a lethal function.  Called only in emergency.
 ****************************************************************/

static int parser_error()
{
  print_internal_error();
  exit(-2);
}


/****************************************************************
  Wrap
 ****************************************************************/

/* static */ int yywrap()
{
  return 1;
}

FILE * re_lex_infile()
{
  FILE * debug_f = yyin;

  return debug_f;
}

void regex_tg_restart(FILE * ff, int from_initial_regex_state)
     /* save actual buffer (and yytext) values; 
	restart lex from file; 
	restore saved values. Resembles to yyrestart(ff) but
	- yy_init_buffer is not done (onyly at a new buffer)
	- the automaton is started from the REGEX0 state.
*/
{
  if ( ! yy_current_buffer )
    {
      yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );
      yy_init_buffer( yy_current_buffer, ff );
    }
  yy_load_buffer_state();
  if (from_initial_regex_state)
    BEGIN(REGEXP0);
}

void regex_tg_restart_with_init(FILE * ff, void * interface_master_current_buffer)
     /*
	restart lex from file; 
	Resembles to yyrestart(ff) but:
	- sets the automaton to the REGEXP0 state (beginning of parsing);
	- inherits some yy_current_buffer (of regex) attributes from
	interface_master_current_buffer : 
	this allows to use it for "read from string" purposes - where
	further yy_current_buffer character reading is forbidden - and
	also for character- versus burst-mode read (if allowed). */  
{
  if ( ! yy_current_buffer )
    {
      yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );
    }

  yy_init_buffer( yy_current_buffer, ff );
    
  if (interface_master_current_buffer)
    {
      yy_current_buffer->yy_fill_buffer = ((YY_BUFFER_STATE) interface_master_current_buffer)->yy_fill_buffer;
      yy_current_buffer->yy_is_interactive = ((YY_BUFFER_STATE) interface_master_current_buffer)->yy_is_interactive;      
    }

  yy_load_buffer_state();
  BEGIN(REGEXP0);
}

void regex_lex_yyless(int n)
{
  yyless(n);
}

void change_lex_state_to_REGEXP (void)
{
  BEGIN(REGEXP);
}

/* export this to prepare for an "unput()" 97-12-1 TG */
void re_nl (void)
{
  NL();
}

static void cond_unput (char value)
{
  if ( unput_allowed)
    unput (value);
}

int set_unput_allowed(int true_or_false)
{
  int old_unput_allowed=0;
  old_unput_allowed = unput_allowed;
  unput_allowed = true_or_false;
  return old_unput_allowed;
}

void set_warn_missing_semic_EOF_allowed(int true_or_false)
{
  warn_missing_semic_EOF_allowed = true_or_false;
}

/****************************************************************
  Prompt
 ****************************************************************/
void print_a_prompt(char *prompt)
{
  if (print_prompt>0) fputs(prompt,stdout);
}

/****************************************************************
  Read something fixed
 ****************************************************************/

void switch_regex_lex_buffer (char * buf)
{
  /*** yy_switch_to_buffer(( YY_BUFFER_STATE)  buf); */
  /*
#ifdef DEBUG
   fprintf (stdout, " DEBUG switch_regex_lex_buffer() buf=0x%x==%d.\n", (int) buf, (int) buf);
#endif
*/
  yy_current_buffer = ( YY_BUFFER_STATE) buf;
}

/* */
void regex_lex_buf_restart(char * buf)
{
  /* 
     #ifdef DEBUG
     DEBUG_report_re_lex("regex_lex_buf_restart()");
     #endif
     */

  if ( buf )
    {
      yy_current_buffer = ( YY_BUFFER_STATE) buf; 
    }
  yy_load_buffer_state();
  BEGIN(REGEXP0);
}

static void regex_tg_flush_buffer_unchecked( )
{
  
  if (yy_current_buffer)
    yy_flush_buffer(yy_current_buffer);
}

void regex_tg_flush_buffer(void)
     /* The regex flex buffer is partially restored according to the
	value in the actual regex_file_info: the yy_ch_buf field is
	restored (to the original value) since this buffer can be
	considered as new when this function is called.
      */
{
  if (yy_current_buffer && regex_file_info && regex_file_info->ch_buf)
    {
      yy_current_buffer->yy_ch_buf = regex_file_info->ch_buf;
      regex_tg_flush_buffer_unchecked();
    }
  else
    fsm_fprintf(stderr, "Regex flex problem in regex_tg_flush_buffer_restored().\n");
}

int regex_length_processed(void)
     /* How many characters have been eaten by the lexer of regex.
	June 1999 TG
      */
{
  int result = 0;
  
  if (! yy_current_buffer)
    return result;
  result = yy_c_buf_p - yy_current_buffer->yy_ch_buf;

  if ( (yy_current_buffer->yy_buf_size - result) > 0  )
    return result;
  else
    return 0;
}

char * re_yy_current_buffer__yy_ch_buf()
     /* return the address of the flex character string buffer.
      */
{
  if (yy_current_buffer && yy_current_buffer->yy_ch_buf)
    {
      return (char *)  yy_current_buffer->yy_ch_buf;
    }
  else
    return NULL;      
}

void start_regex_flex(FILE *f)
{
  static int already_started=FALSE;
  if (! already_started)
    {
      if (!f && !yyin) f = stdin;
      else if (!f) f = yyin;
      /* regex_restart(f);  */
      regex_tg_restart(f, TRUE);  
      regex_file_info = &regex_file_info_info;
      regex_file_info_info.buffer = YY_CURRENT_BUFFER;
      if (regex_file_info_info.buffer)
	regex_file_info_info.ch_buf = yy_current_buffer->yy_ch_buf;
      else
	regex_file_info_info.ch_buf = NULL;
      regex_file_info_info.file.name = NULL;
      regex_file_info_info.file.type = STDIN_IN;
      regex_file_info_info.line_number = 0;
      already_started = TRUE;
    }
}
