s/\+ADJ/\+hmm_ADJ/g
s/\+ADV/\+hmm_ADV/g
s/\+CJ\/AUX/\+hmm_CJ/g
s/\+CM/\+hmm_CM/g
s/\+CMPND/\+hmm_CMPND/g
s/\+CONJ/\+hmm_CONJ/g
s/\+DATE/\+hmm_DATE/g
s/\+EXCL/\+hmm_EXCL/g
s/\+FRGN/\+hmm_FRGN/g
s/\+NOUN/\+hmm_NOUN/g
s/\+NUM/\+hmm_NUM/g
s/\+ORD/\+hmm_ORD/g
s/\+PHRAS/\+hmm_PHRAS/g
s/\+PPERS/\+hmm_PPERS/g
s/\+PR\/AUX/\+hmm_PR/g
s/\+PREFL/\+hmm_PREFL/g
s/\+PREL/\+hmm_PREL/g
s/\+PREP/\+hmm_PREP/g
s/\+PRON/\+hmm_PRON/g
s/\+PRTCL/\+hmm_PRTCL/g
s/\+PT\/AUX/\+hmm_PT/g
s/\+PUNCT/\+hmm_PUNCT/g
s/\+QVRB/\+hmm_QVRB/g
s/\+SYMB/\+hmm_SYMB/g
s/\+TIME/\+hmm_TIME/g
s/\+VAUX/\+hmm_VAUX/g
s/\+VFIN/\+hmm_VFIN/g
s/\+VGER/\+hmm_VGER/g
s/\+VINF/\+hmm_VINF/g
s/\+VMOD/\+hmm_VMOD/g
s/\+VPRT/\+hmm_VPRT/g

