#!/bin/sh
#set -x

GRMDIR=../../../grammar/english/entity
export GRMDIR
GRAM=$GRMDIR/englishEntity.grm
GKLSFILES=../gklsFiles
INPUTDIR=$GKLSFILES/input

JAR=../../dist/jxip.jar

UNAME=`uname`
if [ "$UNAME" = "Linux" ]; then
	# only neccesary on Linux, due to bugs in the Linux native library loading mechanism
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/grondeau/linux
fi

java -classpath $JAR com.xerox.jxip.InputFile $GRAM $INPUTDIR

rm -f "C:\\XIPGKLS\\res\\res.xml"

