SUBJ_REL(devrait,usine)
SUBJ_PASSIVE(implantée,usine)
SUBJ_PASSIVE(représente,usine)
OBJ(représente,investissement)
OBJ(devrait,implantée)
DEEPOBJ(implantée,usine)
COREF_REL(usine,qui)
VMOD_POSIT1(implantée,Eloyes)
NMOD_POSIT1(148 milliards,francs)
NMOD_POSIT1(3,7 milliards,yens)
NMOD_POSIT1(investissement,3,7 milliards)
PREPOBJ(francs,de)
PREPOBJ(yens,de)
PREPOBJ(3,7 milliards,d')
PREPOBJ(Eloyes,à)
DETERM(investissement,un)
DETERM_DEF(usine,L')
AUXIL_PASSIVE(implantée,être)
CONNECT_REL(devrait,qui)
0>GROUPE{SC{NP{L' usine} , SC{BG{qui} FV{devrait}} IV{être implantée} PP{à NP{Eloyes}} INS{( NP{Vosges} )} FV{représente}} NP{un investissement} PP{d' environ NP{3,7 milliards}} PP{de NP{yens}} INS{( NP{148 milliards} PP{de NP{francs}} )} .}

SUBJ(fabriquera,Elle)
OBJ(fabriquera,produit)
OBJ_COORD(fabriquera,pièces)
COREF_REL(produit,qui)
VMOD_POSIT1(fabriquera,dans un premier temps)
VMOD_POSIT1(entre,processus)
NMOD_POSIT1(produit,liquide)
NMOD_POSIT1(pièces,détachées)
NMOD_POSIT1(pièces,filiale)
NMOD_POSIT1(processus,photocopies)
NMOD_POSIT1(filiale,Minolta)
NMOD_POSIT1(Minolta,RFA)
NMOD_POSIT2(pièces,Minolta)
NMOD_POSIT2(filiale,RFA)
COORDITEMS(produit,pièces)
PREPOBJ(RFA,en)
PREPOBJ(Minolta,de)
PREPOBJ(filiale,pour)
PREPOBJ(photocopies,des)
PREPOBJ(processus,dans)
DETERM_DEF(filiale,la)
DETERM(pièces,des)
DETERM_DEF(processus,le)
DETERM_DEF(produit,le)
CONNECT_REL(entre,qui)
1>GROUPE{SC{NP{Elle} FV{fabriquera}} , dans un premier temps , NP{le produit} AP{liquide} SC{BG{qui} FV{entre}} PP{dans NP{le processus}} PP{des NP{photocopies}} ainsi que NP{des pièces} AP{détachées} PP{pour NP{la filiale}} PP{de NP{Minolta}} PP{en NP{RFA}} .}

SUBJ(devrait,usine)
SUBJ(lancer,usine)
OBJ(devrait,lancer)
VMOD(devrait,1992)
VMOD_POSIT1(lancer,fabrication)
NMOD_POSIT1(fabrication,photocopieurs)
COORDITEMS(fabrication,imprimantes)
PREPOBJ(imprimantes,d')
PREPOBJ(photocopieurs,de)
PREPOBJ(fabrication,dans)
PREPOBJ(1992,A partir de)
DETERM_DEF(fabrication,la)
DETERM_DEM(usine,cette)
REFLEX(lancer,se)
2>GROUPE{SC{PP{A partir de NP{1992}} , NP{cette usine} FV{devrait}} IV{se lancer} PP{dans NP{la fabrication}} PP{de NP{photocopieurs}} et PP{d' NP{imprimantes}} .}

SUBJ(emploiera,elle)
OBJ(emploiera,centaine)
VMOD(emploiera,ouverture)
NMOD_POSIT1(centaine,personnes)
PREPOBJ(personnes,de)
PREPOBJ(ouverture,Lors de)
DETERM(centaine,une)
DETERM_POSS(ouverture,son)
3>GROUPE{SC{PP{Lors de NP{son ouverture}} , NP{elle} FV{emploiera}} NP{une centaine} PP{de NP{personnes}} .}

NMOD_POSIT1(double,1992)
PREPOBJ(1992,à)
PREPOBJ(1992,d')
DETERM_DEF(double,le)
4>GROUPE{Et NP{le double} PP{d' ici à NP{1992}} .}

SUBJ(compte,département)
OBJ(réaliser,port)
OBJ(longe,ville)
COREF_REL(fleuve,qui)
VMOD_POSIT2(jeter,Palavas)
VMOD_POSIT2(compte,distance)
VMOD_POSIT1(compte,projets)
VMOD_POSIT1(compte,moins)
VMOD_POSIT1(compte,pas)
VMOD_POSIT1(jeter,Méditerranée)
VMOD(longe,jeter)
NMOD_POSIT1(ans,annonce)
NMOD_POSIT1(port,plaisance)
NMOD_POSIT1(département,Hérault)
NMOD_POSIT1(maire,Montpellier)
NMOD_POSIT1(Montpellier,intention)
NMOD_POSIT1(plaisance,Lez)
NMOD_POSIT2(port,Lez)
NMOD_POSIT2(maire,intention)
NMOD_POSIT1(annonce,maire)
NMOD_POSIT1(distance,8 kilomètres)
NMOD(intention,réaliser)
PREPOBJ(8 kilomètres,d')
PREPOBJ(distance,sur)
PREPOBJ(projets,de)
PREPOBJ(Hérault,de)
PREPOBJ(Palavas,à)
PREPOBJ(Méditerranée,dans)
PREPOBJ(Lez,sur)
PREPOBJ(plaisance,de)
PREPOBJ(intention,de)
PREPOBJ(Montpellier,de)
PREPOBJ(maire,par)
PREPOBJ(annonce,après)
PREPOBJ(jeter,avant de)
PREPOBJ(réaliser,de)
DETERM_NUM(kilomètres,8)
DETERM_NUM(projets,trois)
DETERM_NUM(ans,Deux)
DETERM(distance,une)
DETERM_DEF(Hérault,l')
DETERM_DEF(département,le)
DETERM_DEF(Méditerranée,la)
DETERM_DEF(ville,la)
DETERM_DEF(fleuve,le)
DETERM_DEF(Lez,le)
DETERM(port,un)
DETERM_POSS(intention,son)
DETERM_DEF(maire,le)
DETERM_DEF(annonce,l')
CONNECT_REL(longe,qui)
NEGAT(compte)
5>GROUPE{SC{NP{Deux ans} PP{après NP{l' annonce}} PP{par NP{le maire}} PP{de NP{Montpellier}} PP{de NP{son intention}} IV{de réaliser} NP{un port} PP{de NP{plaisance}} PP{sur NP{le Lez}} , NP{le fleuve} SC{BG{qui} FV{longe}} NP{la ville} IV{avant de se jeter} PP{dans NP{la Méditerranée}} PP{à NP{Palavas}} , NP{le département} PP{de NP{l' Hérault}} FV{ne compte}} pas moins PP{de NP{trois projets}} PP{sur NP{une distance}} PP{d' à peine NP{NOUN{8 kilomètres}}} .}

SUBJ(démarrent,travaux)
SUBJ(agit,il)
OBJ(embellir,entrée)
COREF_REL(anneaux,dont)
VMOD_POSIT1(agit,simplement)
VMOD_POSIT1(démarrent,tout juste)
VMOD(agit,Palavas)
VMOD(agit,embellir)
NMOD_POSIT1(station,création)
NMOD_POSIT1(port,Lez)
NMOD_POSIT1(Lez,anneaux)
NMOD_POSIT2(port,anneaux)
NMOD_POSIT1(création,port)
NMOD_POSIT1(entrée,station)
PREPOBJ(anneaux,de)
PREPOBJ(Lez,sur)
PREPOBJ(port,d')
PREPOBJ(création,par)
PREPOBJ(station,de)
PREPOBJ(Palavas,A)
PREPOBJ(embellir,d')
DETERM_NUM(anneaux,30)
DETERM_DEF(travaux,les)
DETERM_DEF(Lez,le)
DETERM(port,un)
DETERM_DEF(création,la)
DETERM_DEF(station,la)
DETERM_DEF(entrée,l')
REFLEX(agit,s')
CONNECT_REL(démarrent,dont)
6>GROUPE{SC{PP{A NP{Palavas}} , NP{il} FV{s' agit}} simplement IV{d' embellir} NP{l' entrée} PP{de NP{la station}} PP{par NP{la création}} PP{d' NP{un port}} PP{sur NP{le Lez}} PP{de NP{30 anneaux}} , SC{BG{dont} NP{les travaux} FV{démarrent}} tout juste .}

NMOD_POSIT1(5 millions,francs)
PREPOBJ(francs,de)
7>GROUPE{NP{Coût} : NP{5 millions} PP{de NP{francs}} .}

SUBJ_PASSIVE(programmée,inauguration)
DEEPOBJ(programmée,inauguration)
VMOD_POSIT1(programmée,ouverture)
NMOD_POSIT1(saison,prochaine)
NMOD_POSIT1(ouverture,saison)
PREPOBJ(saison,de)
PREPOBJ(ouverture,pour)
DETERM_DEF(saison,la)
DETERM_DEF(ouverture,l')
DETERM_DEF(inauguration,L')
AUXIL_PASSIVE(programmée,est)
8>GROUPE{SC{NP{L' inauguration} FV{est programmée}} PP{pour NP{l' ouverture}} PP{de NP{la AP{prochaine} saison}} .}

SUBJ(est,projet)
OBJ_SPRED(est,ambitieux)
VMOD(est,fleuve)
NMOD_POSIT1(projet,Port - Ariane)
NMOD_POSIT1(fleuve,Lattes)
PREPOBJ(Port - Ariane,de)
PREPOBJ(Lattes,à)
PREPOBJ(fleuve,En amont du)
DETERM_DEF(projet,le)
9>GROUPE{SC{PP{En amont du NP{fleuve}} , PP{à NP{Lattes}} , NP{le projet} PP{de NP{NOUN{Port - Ariane}}} FV{est}} AP{plus ambitieux} .}

SUBJ(entre,municipalité)
SUBJ_PASSIVE_REL(étudié,projet)
OBJ(nécessitant,construction)
DEEPSUBJ(étudié,architectes)
DEEPOBJ(étudié,projet)
COREF_REL(projet,qui)
VMOD_POSIT1(étudié,actuellement)
VMOD_POSIT1(accompagnée,projet)
VMOD_POSIT1(correspondant,habitants)
VMOD_POSIT1(entre,phase)
NMOD_POSIT1(projet,immobilier)
NMOD_POSIT1(architectes,locaux)
NMOD_POSIT1(écluse,accompagnée)
NMOD_POSIT1(phase,seconde)
NMOD_POSIT1(phase,réalisation)
NMOD_POSIT1(port,anneaux)
NMOD_POSIT1(réalisation,port)
NMOD_POSIT1(construction,écluse)
PREPOBJ(architectes,par)
PREPOBJ(habitants,à)
PREPOBJ(projet,d')
PREPOBJ(écluse,d')
PREPOBJ(anneaux,d')
PREPOBJ(port,d')
PREPOBJ(réalisation,de)
PREPOBJ(phase,dans)
DETERM_NUM(architectes,trois)
DETERM_NUM(habitants,4 500)
DETERM_NUM(anneaux,300)
DETERM(projet,un)
DETERM(écluse,une)
DETERM_DEF(construction,la)
DETERM(port,un)
DETERM_DEF(réalisation,la)
DETERM_DEF(phase,la)
DETERM_DEF(municipalité,La)
AUXIL_PASSIVE(étudié,est)
CONNECT_REL(étudié,qui)
10>GROUPE{SC{NP{La municipalité} FV{entre}} PP{dans NP{la AP{seconde} phase}} PP{de NP{la réalisation}} PP{d' NP{un port}} PP{d' NP{environ 300 anneaux}} , GV{nécessitant} NP{la construction} PP{d' NP{une écluse}} accompagnée PP{d' NP{un projet}} AP{immobilier} GV{correspondant} PP{à NP{4 500 habitants}} et SC{BG{qui} FV{est actuellement étudié}} PP{par NP{trois architectes}} AP{locaux} .}

SUBJ_PASSIVE(créée,société)
OBJ(créée,fin janvier)
DEEPOBJ(créée,société)
NMOD_POSIT1(sondages,archéologiques)
NMOD_POSIT1(économie,mixte)
NMOD_POSIT1(sondages,terminés)
NMOD(fin,janvier)
NMOD_POSIT1(société,économie)
PREPOBJ(économie,d')
DETERM(société,une)
DETERM_DEF(sondages,Les)
AUXIL_PASSIVE(créée,sera)
11>GROUPE{SC{NP{Les sondages} AP{archéologiques} terminés , NP{une société} PP{d' NP{économie}} AP{mixte} FV{sera créée}} NP{NOUN{fin janvier}} .}

SUBJ(devraient,coups)
SUBJ_PASSIVE(donnés,coups)
OBJ(devraient,donnés)
DEEPOBJ(donnés,coups)
VMOD_POSIT1(donnés,année)
VMOD_POSIT1(commercialisée,1992)
VMOD_POSIT2(donnés,tranche)
NMOD_POSIT1(tranche,commercialisée)
NMOD_POSIT1(coups,premiers)
NMOD_POSIT1(tranche,première)
NMOD_POSIT1(coups,pioche)
PREPOBJ(1992,en)
PREPOBJ(tranche,pour)
PREPOBJ(année,à la fin de)
PREPOBJ(pioche,de)
DETERM(tranche,une)
DETERM_DEF(année,l')
DETERM_DEF(coups,Les)
AUXIL_PASSIVE(donnés,être)
12>GROUPE{SC{NP{Les AP{premiers} coups} PP{de NP{pioche}} FV{devraient}} IV{être donnés} PP{à la fin de NP{l' année}} PP{pour NP{une AP{première} tranche}} commercialisée PP{en NP{NOUN{1992}}} .}

SUBJ(interdit,dimension)
OBJ(interdit,échéance)
VMOD_POSIT1(interdit,toute)
VMOD(interdit,Montpellier)
NMOD_POSIT1(échéance,précise)
NMOD_POSIT1(dimension,projet)
PREPOBJ(projet,du)
PREPOBJ(Montpellier,A)
DETERM_DEF(dimension,la)
13>GROUPE{SC{PP{A NP{Montpellier}} , NP{la dimension} PP{du NP{projet}} FV{interdit}} toute NP{échéance} AP{précise} .}

OBJ_SPRED(apparait,définitif)
OBJ_COORD_SPRED(apparait,début)
DEEPSUBJ(aéré,espaces)
VMOD_POSIT1(apparait,aujourd'hui)
VMOD_POSIT1(aéré,espaces)
NMOD_POSIT1(port,fluvial)
NMOD_POSIT1(espaces,verts)
NMOD_POSIT1(espaces,seul)
NMOD_POSIT1(ville,aéré)
NMOD_POSIT1(pompe,grande)
NMOD_POSIT1(quartier,nouveau)
NMOD_POSIT1(mairie,future)
NMOD_POSIT1(ans,annonce)
NMOD_POSIT1(port,quartier)
NMOD_POSIT1(annonce,pompe)
NMOD_POSIT1(pompe,création)
NMOD_POSIT1(quartier,habitants)
NMOD_POSIT1(habitants,est)
NMOD_POSIT1(mairie,site)
NMOD_POSIT1(site,fin)
NMOD_POSIT1(fin,année)
NMOD_POSIT2(ans,pompe)
NMOD_POSIT2(port,habitants)
NMOD_POSIT2(annonce,création)
NMOD_POSIT2(quartier,est)
NMOD_POSIT2(mairie,fin)
NMOD_POSIT2(site,année)
NMOD_POSIT1(construction,mairie)
NMOD_POSIT1(est,ville)
NMOD_POSIT1(création,Port - Mariane)
NMOD_POSIT1(début,construction)
COORDITEMS(définitif,début)
PREPOBJ(année,de)
PREPOBJ(fin,pour)
PREPOBJ(site,sur)
PREPOBJ(mairie,de)
PREPOBJ(construction,de)
PREPOBJ(espaces,par)
PREPOBJ(ville,de)
PREPOBJ(est,à)
PREPOBJ(habitants,de)
PREPOBJ(quartier,au coeur d')
PREPOBJ(Port - Mariane,de)
PREPOBJ(création,de)
PREPOBJ(pompe,en)
PREPOBJ(annonce,après)
DETERM_NUM(espaces,trois)
DETERM_NUM(habitants,20000)
DETERM_NUM(ans,Deux)
DETERM_DEF(année,l')
DETERM_DEF(fin,la)
DETERM_DEF(site,le)
DETERM_DEF(mairie,la)
DETERM_DEF(construction,la)
DETERM_DEF(début,le)
DETERM_DEF(ville,la)
DETERM_DEF(est,l')
DETERM(quartier,un)
DETERM_DEF(création,la)
DETERM_DEF(annonce,l')
14>GROUPE{SC{NP{Deux ans} PP{après NP{l' annonce}} PP{en NP{AP{grande} pompe}} PP{de NP{la création}} PP{de NP{NOUN{Port - Mariane}}} , NP{port} AP{fluvial} PP{au coeur d' NP{un AP{nouveau} quartier}} PP{de NP{20000 habitants}} PP{à NP{l' est}} PP{de NP{la ville}} , aéré PP{par NP{trois espaces}} AP{verts} , AP{seul} FV{apparait}} comme AP{définitif} aujourd'hui NP{le début} PP{de NP{la construction}} PP{de NP{la AP{future} mairie}} PP{sur NP{le site}} PP{pour NP{la fin}} PP{de NP{l' année}} .}

SUBJ_PASSIVE(rangée,maquette)
DEEPOBJ(rangée,maquette)
VMOD_POSIT1(exposée,auparavant)
VMOD_POSIT1(rangée,placard)
VMOD_POSIT1(exposée,hall)
NMOD_POSIT1(Ricardo Bofill,exposée)
NMOD_POSIT1(maquette,somptueuse)
NMOD_POSIT1(hall,grand)
NMOD(Ricardo,Bofill)
NMOD_POSIT1(maquette,Ricardo Bofill)
NMOD_POSIT1(hall,mairie)
PREPOBJ(placard,au)
PREPOBJ(mairie,de)
PREPOBJ(hall,dans)
PREPOBJ(Ricardo Bofill,de)
DETERM_DEF(mairie,la)
DETERM_DEF(hall,le)
DETERM_DEF(maquette,La)
AUXIL_PASSIVE(été,a)
AUXIL_PASSIVE(rangée,été)
15>GROUPE{SC{NP{La AP{somptueuse} maquette} PP{de NP{NOUN{Ricardo Bofill}}} exposée auparavant PP{dans NP{le AP{grand} hall}} PP{de NP{la mairie}} FV{a été rangée}} PP{au NP{placard}} .}

SUBJ(explique,Raymond Dugrand)
SUBJ(agissait,il)
OBJ(donner,image)
OBJ(attirer,promoteurs)
OBJ(explique,adjoint)
VMOD_POSIT1(chargé,urbanisme)
VMOD_POSIT1(agissait,maquette)
VMOD(attirer,donner)
VMOD(donner,attirer)
NMOD_POSIT1(image,forte)
NMOD_POSIT1(adjoint,chargé)
NMOD_POSIT1(appel,destinée)
NMOD_POSIT1(adjoint,premier)
NMOD(Raymond,Dugrand)
NMOD_POSIT1(maquette,appel)
ADJMOD(forte,projet)
PREPOBJ(projet,du)
PREPOBJ(appel,d')
PREPOBJ(maquette,d')
PREPOBJ(urbanisme,de)
PREPOBJ(attirer,pour)
PREPOBJ(donner,à)
DETERM_DEF(promoteurs,les)
DETERM(image,une)
DETERM(maquette,une)
DETERM_DEF(urbanisme,l')
REFLEX(agissait,s')
16>GROUPE{SC{" AP{Logique} , FV{explique}} NP{NOUN{Raymond Dugrand}} , NP{AP{premier} adjoint} chargé PP{de NP{l' urbanisme}} SC{, NP{il} FV{s' agissait}} PP{d' NP{une maquette}} PP{d' NP{appel}} destinée IV{à donner} NP{une image} AP{forte} PP{du NP{projet}} IV{pour attirer} NP{les promoteurs} .}

SUBJ(vu,architecte)
OBJ(vu,responsable)
VMOD_POSIT1(récusé,poste)
NMOD_POSIT1(architecte,catalan)
NMOD_POSIT1(architecte,annoncé)
NMOD_POSIT1(responsable,réalisation)
NMOD_POSIT1(réalisation,Port - Mariane)
PREPOBJ(poste,pour)
PREPOBJ(Port - Mariane,de)
PREPOBJ(réalisation,de)
DETERM_DEM(poste,ce)
DETERM_DEF(réalisation,la)
DETERM_DEF(architecte,l')
REFLEX(vu,s')
AUXIL(vu,est)
17>GROUPE{SC{" Entre-temps , NP{l' architecte} AP{catalan} , initialement annoncé comme NP{responsable} PP{de NP{la réalisation}} PP{de NP{NOUN{Port - Mariane}}} , FV{s' est vu}} récusé PP{pour NP{ce poste}} .}

SUBJ(réalisé,Bofill)
SUBJ(accepterait,aucun d')
SUBJ(travailler,Pei)
SUBJ(ajoute,Georges Frêche)
SUBJ_PASSIVE(envisagés,Pei)
SUBJ_PASSIVE_COORD(envisagés,Foster)
SUBJ_PASSIVE_COORD(envisagés,Rogers)
SUBJ_PASSIVE_COORD(envisagés,Meier)
SUBJ_PASSIVE_COORD(envisagés,Jonshon)
SUBJ_COORD(travailler,Jonshon)
SUBJ_COORD(travailler,Meier)
SUBJ_COORD(travailler,Rogers)
SUBJ_COORD(travailler,Foster)
SUBJ_COORD(travailler,Botta)
SUBJ_PASSIVE_COORD(envisagés,Botta)
OBJ(renouveler,style)
OBJ(réalisé,quartier)
OBJ(ajoute,réaction)
OBJ(voir,renouveler)
DEEPOBJ(envisagés,Botta)
DEEPOBJ(envisagés,Pei)
DEEPOBJ(envisagés,Foster)
DEEPOBJ(envisagés,Rogers)
DEEPOBJ(envisagés,Meier)
DEEPOBJ(envisagés,Jonshon)
VMOD_POSIT1(réalisé,déjà)
VMOD(envisagés,encore)
VMOD_POSIT1(réalisé,Montpellier)
VMOD_POSIT1(travailler,tutelle)
VMOD(envisagés,travailler)
NMOD_POSIT1(volonté,claire)
NMOD_POSIT1(architectes,internationaux)
NMOD_POSIT1(architectes,pressentis)
NMOD(Georges,Frêche)
NMOD(quartier,Antigone)
NMOD_POSIT1(style,ville)
NMOD_POSIT1(part,maire)
NMOD_POSIT1(tutelle,Bofill)
NMOD_POSIT1(volonté,part)
NMOD_POSIT1(réaction,dizaine)
NMOD_POSIT1(dizaine,architectes)
NMOD(volonté,voir)
COORDITEMS(Pei,Jonshon)
COORDITEMS(Pei,Meier)
COORDITEMS(Pei,Rogers)
COORDITEMS(Pei,Foster)
COORDITEMS(Pei,Botta)
PREPOBJ(Bofill,de)
PREPOBJ(tutelle,sous)
PREPOBJ(architectes,d')
PREPOBJ(dizaine,de)
PREPOBJ(Montpellier,à)
PREPOBJ(ville,de)
PREPOBJ(maire,du)
PREPOBJ(part,de)
PREPOBJ(volonté,A)
PREPOBJ(travailler,de)
PREPOBJ(voir,de)
DETERM_DEF(tutelle,la)
DETERM_DEF(dizaine,la)
DETERM_DEF(réaction,la)
DETERM_DEF(quartier,le)
DETERM_POSS(ville,sa)
DETERM_DEF(style,le)
DETERM_DEF(part,la)
DETERM_DEF(volonté,la)
AUXIL(réalisé,a)
AUXIL_PASSIVE(envisagés,sont)
NEGAT(accepterait)
18>GROUPE{SC{PP{A NP{la volonté}} AP{désormais claire} PP{de NP{la part}} PP{du NP{maire}} , NP{NOUN{Georges Frêche}} , IV{de voir} IV{renouveler} NP{le style} PP{de NP{sa ville}} SC{BG{(} NP{Bofill} FV{a déjà réalisé}} PP{à NP{Montpellier}} NP{le quartier} NP{Antigone} ) FV{s' ajoute}} NP{la réaction} PP{de NP{la dizaine}} PP{d' NP{architectes}} AP{internationaux} pressentis SC{BG{(} NP{Pei} , NP{Foster} , NP{Rogers} , NP{Meier} , NP{Jonshon} , ou encore NP{Botta} FV{sont envisagés}} ) SC{BG{:} NP{DET{aucun d'}} NP{eux} FV{n' accepterait}} IV{de travailler} PP{sous NP{la tutelle}} PP{de NP{Bofill}} .}

SUBJ(créera,chacun)
OBJ(créera,unités)
VMOD_POSIT1(créera,donc)
VMOD_POSIT1(créera,autonomie)
VMOD(créera,surface)
NMOD_POSIT1(surface,base)
NMOD_POSIT1(base,400 hectares)
NMOD_POSIT2(surface,400 hectares)
NMOD_POSIT1(unités,ensemble)
PREPOBJ(ensemble,de)
PREPOBJ(autonomie,en)
PREPOBJ(400 hectares,de)
PREPOBJ(base,de)
PREPOBJ(surface,Sur)
DETERM_NUM(hectares,400)
DETERM_DEF(ensemble,l')
DETERM_QUANT(unités,plusieurs)
DETERM(unités,une)
DETERM_QUANT(autonomie,toute)
DETERM(surface,une)
19>GROUPE{SC{PP{Sur NP{une surface}} PP{de NP{base}} PP{de NP{NOUN{400 hectares}}} , NP{chacun} FV{créera}} donc PP{en NP{toute autonomie}} NP{une ou plusieurs unités} PP{de NP{l' ensemble}} .}

SUBJ(sera,Port - Mariane)
SUBJ(fera,marché)
SUBJ(dit,Raymond Dugrand)
OBJ(fera,que)
OBJ_SPRED(sera,ce)
VMOD(sera,De même)
VMOD_POSIT1_SUBORD(sera,fera)
VMOD(fera,en)
NMOD(Raymond,Dugrand)
DETERM_DEF(marché,le)
CONNECT(fera,que)
20>GROUPE{SC{De même , " NP{NOUN{Port - Mariane}} FV{sera}} NP{ce} SC{BG{que} NP{le marché} FV{en fera}} " SC{, FV{dit}} NP{NOUN{Raymond Dugrand}} .}

SUBJ(dépendra,nombre)
VMOD_POSIT1(dépendra,rythme)
NMOD_POSIT1(appartements,réalisés)
NMOD_POSIT1(rythme,croissance)
NMOD_POSIT1(habitants,prévisions)
NMOD_POSIT1(croissance,ville)
NMOD_POSIT1(nombre,appartements)
PREPOBJ(prévisions,selon)
PREPOBJ(habitants,entre)
PREPOBJ(ville,de)
PREPOBJ(croissance,de)
PREPOBJ(rythme,du)
PREPOBJ(appartements,d')
DETERM_NUM(habitants,30 000)
DETERM_NUM(habitants,10 000)
DETERM_DEF(prévisions,les)
DETERM_DEF(ville,la)
DETERM_DEF(nombre,Le)
21>GROUPE{SC{NP{Le nombre} PP{d' NP{appartements}} effectivement réalisés FV{dépendra}} PP{du NP{rythme}} PP{de NP{croissance}} PP{de NP{la ville}} : PP{entre NP{10 000 et 30 000 habitants}} , PP{selon NP{les prévisions}} .}

OBJ(rendre,fleuve)
OBJ_SPRED(être,l')
OBJ_SPRED(Reste,problèmes)
COREF_REL(fleuve,qui)
VMOD_POSIT1(être,siècle)
VMOD(résoudre,rendre)
VMOD(cessé,être)
NMOD_POSIT1(problèmes,techniques)
NMOD_POSIT1(ans,histoire)
NMOD_POSIT1(qui,ans)
NMOD(problèmes,résoudre)
PREPOBJ(siècle,au début du)
PREPOBJ(histoire,d')
PREPOBJ(ans,après)
PREPOBJ(être,de)
PREPOBJ(rendre,pour)
PREPOBJ(résoudre,à)
DETERM_NUM(ans,deux mille)
DETERM(fleuve,un)
DETERM_DEF(problèmes,les)
AUXIL(cessé,a)
CONNECT_REL(cessé,qui)
22>GROUPE{SC{FV{Reste}} NP{les problèmes} AP{techniques} IV{à résoudre} IV{pour rendre} AP{navigable} NP{un fleuve} SC{BG{qui} , PP{après NP{deux mille ans}} PP{d' NP{histoire}} , FV{a cessé}} IV{de l' être} PP{au début du NP{siècle}} .}

SUBJ(sont,problèmes)
OBJ_SPRED(sont,maitrisables)
NMOD_POSIT1(études,consultés)
NMOD_POSIT1(ceux,inondation)
NMOD_POSIT1(bureaux,études)
NMOD_POSIT1(alimentation,eau)
NMOD_POSIT1(conclusions,bureaux)
NMOD_POSIT1(problèmes,alimentation)
PREPOBJ(inondation,d')
PREPOBJ(eau,en)
PREPOBJ(alimentation,d')
PREPOBJ(études,d')
PREPOBJ(bureaux,de)
PREPOBJ(conclusions,D'après)
DETERM_DEF(problèmes,les)
DETERM_QUANT(bureaux,tous les)
DETERM_DEF(conclusions,les)
23>GROUPE{SC{PP{D'après NP{les conclusions}} PP{de NP{tous les bureaux}} PP{d' NP{études}} consultés , NP{les problèmes} PP{d' NP{alimentation}} PP{en NP{eau}} comme NP{ceux} PP{d' NP{inondation}} FV{sont}} AP{aujourd'hui maitrisables} .}

SUBJ(proviennent,incertitudes)
VMOD_POSIT1(proviennent,plutôt)
VMOD_POSIT1(proviennent,difficulté)
NMOD_POSIT1(rival,politique)
NMOD_POSIT1(dialogue,persistante)
NMOD_POSIT1(maire,socialiste)
NMOD_POSIT1(incertitudes,véritables)
NMOD(George,Frêche)
NMOD(Michel,Vaillat)
NMOD(maire,George Frêche)
NMOD_POSIT1(maire,Lattes)
NMOD_POSIT1(dialogue,maire)
NMOD_POSIT1(difficulté,dialogue)
PREPOBJ(Lattes,de)
PREPOBJ(maire,entre)
PREPOBJ(dialogue,de)
PREPOBJ(difficulté,de)
DETERM_DEF(maire,le)
DETERM_POSS(rival,son)
DETERM_DEF(maire,le)
DETERM_DEF(difficulté,la)
DETERM_DEF(incertitudes,Les)
24>GROUPE{SC{NP{Les AP{véritables} incertitudes} FV{proviennent}} plutôt PP{de NP{la difficulté}} PP{de NP{dialogue}} AP{persistante} PP{entre NP{le maire}} AP{socialiste} NP{NOUN{George Frêche}} et NP{son rival} AP{politique} , NP{le maire} PP{de NP{Lattes}} , NP{NOUN{Michel Vaillat}} INS{( NP{UDF} )} .}

SUBJ(contraindrait,Port - Mariane)
SUBJ(rejette,ville)
SUBJ(précise,Jean Robert Moner)
SUBJ(exclut,ville)
SUBJ_IMPERSO(fallait,il)
OBJ(remonter,niveau)
OBJ(faciliter,circulaton)
OBJ(instaurer,péage)
OBJ(trouver,moyen)
OBJ(amortir,investissements)
OBJ(rejette,proposition)
OBJ(exclut,idée)
OBJ(contraindrait,que)
OBJ(précise,secrétaire)
OBJ(fallait,trouver)
VMOD_POSIT1(rejette,toujours)
VMOD_POSIT1(exclut,pas)
VMOD_POSIT1(exclut,a priori)
VMOD_POSIT1_SUBORD(instaurer,fallait)
VMOD_POSIT1(située,Lez)
VMOD(contraindrait,nous)
VMOD(remonter,faciliter)
VMOD(contraindrait,faire)
NMOD_POSIT1(proposition,montpelliéraine)
NMOD_POSIT1(secrétaire,général)
NMOD_POSIT1(Lattes,située)
NMOD(Jean,Robert)
NMOD(Robert,Moner)
NMOD_POSIT1(ville,Lattes)
NMOD_POSIT1(niveau,fleuve)
NMOD_POSIT1(circulaton,bateaux)
NMOD_POSIT1(secrétaire,mairie)
NMOD_POSIT1(mairie,Lattes)
NMOD_POSIT2(secrétaire,Lattes)
NMOD(moyen,amortir)
NMOD(idée,instaurer)
NMOD(proposition,remonter)
COORDITEMS_SC(rejette,exclut)
PREPOBJ(Lattes,de)
PREPOBJ(mairie,de)
PREPOBJ(bateaux,des)
PREPOBJ(fleuve,du)
PREPOBJ(Lez,en aval du)
PREPOBJ(Lattes,de)
PREPOBJ(faire,à)
PREPOBJ(amortir,d')
PREPOBJ(instaurer,d')
PREPOBJ(faciliter,pour)
PREPOBJ(remonter,de)
DETERM_DEF(mairie,la)
DETERM_DEF(investissements,les)
DETERM(moyen,un)
DETERM(péage,un)
DETERM_DEF(idée,l')
DETERM_DEF(circulaton,la)
DETERM_DEF(niveau,le)
DETERM_DEF(proposition,la)
DETERM_DEF(ville,La)
CONNECT(fallait,si jamais)
CONNECT(contraindrait,que)
NEGAT(exclut)
25>GROUPE{SC{NP{La ville} PP{de NP{Lattes}} , située PP{en aval du NP{Lez}} , FV{rejette}} toujours NP{la proposition} AP{montpelliéraine} IV{de remonter} NP{le niveau} PP{du NP{fleuve}} IV{pour faciliter} NP{la circulaton} PP{des NP{bateaux}} SC{BG{et} FV{n' exclut}} pas a priori NP{l' idée} IV{d' instaurer} NP{un péage} " SC{BG{si jamais} NP{il} FV{fallait}} IV{trouver} NP{un moyen} IV{d' amortir} NP{les investissements} SC{BG{que} FV{nous contraindrait}} IV{à faire} NP{NOUN{Port - Mariane}} " SC{, FV{précise}} NP{NOUN{Jean Robert Moner}} , NP{secrétaire} AP{général} PP{de NP{la mairie}} PP{de NP{Lattes}} .}

SUBJ(pense,l'on)
SUBJ_REL(fait,Menace)
SUBJ(sourire,Montpellier)
SUBJ(avoir,moyens)
OBJ_COORD(fait,avoir)
OBJ(fait,sourire)
COREF_REL(Montpellier,où)
COREF_REL(Menace,qui)
VMOD_POSIT1(sourire,Montpellier)
NMOD_POSIT2(moyens,supérieurs)
NMOD_POSIT1(moyens,rétorsion)
NMOD_POSIT1(ceux,maire)
NMOD_POSIT1(maire,Lattes)
ADJMOD(supérieurs,ceux)
COORDITEMS(sourire,avoir)
PREPOBJ(Lattes,de)
PREPOBJ(maire,du)
PREPOBJ(ceux,à)
PREPOBJ(rétorsion,de)
PREPOBJ(Montpellier,à)
DETERM(moyens,des)
CONNECT_REL(fait,qui)
CONNECT_REL(pense,où)
26>GROUPE{NP{Menace} SC{BG{qui} FV{fait}} IV{sourire} PP{à NP{Montpellier}} , SC{BG{où} NP{l'on} FV{pense}} IV{avoir} NP{des moyens} PP{de NP{rétorsion}} AP{supérieurs} PP{à NP{ceux}} PP{du NP{maire}} PP{de NP{Lattes}} .}

SUBJ_PASSIVE(liés,intérêts)
OBJ(envisager,négociations)
DEEPOBJ(liés,intérêts)
VMOD_POSIT1(envisager,tant)
NMOD_POSIT1(intérêts,communes)
ADJMOD(Impossible,envisager)
PREPOBJ(communes,des)
PREPOBJ(fait,en)
PREPOBJ(envisager,de)
DETERM_NUM(communes,deux)
DETERM_DEF(intérêts,les)
DETERM(négociations,de)
AUXIL_PASSIVE(liés,sont)
NEGAT(envisager)
27>GROUPE{SC{AP{Impossible} PP{en NP{fait}} IV{de ne pas envisager} NP{de négociations} , tant NP{les intérêts} PP{des NP{deux communes}} FV{sont liés}} .}

SUBJ(saisir,préfet)
SUBJ(prononce,il)
SUBJ(demandé,préfet)
OBJ(clarifier,points)
OBJ(saisir,Conseil d'Etat)
OBJ_SPRED(rester,obscurs)
OBJ(voir,clarifier)
OBJ(pourraient,rester)
COREF_REL(points,qui)
VMOD_POSIT1(prononce,d'abord)
VMOD_POSIT1_SUBORD(saisir,prononce)
VMOD_POSIT1(prononce,notion)
VMOD_POSIT1(demandé,ministère)
VMOD(demandé,saisir)
NMOD_POSIT1(Yves - Jean Bentejac,soucieux)
NMOD_POSIT1(points,derniers)
NMOD(Yves - Jean,Bentejac)
NMOD_POSIT1(préfet,Hérault)
NMOD_POSIT1(ministère,intérieur)
NMOD_POSIT1(notion,propriété)
NMOD_POSIT1(propriété,rives)
NMOD_POSIT1(rives,Lez)
NMOD_POSIT2(notion,rives)
NMOD_POSIT2(propriété,Lez)
ADJMOD(soucieux,voir)
PREPOBJ(Lez,du)
PREPOBJ(rives,des)
PREPOBJ(propriété,de)
PREPOBJ(notion,sur)
PREPOBJ(intérieur,de)
PREPOBJ(ministère,au)
PREPOBJ(Hérault,de)
PREPOBJ(affaire,Dans)
PREPOBJ(saisir,de)
PREPOBJ(voir,de)
DETERM_DEF(notion,la)
DETERM_DEF(Conseil d'Etat,le)
DETERM_DEF(intérieur,l')
DETERM_DEF(points,les)
DETERM_DEF(Hérault,l')
DETERM_DEF(préfet,le)
DETERM_DEM(affaire,cette)
REFLEX(prononce,se)
AUXIL(demandé,a)
CONNECT_REL(pourraient,qui)
CONNECT(prononce,afin qu')
28>GROUPE{SC{PP{Dans NP{cette affaire}} , NP{le préfet} PP{de NP{l' Hérault}} , NP{NOUN{NOUN{Yves - Jean} Bentejac}} , AP{soucieux} IV{de voir} IV{clarifier} NP{les AP{derniers} points} SC{BG{qui} FV{pourraient}} IV{rester} AP{obscurs} , FV{a demandé}} PP{au NP{ministère}} PP{de NP{l' intérieur}} IV{de saisir} NP{le Conseil d'Etat} , SC{BG{afin qu'} NP{il} FV{se prononce}} d'abord PP{sur NP{la notion}} PP{de NP{propriété}} PP{des NP{rives}} PP{du NP{Lez}} .}

SUBJ(appartiennent,Celles-ci)
SUBJ_REL(pourraient,particuliers)
SUBJ(avoir,particuliers)
SUBJ(dire,particuliers)
OBJ(avoir,mot)
OBJ(pourraient,avoir)
COREF_REL(particuliers,qui)
VMOD_POSIT1(appartiennent,part)
VMOD_POSIT1(dire,passage)
VMOD_POSIT2(appartiennent,communes)
VMOD_POSIT2(appartiennent,autre)
VMOD_POSIT2(appartiennent,particuliers)
VMOD(avoir,dire)
NMOD_POSIT1(part,communes)
NMOD_POSIT1(communes,autre)
NMOD_POSIT1(passage,bateaux)
NMOD_POSIT2(part,autre)
PREPOBJ(bateaux,des)
PREPOBJ(passage,sur)
PREPOBJ(particuliers,à)
PREPOBJ(autre,pour)
PREPOBJ(communes,aux)
PREPOBJ(part,pour)
PREPOBJ(dire,à)
DETERM_DEF(passage,le)
DETERM_POSS(mot,leur)
DETERM_QUANT(particuliers,plusieurs)
DETERM(autre,une)
DETERM(part,une)
CONNECT_REL(pourraient,qui)
29>GROUPE{SC{NP{Celles-ci} FV{appartiennent}} PP{pour NP{une part}} PP{aux NP{communes}} , PP{pour NP{une autre}} PP{à NP{plusieurs particuliers}} SC{BG{qui} FV{pourraient}} IV{avoir} NP{leur mot} IV{à dire} PP{sur NP{le passage}} PP{des NP{bateaux}} .}

SUBJ(restent,élus)
SUBJ(appartiennent,terrains)
OBJ_SPRED(restent,sereins)
VMOD_POSIT1(appartiennent,villes)
NMOD_POSIT1(élus,locaux)
NMOD_POSIT1(terrains,concernés)
NMOD_POSIT1(Palavas,Montpellier)
PREPOBJ(villes,aux)
PREPOBJ(Montpellier,à)
PREPOBJ(Palavas,à)
DETERM_DEF(terrains,les)
DETERM_DEF(élus,les)
30>GROUPE{SC{Mais NP{les élus} AP{locaux} FV{restent}} AP{sereins} SC{BG{:} PP{à NP{Palavas}} comme PP{à NP{Montpellier}} , NP{les terrains} concernés FV{appartiennent}} PP{aux NP{villes}} .}

SUBJ(convaincu,commune)
SUBJ(vendre,commune)
OBJ(convaincu,propriétaire)
VMOD(convaincu,Lattes)
VMOD(convaincu,vendre)
NMOD_POSIT1(propriétaire,principal)
PREPOBJ(Lattes,A)
PREPOBJ(vendre,de)
DETERM_DEF(propriétaire,le)
DETERM_DEF(commune,la)
AUXIL(convaincu,a)
31>GROUPE{SC{PP{A NP{Lattes}} , NP{la commune} FV{a convaincu}} NP{le AP{principal} propriétaire} IV{de vendre} .}

SUBJ(demande,préfet)
SUBJ(donné,loi)
SUBJ(prononcer,préfet)
OBJ(donné,charge)
VMOD_POSIT1(demande,Conseil d'Etat)
VMOD_POSIT1(prononcer,point)
VMOD(demande,prononcer)
NMOD_POSIT1(ports,fluviaux)
NMOD_POSIT1(conseils,régionaux)
NMOD_POSIT1(point,dernier)
NMOD_POSIT1(loi,décentralisation)
NMOD_POSIT1(ports,conseils)
NMOD_POSIT1(gestion,ports)
NMOD_POSIT1(décentralisation,1983)
NMOD_POSIT1(charge,gestion)
PREPOBJ(conseils,aux)
PREPOBJ(ports,des)
PREPOBJ(gestion,de)
PREPOBJ(1983,de)
PREPOBJ(décentralisation,de)
PREPOBJ(point,sur)
PREPOBJ(Conseil d'Etat,au)
PREPOBJ(prononcer,de)
DETERM_DEF(gestion,la)
DETERM_DEF(charge,la)
DETERM_DEF(loi,la)
DETERM(point,un)
DETERM_DEF(préfet,Le)
REFLEX(prononcer,se)
AUXIL(donné,a)
32>GROUPE{SC{NP{Le préfet} FV{demande}} PP{au NP{Conseil d'Etat}} IV{de se prononcer} PP{sur NP{un AP{dernier} point}} SC{BG{:} NP{la loi} PP{de NP{décentralisation}} PP{de NP{1983}} FV{a donné}} NP{la charge} PP{de NP{la gestion}} PP{des NP{ports}} AP{fluviaux} PP{aux NP{conseils}} AP{régionaux} .}

SUBJ(devienne,Port - Mariane)
SUBJ(Peut,-on)
OBJ_PROPQUE(imaginer,devienne)
OBJ_SPRED(devienne,concession)
OBJ(Peut,imaginer)
NMOD_POSIT1(région,Languedoc-Roussillon)
NMOD_POSIT1(concession,région)
PREPOBJ(Languedoc-Roussillon,de)
PREPOBJ(région,de)
DETERM_DEF(région,la)
CONNECT(devienne,que)
33>GROUPE{SC{" FV{Peut}} NP{-on} IV{imaginer} SC{BG{que} NP{NOUN{Port - Mariane}} FV{devienne}} NP{concession} PP{de NP{la région}} PP{de NP{Languedoc-Roussillon}} ?}

SUBJ(interroge,Yves - Jean Bentejac)
NMOD(Yves - Jean,Bentejac)
REFLEX(interroge,s')
34>GROUPE{SC{" FV{s' interroge}} NP{NOUN{NOUN{Yves - Jean} Bentejac}} .}

SUBJ(refuse,ville)
SUBJ(envisager,ville)
OBJ(envisager,hypothèse)
VMOD_POSIT1(refuse,tout net)
VMOD(refuse,envisager)
NMOD_POSIT1(ville,Montpellier)
PREPOBJ(Montpellier,de)
PREPOBJ(envisager,d')
DETERM_DEM(hypothèse,cette)
DETERM_DEF(ville,La)
35>GROUPE{SC{NP{La ville} PP{de NP{Montpellier}} FV{refuse}} tout net IV{d' envisager} NP{cette hypothèse} .}

SUBJ(agit,il)
VMOD_POSIT1(transférer,régions)
VMOD(agit,esprit)
VMOD(agit,transférer)
NMOD_POSIT1(compétences,anciennes)
NMOD(Raymond,Dugrand)
NMOD_POSIT1(esprit,loi)
NMOD_POSIT1(régions,compétences)
NMOD_POSIT1(compétences,Etat)
NMOD_POSIT2(régions,Etat)
NMOD(Raymond Dugrand,argumenter)
PREPOBJ(Etat,de)
PREPOBJ(compétences,d')
PREPOBJ(régions,sur)
PREPOBJ(loi,de)
PREPOBJ(esprit,Dans)
PREPOBJ(transférer,de)
PREPOBJ(argumenter,d')
DETERM_DEF(Etat,l')
DETERM_DEF(régions,les)
DETERM_DEF(loi,la)
DETERM_DEF(esprit,l')
REFLEX(agit,s')
36>GROUPE{Et NP{NOUN{Raymond Dugrand}} IV{d' argumenter} SC{BG{:} " PP{Dans NP{l' esprit}} PP{de NP{la loi}} , NP{il} FV{s' agit}} IV{de transférer} PP{sur NP{les régions}} PP{d' NP{AP{anciennes} compétences}} PP{de NP{l' Etat}} .}

SUBJ(relève,il)
SUBJ(devrait,gestion)
SUBJ_PASSIVE(classé,Lez)
DEEPOBJ(classé,Lez)
VMOD_POSIT1(relève,pas)
VMOD_POSIT1(confiée,naturellement)
VMOD_POSIT1(classé,pas)
VMOD_POSIT1(confiée,ville)
VMOD_POSIT1(relève,domaine)
NMOD(ville,propriétaire)
NMOD_POSIT1(domaine,Etat)
PREPOBJ(ville,à)
PREPOBJ(Etat,de)
PREPOBJ(domaine,du)
DETERM_DEF(ville,la)
DETERM_POSS(gestion,sa)
DETERM_DEF(Etat,l')
DETERM_DEF(Lez,le)
AUXIL_PASSIVE(classé,étant)
AUXIL_PASSIVE(confiée,être)
NEGAT(étant)
NEGAT(relève)
37>GROUPE{SC{En l'occurrence , NP{le Lez} GV{n' étant pas classé} , NP{il} FV{ne relève}} pas PP{du NP{domaine}} PP{de NP{l' Etat}} ; NP{sa gestion} FV{devrait} IV{être naturellement confiée} PP{à NP{la ville}} NP{propriétaire} .}

