/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.Xip;
import com.xerox.xrce.xipui.ide.generator.CommonMethod;
import com.xerox.xrce.xipui.ide.generator.RuleGenerator;
import com.xerox.xrce.xipui.ui.graph.*;

import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;

/**
 *
 * @author csaillet
 */
public class BodyPanel extends GeneralPanel {

    /** Creates a new instance of BodyPan
     * @param context
     * @param id 
     */
    public BodyPanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/body.htm");
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);

        String choiceCategory = (String) this.getProperty("category");
        choiceCategoryBox.setSelectedItem(choiceCategory);
    }// </editor-fold>

    public void initPanel() {
        addRuleButton.setVisible(false);
        clearTempFileButton.setVisible(false);
        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        categoryLabel.setEnabled(false);
        choiceCategoryBox.setEnabled(false);
        dependencyLabel.setVisible(false);
        dependencyBox.setVisible(false);
        longestBox.setVisible(false);
        indexBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);
        String rule = (String) this.getProperty("rule");
        jTextArea2.setText(rule);
        jTextArea2.setToolTipText(rule);
    }

    public void next() {

        Vector vSelFeature = (Vector) this.getProperty("vectBodySelect");
        if (vSelFeature.size() == 0) {
            warning("select body please!");
        } else {
            LeftContextPanel left = new LeftContextPanel(getModuleContext(), id);
            left.leftContP();
        }
    }

    public void clear() {
        CommonMethod cmethod = new CommonMethod();
        Vector vecbody = (Vector) this.getProperty("vectBodySelect");
        if (vecbody.size() != 0) {
            cmethod.unselectXipNodeFromVector(vecbody, getModuleContext().getSessionGraph(id));
        }
        vecbody.clear();
        this.setProperty("vectBodySelect", vecbody);
    }

    public void close() {
    }

    public void back() {
        clear();
        CategoryPanel category = new CategoryPanel(getModuleContext(), id);
        category.categoryP();
    }

    public void indexWord() {
    }

    public void lonMatch() {
    }

    public void generateRule() {

        try {
            CommonMethod cmethod = new CommonMethod();
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            Vector v = session.getNodeGraphSelected();
            Vector selectedFeatures = new Vector();
            Vector selectFeat = new Vector();
            if (v != null) {
                Iterator ite = v.iterator();
                while (ite.hasNext()) {
                    NodeGraph ng = (NodeGraph) ite.next();
                    selectedFeatures.add(ng);
                }
            }
            Vector vSelFeature = cmethod.vectNodeGraphToSelectedObject(getModuleContext(), id, selectedFeatures);
            this.setProperty("vectBodySelect", vSelFeature);
            Vector vect = new Vector();
            Xip xip = getProject().getXip();
            XipResult xresult = xip.getXipResult();
            Vector vOfXipUnit = xresult.getXipUnits();
            XipUnit unit = (XipUnit) vOfXipUnit.get(0);
            XipNode root1 = unit.getRoot();
            int ghandler = getModuleContext().getProject().getGhandler();
            CommonMethod.readXipNode(root1, vect, xip, ghandler); // vect contient les noeuds de l arbre
//            cmethod.printXipNode(vect);
            // deselection si des noeuds ou des dependances ont ete selectionne
            boolean stop = false;
            Iterator it = vSelFeature.iterator();
            while (it.hasNext() && stop == false) {
                SelectedObject selobj = (SelectedObject) it.next();
                Object xnode = selobj.getObject();
                long index = ((NodeGraph) v.lastElement()).getIndex();
                if (xnode instanceof XipLeaf) {
                    warning("You can't choose the leaves !");
                    session.unSelectXipNode(index);
                    stop = true;
                } else if (xnode instanceof XipDependency) {
                    warning("You can't choose the dependencies !");
                    session.unSelectXipDependency(index);
                    stop = true;
                }
            }
            RuleGenerator generator = new RuleGenerator(getModuleContext(), id);
            String rule = generator.constructRules(vect);
            if (rule.equals("problem")) {
                long index = ((NodeGraph) v.lastElement()).getIndex();
                session.unSelectXipNode(index);
            } else {
                DEBUG_LOG.trace("body rule = " + rule);
                this.setProperty("rule", rule);
                jTextArea2.setText(rule);
                jTextArea2.setToolTipText(rule);
            }
        } catch (Exception e) {
            DEBUG_LOG.trace(e);
        }
    }

    public void bodyP() {
        this.setProperty("panel", "body");
        BodyPanel body = new BodyPanel(getModuleContext(), id);
        this.refreshTabbedPane(body);
    }
}
