/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.ui.graph.*;

import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;

/**
 *
 * @author csaillet
 */
public class DependencyTypePanel extends GeneralPanel {

    /** Creates a new instance of DependencyTypePanel
     * @param context
     * @param id 
     */
    public DependencyTypePanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        repaint();
        setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/dependencyType.htm");
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);

        String typeDependency = (String) this.getProperty("dependency");
        dependencyBox.setSelectedItem(typeDependency);
    }// </editor-fold>

    public void initPanel() {
        addRuleButton.setVisible(false);
        clearButton.setEnabled(false);
        clearTempFileButton.setVisible(false);
        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        categoryLabel.setVisible(false);
        choiceCategoryBox.setVisible(false);
        longestBox.setVisible(false);
        indexBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);
    }

    public void next() {
        String dependency = (String) dependencyBox.getSelectedItem();
        this.setProperty("dependency", dependency);
        String dep = (String) this.getProperty("dependency");
        DependencyNodePanel depNode = new DependencyNodePanel(getModuleContext(), id);
        depNode.nodeDependency();
    }

    public void back() {
        this.setProperty("dependency", "");
        SelectionRulePanel selection = new SelectionRulePanel(getModuleContext(), id);
        selection.selectionP();
    }

    public void clear() {
    }

    public void close() {
    }

    public void indexWord() {
    }

    public void lonMatch() {
    }

    public void generateRule() {
        // deselection automatique de toutes selections de noeuds
        SessionGraph session = getModuleContext().getSessionGraph(false, id);
        Vector v = session.getNodeGraphSelected();
        if ((v.size()) != 0) {
            warning("Wrong choice !");
            long index = ((NodeGraph) v.firstElement()).getIndex();
            if (((NodeGraph) v.firstElement()).getSelectedObject().getObject() instanceof XipNode) {
                session.unSelectXipNode(index);
            } else if (((NodeGraph) v.firstElement()).getSelectedObject().getObject() instanceof XipDependency) {
                session.unSelectXipDependency(index);
            }
        }
    }

    public void typeDependency() {
        this.setProperty("panel", "typedependency");
        DependencyTypePanel typeDep = new DependencyTypePanel(getModuleContext(), id);
        this.refreshTabbedPane(typeDep);
    }
}
