/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.Xip;
import com.xerox.xrce.xipui.ide.generator.CommonMethod;
import com.xerox.xrce.xipui.ide.generator.RuleGenerator;
import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;
import com.xerox.xrce.xipui.ui.graph.*;

/**
 *
 * @author csaillet
 */
public class DependencyNodePanel extends GeneralPanel {

    /** Creates a new instance of DependencyNodePanel
     * @param context
     * @param id 
     */
    public DependencyNodePanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        repaint();
        setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/dependencyNode.htm");
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {

        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);

        String typeDependency = (String) this.getProperty("dependency");
        dependencyBox.setSelectedItem(typeDependency);
    }// </editor-fold>

    public void initPanel() {
        addRuleButton.setVisible(false);
        clearTempFileButton.setVisible(false);
        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        dependencyLabel.setEnabled(false);
        dependencyBox.setEnabled(false);
        categoryLabel.setVisible(false);
        choiceCategoryBox.setVisible(false);
        longestBox.setVisible(false);
        indexBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);
        String rule = (String) this.getProperty("rule");
        jTextArea2.setText(rule);
        jTextArea2.setToolTipText(rule);
    }

    public void next() {
        Vector vecdependencynode = (Vector) this.getProperty("vectDependencySelect");
        if (vecdependencynode.size() == 0) {
            warning("select nodes please!");
        } else {
            FocusPanel focus = new FocusPanel(getModuleContext(), id);
            focus.focusP();
        }
    }

    public void back() {
        clear();
        DependencyTypePanel typeDep = new DependencyTypePanel(getModuleContext(), id);
        typeDep.typeDependency();
    }

    public void clear() {
        try {
            CommonMethod cmethod = new CommonMethod();
            Vector vecdependencynode = (Vector) this.getProperty("vectDependencySelect");
            if (vecdependencynode.size() != 0) {
                cmethod.unselectXipNodeFromVector(vecdependencynode, getModuleContext().getSessionGraph(id));
            }
            vecdependencynode.clear();
            this.setProperty("vectDependencySelect", vecdependencynode);
        } catch (Exception e) {
            DEBUG_LOG.trace("poblem unselect XipDependency !");
        }
    }

    public void close() {
    }

    public void indexWord() {
    }

    public void lonMatch() {
    }

    public void generateRule() {

        try {
            CommonMethod cmethod = new CommonMethod();
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            Vector v = session.getNodeGraphSelected();
            Vector selectedFeatures = new Vector();
            if (v != null) {
                Iterator ite = v.iterator();
                while (ite.hasNext()) {
                    NodeGraph ng = (NodeGraph) ite.next();
                    selectedFeatures.add(ng);
                }
            }
            Vector vecdependencynode = cmethod.vectNodeGraphToSelectedObject(getModuleContext(), id, selectedFeatures);
            this.setProperty("vectDependencySelect", vecdependencynode);
            Vector vect = new Vector();
            Xip xip = getProject().getXip();
            XipResult xresult = xip.getXipResult();
            Vector vOfXipUnit = xresult.getXipUnits();
            XipUnit unit = (XipUnit) vOfXipUnit.get(0);
            XipNode root1 = unit.getRoot();
            int ghandler = getModuleContext().getProject().getGhandler();
            CommonMethod.readXipNode(root1, vect, xip, ghandler);
//            cmethod.printXipNode(vect);    
            //verifie que le noeud selectionne n est pas une feuille si oui deselectionne
            boolean stop = false;
            Iterator it = vecdependencynode.iterator();
            while (it.hasNext() && stop == false) {
                SelectedObject selobj = (SelectedObject) it.next();
                Object xnode = selobj.getObject();
                if (xnode instanceof XipLeaf) {
                    warning("You can't choose the leaves !");
                    long index = ((NodeGraph) v.lastElement()).getIndex();
                    session.unSelectXipNode(index);
                    stop = true;
                }
            }
            RuleGenerator generator = new RuleGenerator(getModuleContext(), id);
            String rule = generator.constructRules(vect);
            if (rule.equals("problem")) {
                long index = ((NodeGraph) v.lastElement()).getIndex();
                if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipNode) {
                    session.unSelectXipNode(index);
                } else if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipDependency) {
                    session.unSelectXipDependency(index);
                }
            } else {
                this.setProperty("rule", rule);
                DEBUG_LOG.trace("body rule = " + rule);
                jTextArea2.setText(rule);
                jTextArea2.setToolTipText(rule);
            }
        } catch (Exception e) {
            DEBUG_LOG.trace(e);
        }
    }

    public void nodeDependency() {
        this.setProperty("panel", "nodedependency");
        DependencyNodePanel depNode = new DependencyNodePanel(getModuleContext(), id);
        this.refreshTabbedPane(depNode);
    }
}
