/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.Xip;
import com.xerox.xrce.xipui.ide.generator.CommonMethod;
import com.xerox.xrce.xipui.ide.generator.RuleGenerator;
import com.xerox.xrce.xipui.ui.graph.*;

import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;

/**
 *
 * @author csaillet
 */
public class FocusPanel extends GeneralPanel {

    /** Creates a new instance of FocusPanel
     * @param context
     * @param id 
     */
    public FocusPanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        repaint();
        setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/focus.htm");
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);

        String typeDependency = (String) this.getProperty("dependency");
        dependencyBox.setSelectedItem(typeDependency);

    }// </editor-fold>

    public void initPanel() {

        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        dependencyLabel.setEnabled(false);
        dependencyBox.setEnabled(false);

        categoryLabel.setVisible(false);
        choiceCategoryBox.setVisible(false);
        longestBox.setVisible(false);
        indexBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);

        addRuleButton.setVisible(false);
        clearTempFileButton.setVisible(false);

        String rule = (String) this.getProperty("rule");
        jTextArea2.setText(rule);
        jTextArea2.setToolTipText(rule);
    }

    public void back() {
        clear();
        DependencyNodePanel depNode = new DependencyNodePanel(getModuleContext(), id);
        depNode.nodeDependency();
    }

    public void next() {
        AddRule addR = new AddRule(getModuleContext(), id);
        addR.addRule();
    }

    public void clear() {
        Vector focus = (Vector) this.getProperty("vectFocusSelect");
        if (focus.size() != 0) {
            focus.clear();
            this.setProperty("vectFocusSelect", focus);

            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            if (session == null) {
                warning("error session null");
            } else {
                session.repaintViewer();
            }
        }
        generateRule();
    }

    public void close() {
    }

    public void indexWord() {
    }

    public void lonMatch() {
    }

    public void generateRule() {
        try {

            CommonMethod cmethod = new CommonMethod();
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            Vector v = session.getNodeGraphSelected();
            Vector selectedFeatures = new Vector();
            if (v != null) {
                Iterator ite = v.iterator();
                while (ite.hasNext()) {
                    NodeGraph ng = (NodeGraph) ite.next();
                    selectedFeatures.add(ng);
                }
            }

            Vector vecfoc = cmethod.vectNodeGraphToSelectedObject(getModuleContext(), id, selectedFeatures);

            Vector vecdependencynode = (Vector) this.getProperty("vectDependencySelect");
            // si un noeud de l arbre de chunks a ete selectionne alors deselection
            if ((v.size()) > vecdependencynode.size()) {
                warning("Wrong choice, select in the selection list !");
                long index = ((NodeGraph) v.lastElement()).getIndex();
                if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipNode) {
                    session.unSelectXipNode(index);
                } else if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipDependency) {
                    session.unSelectXipDependency(index);
                }
            } else { // si un noeud de l arbre de chunks a ete deselectionne alors selection

                long res = cmethod.verifyNodeSelection(vecfoc, vecdependencynode);
                if (res != -1) {
                    warning("Wrong choice, select in the selection list !");
                    if (session.getXipDependency(res) != null) {
                        session.selectXipDependency(res);
                    } else if (session.getXipNode(res) != null) {
                        session.selectXipNode(res);
                    }
                }
            }
            Vector vect = new Vector();
            Xip xip = getProject().getXip();
            XipResult xresult = xip.getXipResult();
            Vector vOfXipUnit = xresult.getXipUnits();
            XipUnit unit = (XipUnit) vOfXipUnit.get(0);
            XipNode root1 = unit.getRoot();
            int ghandler = getModuleContext().getProject().getGhandler();
            CommonMethod.readXipNode(root1, vect, xip, ghandler);
//            cmethod.printXipNode(vect);     
            Vector vecfocus = (Vector) this.getProperty("vectFocusSelect");
            int aritint = vecfocus.size();
            if (aritint == 0) {
                aritint = 1;
            }
            String arity = String.valueOf(aritint);
            this.setProperty("arity", arity);
            RuleGenerator generator = new RuleGenerator(getModuleContext(), id);
            String rule = generator.constructRules(vect);
            if (rule.equals("problem")) {
                long index = ((NodeGraph) v.lastElement()).getIndex();
                session.unSelectXipNode(index);
            } else {
                this.setProperty("rule", rule);
                DEBUG_LOG.trace("rule = " + rule);
                jTextArea2.setText(rule);
                jTextArea2.setToolTipText(rule);
            }
        } catch (Exception e) {
            DEBUG_LOG.trace(e);
        }
    }

    public void focusP() {
        this.setProperty("panel", "focus");
        FocusPanel focus = new FocusPanel(getModuleContext(), id);
        this.refreshTabbedPane(focus);
    }
}
