/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.Xip;
import com.xerox.xrce.xipui.ide.generator.CommonMethod;
import com.xerox.xrce.xipui.ide.generator.RuleGenerator;
import com.xerox.xrce.xipui.ui.graph.*;

import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;

/**
 *
 * @author csaillet
 */
public class IndexLastWordPanel extends GeneralPanel {

    /** Creates a new instance of IndexLastWordPanel
     * @param context
     * @param id 
     */
    public IndexLastWordPanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        repaint();
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {

        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);

        String choiceCategory = (String) this.getProperty("category");
        choiceCategoryBox.setSelectedItem(choiceCategory);
    }// </editor-fold>

    public void initPanel() {
        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        categoryLabel.setEnabled(false);
        choiceCategoryBox.setEnabled(false);
        dependencyLabel.setVisible(false);
        dependencyBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);
        addRuleButton.setVisible(false);
        clearTempFileButton.setVisible(false);
        String rule = (String) this.getProperty("rule");
        jTextArea2.setText(rule);
        jTextArea2.setToolTipText(rule);

        String longestmatch = (String) this.getProperty("longestMatch");
        if (longestmatch.equals("true")) {
            longestBox.setSelected(true);
        } else {
            longestBox.setSelected(false);
        }

        String indlastwrd = (String) this.getProperty("indexlastword");
        if (indlastwrd.equals("true")) {
            indexBox.setSelected(true);
        } else {
            indexBox.setSelected(false);
        }


        String typeRule = (String) this.getProperty("choiceRule");
        if (typeRule.equals("Sequence")) {
            indexBox.setVisible(false);
            setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/longestMatch.htm");
        } else {
            setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/indexLongestMatch.htm");
        }
    }

    public void back() {
        clear();
        RightContextPanel right = new RightContextPanel(getModuleContext(), id);
        right.rightContP();
    }

    public void next() {
        AddRule addR = new AddRule(getModuleContext(), id);
        addR.addRule();
    }

    public void clear() {
        String stglongest = (String) this.getProperty("longestMatch");
        if (stglongest.equals("true")) {
            longestBox.setSelected(false);
            this.setProperty("longestMatch", "false");
        }
        String stgindex = (String) this.getProperty("indexlastword");
        if (stgindex.equals("true")) {
            indexBox.setSelected(false);
            this.setProperty("indexlastword", "false");
        }
        generateRule();
    }

    public void close() {
    }

    public void indexWord() {
        String indlastwrd = (String) this.getProperty("indexlastword");
        if (indexBox.isSelected()) {
            indlastwrd = "true";
        } else {
            indlastwrd = "false";
        }
        this.setProperty("indexlastword", indlastwrd);
        generateRule();
    }

    public void lonMatch() {
        String lgestmatch = (String) this.getProperty("longestMatch");
        if (longestBox.isSelected()) {
            lgestmatch = "true";
        } else {
            lgestmatch = "false";
        }
        this.setProperty("longestMatch", lgestmatch);
        generateRule();
    }

    public void generateRule() {
        try {
            CommonMethod cmethod = new CommonMethod();
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            Vector v = session.getNodeGraphSelected();
            Vector selectedFeatures = new Vector();
            if (v != null) {
                Iterator ite = v.iterator();
                while (ite.hasNext()) {
                    NodeGraph ng = (NodeGraph) ite.next();
                    selectedFeatures.add(ng);
                }
            }
            Vector vecLongMatch = cmethod.vectNodeGraphToSelectedObject(getModuleContext(), id, selectedFeatures);
            int sizeTot;
            Vector body = (Vector) this.getProperty("vectBodySelect");
            Vector left = (Vector) this.getProperty("vectLeftSelect");
            Vector right = (Vector) this.getProperty("vectRightSelect");
            sizeTot = body.size() + left.size() + right.size();
            //si un noeud de l arbre de chunks a ete selectionne alors deselection
            if ((v.size()) > sizeTot) {
                long index = ((NodeGraph) v.lastElement()).getIndex();
                if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipDependency) {
                    warning("Wrong selection !");
                    session.unSelectXipDependency(index);
                } else if (((NodeGraph) v.lastElement()).getSelectedObject().getObject() instanceof XipNode) {
                    warning("Wrong selection !");
                    session.unSelectXipNode(index);
                }
            } else { // si un noeud de l arbre de chunks a ete deselectionne alors selection

                long bod = cmethod.verifyNodeSelection(vecLongMatch, body);
                if (bod != -1) {
                    warning("Wrong selection !");
                    session.selectXipNode(bod);
                }
                long lef = cmethod.verifyNodeSelection(vecLongMatch, left);
                if (lef != -1) {
                    warning("Wrong selection !");
                    session.selectXipNode(lef);
                }
                long rig = cmethod.verifyNodeSelection(vecLongMatch, right);
                if (rig != -1) {
                    warning("Wrong selection !");
                    session.selectXipNode(rig);
                }
            }
            Vector vect = new Vector();
            Xip xip = getProject().getXip();
            XipResult xresult = xip.getXipResult();
            Vector vOfXipUnit = xresult.getXipUnits();
            XipUnit unit = (XipUnit) vOfXipUnit.get(0);
            XipNode root1 = unit.getRoot();
            int ghandler = getModuleContext().getProject().getGhandler();
            CommonMethod.readXipNode(root1, vect, xip, ghandler); // vect contient les noeuds de l arbre
//            cmethod.printXipNode(vect); 

            RuleGenerator generator = new RuleGenerator(getModuleContext(), id);
            String rule = generator.constructRules(vect);
            if (rule.equals("problem")) {
                long index = ((NodeGraph) v.lastElement()).getIndex();
                session.unSelectXipNode(index);
            } else {
                DEBUG_LOG.trace("rule = " + rule);
                this.setProperty("rule", rule);
                jTextArea2.setText(rule);
                jTextArea2.setToolTipText(rule);
            }
        } catch (Exception e) {
            DEBUG_LOG.trace(e);
        }
    }

    public void indexWordP() {
        this.setProperty("panel", "indlastword");
        IndexLastWordPanel indexWord = new IndexLastWordPanel(getModuleContext(), id);
        this.refreshTabbedPane(indexWord);
    }
}
