/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ide.generator.ui;

import com.xerox.xrce.xipui.Xip;
import com.xerox.xrce.xipui.ide.generator.CommonMethod;
import com.xerox.xrce.xipui.ide.generator.RuleGenerator;
import com.xerox.xrce.xipui.ui.graph.*;
import com.xerox.xrce.xipui.modules.ModuleContext;
import java.util.*;
import com.xerox.jxip.*;

/**
 *
 * @author csaillet
 */
public class KeepTagPanel extends GeneralPanel {

    /** Creates a new instance of KeepTagPanel
     * @param context
     * @param id 
     */
    public KeepTagPanel(ModuleContext context, int id) {
        super(context, id);
        initComponents();
        repaint();
        setPageDoc("/com/xerox/xrce/xipui/ide/generator/doc/keep.htm");
        setProperty("panel_", this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        String typeRule = (String) this.getProperty("choiceRule");
        choiceRuleBox.setSelectedItem(typeRule);
    }// </editor-fold>

    public void initPanel() {
        addRuleButton.setVisible(false);
        clearTempFileButton.setVisible(false);
        ruleLabel.setEnabled(false);
        choiceRuleBox.setEnabled(false);
        dependencyLabel.setVisible(false);
        dependencyBox.setVisible(false);
        categoryLabel.setVisible(false);
        choiceCategoryBox.setVisible(false);
        longestBox.setVisible(false);
        indexBox.setVisible(false);
        outputLabel.setVisible(false);
        fileRadioButton.setVisible(false);
        bufferRadioButton.setVisible(false);
        String rule = (String) this.getProperty("rule");
        jTextArea2.setText(rule);
        jTextArea2.setToolTipText(rule);
    }

    public void next() {
        Vector veckeepSel = (Vector) this.getProperty("vectKeepSelect");
        if (veckeepSel.size() == 0) {
            warning("select keep please!");
        } else {
            LeftContextPanel left = new LeftContextPanel(getModuleContext(), id);
            left.leftContP();
        }
    }

    public void back() {
        clear();
        HeadPanel head = new HeadPanel(getModuleContext(), id);
        head.headTag();
    }

    public void clear() {
        Vector veckeepnodegraph = (Vector) this.getProperty("vectKeepNodeGraph");
        Vector veckeepselect = (Vector) this.getProperty("vectKeepSelect");
        if (veckeepselect != null) {
            veckeepselect.clear();
            veckeepnodegraph.clear();
            setProperty("vectKeepNodeGraph", veckeepnodegraph);
            setProperty("vectKeepSelect", veckeepselect);
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            if (session == null) {
                warning("error session null");
            } else {
                session.repaintViewer();
            }
        }
    }

    public void close() {
    }

    public void indexWord() {
    }

    public void lonMatch() {
    }

    public void generateRule() {
        try {
            CommonMethod cmethod = new CommonMethod();
            SessionGraph session = getModuleContext().getSessionGraph(false, id);
            Vector v = session.getNodeGraphSelected();
            Vector selectedFeatures = new Vector();
            if (v != null) {
                Iterator ite = v.iterator();
                while (ite.hasNext()) {
                    NodeGraph ng = (NodeGraph) ite.next();
                    selectedFeatures.add(ng);
                }
            }
            Vector vecKeepNodeGraph = (Vector) this.getProperty("vectKeepNodeGraph"); // vector de nodeGraph
            Vector veckeepSel = cmethod.vectNodeGraphToSelectedObject(getModuleContext(), id, vecKeepNodeGraph);
            this.setProperty("vectKeepSelect", veckeepSel);
            boolean stop = false;
            Iterator it = veckeepSel.iterator();
            while (it.hasNext() && stop == false) {
                SelectedObject selobj = (SelectedObject) it.next();
                Object xnode = selobj.getObject();
                long index = ((NodeGraph) v.lastElement()).getIndex();
                if (xnode instanceof XipDependency) {
                    warning("You can't choose the dependencies !");
                    session.unSelectXipDependency(index);
                    stop = true;
                }
            }
            Vector vect = new Vector();
            Xip xip = getProject().getXip();
            XipResult xresult = xip.getXipResult();
            Vector vOfXipUnit = xresult.getXipUnits();
            XipUnit unit = (XipUnit) vOfXipUnit.get(0);
            XipNode root1 = unit.getRoot();
            int ghandler = getModuleContext().getProject().getGhandler();
            CommonMethod.readXipNode(root1, vect, xip, ghandler);
//            cmethod.printXipNode(vect);        
            RuleGenerator generator = new RuleGenerator(getModuleContext(), id);
            String rule = generator.constructRules(vect);
            if (rule.equals("problem")) {
                long index = ((NodeGraph) vecKeepNodeGraph.lastElement()).getIndex();
                boolean st = false;
                Iterator iter = veckeepSel.iterator();
                while (iter.hasNext() && st == false) {
                    SelectedObject sel = (SelectedObject) iter.next();
                    if (index == ((XipNode) sel.getObject()).getIndex()) {
                        iter.remove();
                        st = true;
                    }
                }
                this.setProperty("vectKeepSelect", veckeepSel);
                st = false;
                Iterator itera = vecKeepNodeGraph.iterator();
                while (itera.hasNext() && st == false) {
                    NodeGraph nodeGra = (NodeGraph) itera.next();
                    if (index == ((XipNode) nodeGra.getSelectedObject().getObject()).getIndex()) {
                        itera.remove();
                        st = true;
                    }
                }
                this.setProperty("vectKeepNodeGraph", vecKeepNodeGraph);
                session.repaintViewer();
//                session.unSelectXipNode(index);
            } else {
                DEBUG_LOG.trace("body rule = " + rule);
                this.setProperty("rule", rule);
                jTextArea2.setText(rule);
                jTextArea2.setToolTipText(rule);
            }
        } catch (Exception e) {
            DEBUG_LOG.trace(e);
        }
    }

    public void keepTagP() {
        this.setProperty("panel", "keep");
        KeepTagPanel keep = new KeepTagPanel(getModuleContext(), id);
        this.refreshTabbedPane(keep);
    }
}
