#!/bin/sh
set -x
classPath=config:build/classes:../../../libExt/ws/0.2/cacao_client.jar
#classPath=config:build/classes:../../../libExt/ws/0.2/CACAO_WSclients.jar
params="-Dhttp.proxyHost=cornillon.grenoble.xrce.xerox.com -Dhttp.proxyPort=8000"
class=wsTest1.Ws_client1
java -Xmx512m $params -cp $classPath $class 
#java -Xmx512m -cp $classPath $class 
