#!/bin/sh
set -x

XIP_HOME=../../..
LD_LIBRARY_PATH=$XIP_HOME/lib/linux/sharedLib
export LD_LIBRARY_PATH

rm -f sample  errors.err output

g++ -o sample -I$XIP_HOME/include -L$LD_LIBRARY_PATH -lxip sample.cxx

./sample $XIP_HOME/grammar/english/norm/gram_norm_entit.grm input.xml

