/*
 * FMenu.java
 *
 * Created on April 25, 2008, 1:13 PM
 */

package extractionweb;

import javax.swing.JOptionPane;
import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasParentFilter;
import org.htmlparser.filters.NotFilter;
import org.htmlparser.filters.OrFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.lexer.Lexer;
import org.htmlparser.util.NodeIterator;
import org.htmlparser.util.NodeList;
import org.htmlparser.util.ParserException;

/**
 * The frame displaying the main menu of the application.
 * @author  Cédric Tarsitano
 */
public class FMenu extends javax.swing.JFrame {

    /** Creates new form FMenu */
    public FMenu() {
        initComponents();
        Main.centerFramePosition(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        URLButton = new javax.swing.JButton();
        ConfigurationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xerox Web Data Extraction v1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setForeground(java.awt.Color.red);

        Title.setFont(new java.awt.Font("Luxi Sans", 2, 24)); // NOI18N
        Title.setForeground(java.awt.Color.red);
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Xerox Web Data Extraction");

        URLButton.setBackground(new java.awt.Color(249, 248, 240));
        URLButton.setForeground(java.awt.Color.red);
        URLButton.setText("New Extraction");
        URLButton.setToolTipText("Starts a new extraction");
        URLButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        URLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLButtonActionPerformed(evt);
            }
        });

        ConfigurationButton.setBackground(new java.awt.Color(249, 248, 240));
        ConfigurationButton.setForeground(java.awt.Color.red);
        ConfigurationButton.setText("Configuration");
        ConfigurationButton.setToolTipText("Opens the configuration dialog");
        ConfigurationButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(URLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void URLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLButtonActionPerformed
    String saveLastUrlTyped = Main.lastUrlTyped;
    if(++Main.numberRequest > 1);
        Main.preInit();
    String s = JOptionPane.showInputDialog(this, "Please type the URL name you want to extract data from", Main.lastUrlTyped);
    if(null == s)
        return;
    Main.initProxy(s);
    if(null == Main.lastUrlTyped)
        Main.lastUrlTyped = saveLastUrlTyped;
    if(Main.lastUrlTyped.isEmpty())
        return;
    
    try {
        long deb = System.currentTimeMillis();
        Lexer lex;
        if(null == Main.url)
            lex = new Lexer(Main.connection.openConnection(Main.lastUrlTyped));
        else
            lex = new Lexer(Main.connection.openConnection(Main.url));

        Parser.setConnectionManager(Main.connection);
        Parser parser = new Parser(lex);
        parser.setEncoding("UTF8");

        TagNameFilter[] filters = {new TagNameFilter("TABLE"), new TagNameFilter("UL"), new TagNameFilter("OL"), new TagNameFilter("P")};

        NodeList list = new NodeList ();
        NodeFilter interFilter = new OrFilter(filters);
        //NodeFilter filter = new AndFilter(interFilter, new NotFilter(new HasParentFilter(interFilter, true)));


        for (NodeIterator e = parser.elements(); e.hasMoreNodes (); )
            e.nextNode().collectInto(list, interFilter);
            //e.nextNode().collectInto(list, filter);

        Main.parseNodeList(list);

        long fin = System.currentTimeMillis();

        System.out.println("Temps d'exécution : " + (fin - deb) + " ms.");
    }
    catch(ParserException e){
        JOptionPane.showMessageDialog(this, "An error occured while parsing the data.\nThe application will not process the extraction.\nCheck the URL you typed", "Fatal error", JOptionPane.ERROR_MESSAGE);
        return;
        //System.err.println(e.getMessage());
        //e.printStackTrace();
    }
    
    Main.toolsFrame = new FExtraParsingTools();
    Main.toolsFrame.setVisible(true);
    Main.toolsFrame.requestFocus();
}//GEN-LAST:event_URLButtonActionPerformed

private void ConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurationButtonActionPerformed
    new FConfiguration(true).setVisible(true);
}//GEN-LAST:event_ConfigurationButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfigurationButton;
    private javax.swing.JLabel Title;
    private javax.swing.JButton URLButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
