/*
 * PListTemplate.java
 *
 * Created on April 30, 2008, 11:26 AM
 */

package extractionweb;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import java.util.regex.PatternSyntaxException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.filechooser.FileSystemView;

/**
 * JPanel displaying a PARAGRAPH.
 * @author  Cédric Tarsitano
 */
public class PListTemplate extends javax.swing.JPanel {

    /**
     * The parent container of this JPanel.
     */
    private JTabbedPane mParent;
    /**
     * The index of this JPanel in the tab list in FExtraParsingTools.
     */
    private int mIndex;
    /**
     * The regular expression used to split the content of the JTextArea
     */
    private String mRegexp;
    /**
     * All the saved states of this JPanel.
     */
    private Vector <String> mStates;
    /**
     * Index of the current state in <i>mStates</i>.
     */
    private int mCurrentState;
    /**
     * Index of the last state saved in <i>mStates</i>.
     */
    private int mMaxState;
    
    /** Creates new form PListTemplate */
    public PListTemplate(JTabbedPane pane, int index, Vector <Data> list) {
        mParent = pane;
        mIndex = index;
        mRegexp = "";
        initComponents();
        mCurrentState = mMaxState = 0;
        mStates = new Vector <String> ();
        mStates.addElement(list.firstElement().getContent());
        jTextArea1.setText(mStates.elementAt(mCurrentState));
    }

    /**
     * Return the index of this JPanel in the tab list of FExtraParsingTools.
     * @return the index of this JPanel in the tab list of FExtraParsingTools. 
     */
    protected int getIndex(){
        return mIndex;
    }
    
    /**
     * Sets the index of this JPanel in the tab list of FExtraParsingTools to <i>index</i>.
     * @param index the index of this JPanel in the tab list of FExtraParsingTools.
     */
    protected void setIndex(int index){
        mIndex = index;
    }
    
    /**
     * Method that provides the "redo" function (Ctrl-Y).
     */
    protected void redo(){
        if(mCurrentState < mMaxState){
            ++mCurrentState;
            jTextArea1.setText(mStates.elementAt(mCurrentState));
        }
    }
    
    /**
     * Method that provides the "undo" function (Ctrl-Z).
     */
    protected void undo(){
        if(mCurrentState > 0){
            --mCurrentState;
            jTextArea1.setText(mStates.elementAt(mCurrentState));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeTabButton = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        splitContentButton = new javax.swing.JButton();
        saveDataButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(java.awt.Color.white);

        jPanel1.setBackground(java.awt.Color.white);

        closeTabButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_button_close.gif"))); // NOI18N
        closeTabButton.setToolTipText("Closes the current tab");
        closeTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTabButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(891, Short.MAX_VALUE)
                .addComponent(closeTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeTabButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonsPanel.setBackground(java.awt.Color.white);

        splitContentButton.setForeground(java.awt.Color.red);
        splitContentButton.setText("Split content");
        splitContentButton.setToolTipText("Splits the content of the data with a given string");
        splitContentButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        splitContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitContentButtonActionPerformed(evt);
            }
        });

        saveDataButton.setForeground(java.awt.Color.red);
        saveDataButton.setText("Save this data in a file");
        saveDataButton.setToolTipText("Saves this data in a file");
        saveDataButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(splitContentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(saveDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(splitContentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void closeTabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTabButtonActionPerformed
     if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(
                                        null,
                                        "The data contained in this tab will be lost.\nDo you really want to loose that data ?",
                                        "Warning",
                                        JOptionPane.YES_NO_OPTION,
                                        JOptionPane.WARNING_MESSAGE)){
        mParent.remove(mIndex);
        FExtraParsingTools.mTabList.removeElementAt(mIndex);
        FExtraParsingTools.refreshIndex(mIndex);
    }
}//GEN-LAST:event_closeTabButtonActionPerformed

private void splitContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitContentButtonActionPerformed
    mRegexp = JOptionPane.showInputDialog(this, "Type a regular expression to split the content");
    try{
        String[] elements = jTextArea1.getText().split(mRegexp);
        FExtraParsingTools.addTab(elements, mIndex + 1);
    }
    catch(PatternSyntaxException e){
        boolean b = System.getProperty("os.name").toLowerCase().startsWith("win") || System.getProperty("os.name").toLowerCase().startsWith("microsoft");
        String s = "";
        String sep = System.getProperty("file.separator");
        JOptionPane.showMessageDialog(this, "The regular expression you typed is not correct.\n A window will open to provide you some help.", "Error", JOptionPane.ERROR_MESSAGE);
        try{if(b)
                s = "C:\\Program Files\\Mozilla Firefox\\firefox.exe";
            else
                s = "firefox";
            Runtime.getRuntime().exec(new String[] {s, System.getProperty("java.home") + sep + "docs" + sep + "api" + sep + "java" + sep + "util" + sep + "regex" + sep + "Pattern.html"});
        }
        catch (Exception ex){
            ex.printStackTrace();
            try{
                if(!b)
                    throw new Exception("Unable to find the browser.");
                else
                    Runtime.getRuntime().exec(new String[] {"C:\\Program Files\\Internet Explorer\\iexplore.exe", System.getProperty("java.home") + sep + "docs" + sep + "api" + sep + "java" + sep + "util" + sep + "regex" + sep + "Pattern.html"});
            }
            catch (Exception exc){
                exc.printStackTrace();
                JOptionPane.showMessageDialog(this,
                                              "Unable to run the web browser. Please visit the following page :\n" + 
                                              System.getProperty("java.home") +
                                              sep + "docs" + sep + "api" + sep + "java" + sep + "util" + sep + "regex" + sep + "Pattern.html",
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
}//GEN-LAST:event_splitContentButtonActionPerformed

private void saveDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataButtonActionPerformed
    try{
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView());
        j.setDialogTitle("Select the file to export this data to");
        int res, err = 0;
        boolean ok = false;
        while(!ok){
            res = j.showSaveDialog(this);
            switch(res){
                case JFileChooser.APPROVE_OPTION :
                    File saveFile = j.getSelectedFile();
                    if(!saveFile.exists())
                        saveFile.createNewFile();
                    FileWriter fw = new FileWriter(saveFile);
                    fw.write(jTextArea1.getText());
                    fw.close();
                    ok = true;
                    break;
                case JFileChooser.CANCEL_OPTION :
                    ok = true;
                    break;
                case JFileChooser.ERROR_OPTION :
                default :
                    ++err;
                    if(err > 5)
                        throw new IOException("An error occured while selecting the output file, 5 times.");
                    JOptionPane.showMessageDialog(this, "An error occured, please select the output file again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    catch (IOException e){
        JOptionPane.showMessageDialog(this, "Please check the file you selected.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println(e.getMessage());
        e.printStackTrace();
    }
}//GEN-LAST:event_saveDataButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeTabButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton saveDataButton;
    private javax.swing.JButton splitContentButton;
    // End of variables declaration//GEN-END:variables

}
