#!/bin/sh
set -x
java -Xmx128m -classpath /opt/ParSem/users/grondeau/parSem/xip/dev/java/dist/jxip.jar:build TestJSON /opt/ParSem/users/grondeau/parSem/xip/dev/GRAMMARS/GERMAN/APPLICATIONS/EERQI/data/german_eerqi.grm in1

