#!/bin/sh
set -x
java -Xmx128m -classpath /opt/ParSem_db/users/Roux/xip/parSem/xip/dev/java/dist/jxip.jar:build Test /opt/ParSem_db/users/Roux/testsalah/gram.grm  /opt/ParSem_db/users/Roux/testsalah/input.txt

