#!/bin/sh
set -x
gram2=../../../GRAMMARS/PORTUGUESE/GRMFILES/portuguese.grm
in2=por1
in3=t1
xip=../../../xipFst/bin/linux/xip
#xip=/opt/ParSem/bin/xip-10.01-79/bin/linux/xip

$xip -grm $gram2 -tr -f -text inputs/por1
