# -*- coding: iso-8859-1 -*-

import sys
import os

accentues=["à","â","ä","é","è","ê","ë","ï","î","û","ü","ù","ç","ô","ö"]

def estlettre(i):
    if i.isalpha() or i in accentues:
        return True
    return False

francais=["sémantique", 
        "termes", 
        "reconstructeur",  
        "Echec sur la remontée des traits.",  
        "VERSION_XIP",
        "Changement par règle de deduction", 
        "Destruction par règle de deduction ", 
        " donne: ",  
        " avec ",   
        "Partie droite de la règle ne correspond pas",  
        "Un test a déjà été introduit par un 'if'", 
        "Attention, il faut une variable pour tester les traits",
        "Un point doit être présent dans le nom de fichier",
        "Réponse inconnue",
        "désambiguïsation",
        "Champ Nombre manquant ou mal écrit",
        "Champ Doublons manquant ou mal écrit",
        "négation",
        "toutmajuscule",
        "règle",
        "règles",
        "dirègles",
        "têtes",
        "marqueur",
        "préstd",
        "prérct",
        "abréviations",
        "déduction",
        "Erreur, ce champ est inconnu, on attend la valeur: marqueur",
        "On attend soit '&' soit ')' soit ';' dans cette règle",
        "On attend '(' dans cette règle",
        "abréviations",
        "La variable dans cette fonction ne correspond pas à une variable des tests associés",
        "Les regles Marqueurs doivent commencer par 'chiffre>' ex: 1> ",
        "On attend '=' dans cette règle",
        "On attend '{' dans cette règle",
        "Erreur dans la règle, ce caractère n'est pas valide:",
        "On attend '&' dans cette règle de défaut",
        "",
        "On attend ',' ou '}' dans cette règle de défaut",
        "défauts", 
        "taillemot",
        "",
        "Le symbole d'affectation '=' est attendu dans ce cas",
        "définitions",
        "Pas plus d'une valeur dans la définition",
        "Il manque une ',' ou un '=' dans cette règle",
        "zones",
        "filtrecouche",
        "découpeséquence",
        "Une seule catégorie dans la partie droite de la règle de simplification", 
        "catégories",
        " n'a pas de définition de traits",
        "plrègles",
        "La flèche est manquante ou mal écrite",
        "Il manque une paranthèse",
        "Erreur lors de la lecture d'une regle sémantique",
        "La catégorie finale ne peut être un '?'",
        "Cette couche est filtrée et ne s'applique pas:",
        "La partie droite d'une affectation doit se trouver entre {}",
        "Il manque une parenthèse fermante", 
        "Il n'y a pas d'abréviation",
        "Pas de parenthèse ici...",
        "Seule une valeur de trait peut apparaître après un '='",
        "Attention: Affectation multiple de catégories pour une entrée -> Catégorie conservé: ",
        "défaut",
        "Il n'existe aucune règle par défaut pour ce trait",
        "Erreur, il faut le coupe-choix avec l'analyse longue",
        "Impossible, une valeur a déjà été donnée pour ce trait : ", 
        "La partie droite contient des erreurs...",
        " n'a pas de définition de traits", 
        "Cette couche est déjà associé avec un filtre.",
        "Règle:",
        "Seule une balise début peut recevoir ce type de traits",
        "Trop de doublons dans cette règle,augmenter la valeur de DOUBLONS",
        "Pas de règle",
        "Ce filtre doit être associé à un numéro de couche.",
        "Operateur inconnu: ",
        "Cette regle commence avec une structure trop complexe...",
        "Attention, dans le cas d'un changement, il n'est possible de produire qu'une seule solution.",
        ":On choisit la règle ", 
        "On crée ",
        ":Échec sur les traits",
        ":On arrête les recherches",
        "Erreur:Montée des traits:",
        "Erreur:Règle de défaut inexistante. Contexte:",
        "Erreur négation: ",
        "Erreur, la dépendance doit être enclose entre '<...>'", 
        "Trop de noms différents (attribut ou valeur) : Veuillez augmenter la valeur du champ NOMBRE dans votre fichier langue.xip",
        "Erreur de la lecture de la zone",
        "affichagefonction", 
        "Attention, une seule fonction peut être marquée à la fois",
        "Seul un ';' est acceptable ici",
        "Attention, il manque une '*' ou un '+' après les parenthèses",
        "Nom de code incorrecte ou absent:", 
        "Fichier inconnu: ",
        "Pas de champ 'vocabulaires' a cet endroit",
        "finphrase",
        "trace", 
        "tracenoeud",
        "nombre",
        "doublons",
        "La variable #0 correspond au mot que l'on simplifie, on ne peut l'utiliser comme variable dans un contexte.",
        "Mot clef 'where' attendu",
        "sortie",
        "La valeur maximale de couche est comprise entre [1-1000]",
        "traits",
        "lexique",
        "vocabulaires",
        "Il manque une '['",
        "Il manque une ',' ou un ']'",
        "Ce trait n'existe pas ---> ",
        "affichage", 
        "Il manque le filtre d'affichage",
        "Il manque un ']'",
        "Il manque un '<'",
        " est une valeur inconnue pour ",
        " n'est pas une valeur possible pour ",
        "poststd",
        "postrct",
        "Si une categorie n'est pas precisee, il faut utiliser l'operateur '+='",
        "Il manque un '='",
        " est inconnu comme attribut",
        "Erreur dans une affectation: traits sont presents dans la variable gauche ou traits manquant dans la variable droite",
        "Les variables dans un test doivent être associees à des traits",
        "L'une des variables dans la partie droite ne correspond pas a une variable dans la partie gauche...",
        "lemme",
        "Seules des variables de noeuds sont acceptées ici (#1, #2..)",
        "Les definitions locales de traits s'inserent avec '<traits>'",
        "Il manque une ',' ou une '}'",
        "Il manque une ',' ou un '.' ou un ';'",
        "Il manque une ',' ou une ')'",
        "Il manque une ',' ou un ']'",
        "Il manque un ':'",
        "Une seule valeur possible pour le champ libre",
        "Une valeur doit être spécifié pour chacun des attributs au sein d'une PL-règle.",
        "Ce mot n'est pas dans la liste de vocabulaire --> ",
        "Une regle ne peut avoir de partie droite vide.",
        "erreurs.err",
        "Nombre de Catégorie trop grand",
        "Arbre",
        "[c]",
        "Erreur lors de l'application de la RCT:",
        "sur ",
        "DI-regle, couche: ",
        ":Base:",
        ":On isole:",
        ":On recherche encore:",
        "On met en attente ",
        "erreur pendant l'analyse, augmenter la valeur de DOUBLONS",
        "Erreur dans le fichier:",
        " à la ligne:",
        "Plus de mémoire.",
        "Echec dû à la PL-règle:",
        "Temps: ",
        "Caractère de début manquant ou erroné",
        "Aucune valeur trouvée pour cet attribut",
        "indentées",
        "Le(s) trait(s) suivant(s) doit(vent) être présent sur ce noeud: ", 
        "On veut associer le noeud: ",
        "Correspondance refusée entre ce noeud et cet élément de la règle",
        "Elément de la règle: ",
        "Abréviation déjà utilisée : ",
        "Abréviation inconnue : ",
        "Erreur dans la lecture de l'itération maximale pour une categorie",
        "surface",
        "Aucun test sur des valeurs de traits n'est permis ici",
        "La règle impose que ce noeud ait une valeur pour les traits suivants: ",
        "Traits non trouvés dans les abréviations:", 
        "locale",
        "La forme exacte est: ..{ ", 
        "Structure de traits non analysable : ", 
        "Séquence. Couche: ", 
        "affichagenoeud", 
        " Impossible de virer la seule interpretation: ", 
        " on vire: ", 
        " Virer au sein d'un contexte", 
        "majuscule", 
        "Simplification. Couche: ", 
        "tag", 
        "Avant Simplification.", 
        "TAG inconnu:",
        "chiffre",
        "Champ 'chiffre' absent ou mal écrit", 
        "Après Simplification.", 
        "On écrase l'entrée: ",
        "traduction",
        "Il manque un '.' ou un '['", 
        "Nombre maximum de règles atteint dans un fichier paramètre.", 
        "Le nom du chemin 'XPath' doit être suivi d'un '('", 
        "fonctions",
        ": catégorie inconnue",
        "Tous les arguments de cette fonction n'ont pu être associés avec un element dans la partie droite",
        "Extraction réussie.",
        "cacher",
        "Une catégorie optionnelle ne peut commencer une règle",
        "Il manque la taille de la matrice d'affichage (X ou Y)",
        "Cette couche doit être du type Simplification",
        "Fonction inconnue: ",
        "extraction",
        "séquence",
        "Echec extraction.",
        "Erreur... le contexte droit doit apparaitre avant le point final ",
        "Erreur... le contexte gauche ne s'applique pas",
        "Erreur... le contexte droit ne s'applique pas",
        "Erreur sur la valeur du champ libre :",
        "Erreur, Cette couche est déjà d'un autre type= ",
        "Marquage: contexte droit insuffisant",
        "Erreur, il manque une accolade fermante pour un test ",
        "Erreur, les règles d'affectation ne sont disponibles qu'au sein d'une couche",
        "Erreur, Cette couche est déjà du type: règle DI Catégorie= ",
        "Erreur, il manque l'indice de couche pour cette pl-règle",  
        "Erreur, Aucune DI-règle ne peut s'associer avec cette PL-règle dans cette couche",
        "Erreur, plusieurs catégories portent le trait last dans cette règle",
        "Erreur, plusieurs catégories portent le trait first dans cette règle",
        "Erreur, ce champ est inconnu: ",
        "codagexml",
        "Un seul attribut est permis ici...",
        "On ne peut pas générer plus d'une dépendance à la fois dans ce contexte.",
        "doubleréduction",
        "Succès lors de l'application de la règle.",
        "Echec lors de l'application du contexte ou lors d'une comparaison sur les traits.",
        "Echec, champ absent...",
        "Erreur... Il faut une variable $xxx avec le '^'.",
        "Index non valide... Regénérez l'index...",
        "Le caractère '\"' doit toujours être précédé du caractère d'échappement: \\\"",
        "Cette règle détruit toutes les lectures de: ",
        ". Elle ne peut s'appliquer.",
        "> Echec de la règle de séquence: ",
        " commençant au noeud: ",
        "> Règle de séquence: ",
        "Erreur: boucle infinie...",
        "Règle d'extraction: ",
        "Règle de dépendance: ",
        "Succès: ",
        " sur le noeud: ",
        "Règle de marquage: ",
        "Règle de reconstruction: ",
        "Application de la règle de reconstruction: ",
        "garder",
        "Ce noeud de règle de reconstruction peut occasionner la perte de mots dans l'arbre syntaxique",
        "Avertissement, cette règle a consommé trop de temps d'analyse", 
        "Erreur: cet attribut n'a jamais été déclaré.",
        "Erreur: Seule une structure de noeud (#num) peut être utilisée ici.",
        "Champ XML manquant.",
        "Erreur dans la formule XML.",
        "Méthode inconnue.",
        "Une variable pour un noeud maison ne peut pas être utilisé ailleurs dans la formule",
        "La DTD contient des erreurs",
        "Ce champ de DTD ne correspond pas à une action pour XIP",
        "Cette description de traits devrait comprendre deux éléments parmi ses valeurs possibles",
        "Cette procédure a déjà été déclarée",
        "Une procédure ne peut être le résultat d'une règle de déduction",
        "Cette procédure n'a pas de corps d'analyse",
        "'_goto' doit être unique",
        "Ce label a déjà été utilisé",
        "Espace d'analyse complet (vérifiez vos boucles d'analyse)",
        "Fichier Paramètre inconnu",
        "Trace activée",
        "Chargement de la grammaire en cours",
        "Initialisation du Parseur",
        "Les fichiers paramètres ne peuvent être chargés en mode: limité...",
        "Les expressions XIP doivent être encloses entre deux '!'",
        "Action inconnue: ",
        "Action par défaut inconnue",
        "Fonction inconnue (type possible: analyze,merge,feature ou skip)",
        "Mauvais nombre d'argument pour une transformation en traits.",
        "Paramètre manquant.\nActions possibles:\n\tskip=text|all\n\tanalyze=token|chunk|dependency\n\tfeature=string,string,(token|chunk|dependency).",
        "Paramètre inconnu pour _display",
        "Le '}' est absent dans une boucle 'WHILE'",
        "Il manque un 'WHILE' pour ce '}'",
        "Cette étiquette est inconnue",
        "On ne peut affecter une valeur précédée d'une négation",
        "Erreur dans la définition de votre lexème: Parenthèse manquante.",
        "Erreur dans la définition de votre lexème: Crochet manquant.",
        "Erreur dans la définition de votre lexème: La négation ne peut précéder une parenthèse.",
        "maxmots",
        "Le nombre maximum de mots a été atteint",
        "Caractère ',' ou ';' or '}' ou '|' manquant",
        "Il faut définir une fenêtre de catégories pour utiliser des '*' ou des '+': Cat#max",
        "La négation ne peut être appliquée qu'à une catégorie.",
        "L'opérateur '?-' doit nécessairement être en fin de règle.",
        "La virgule est mal placée dans cette expression régulière",
        "On ne peut utiliser une '*' ou un '+' a cet endroit",
        "On attend une parenthèse fermante ici: ')'", 
        "On attend un crochet fermant ici",
        "fragmenter",
        "Les variables d'expressions régulières doivent apparaître par ordre croissant 1,2...9",
        "On peut seulement avoir un signe d'affectation ('=') devant une variable XIP dans une création de noeud XML",
        "Après un '|' on ne peut avoir que: 'if', 'iftest' ou '{'",
        "Erreur dans la lecture de la règle de déduction: ",
        "Concept ontologique inconnu",
        "Ce chemin ontologique est incohérent",
        "affichageontologie",
        "Erreur: il manque l'alias au sein de l'expression XML",
        "Erreur: une string ou un vector doit toujours commencer avec un '_'",
        "Erreur: Il faut fournir un indice à cette variable de type vector.",
        "Erreur: Ce '}' n'est pas associé avec un 'for'..",
        "Erreur: Il manque une '}'...",
        "Erreur: 'iftest' mal écrit..",
        "Erreur: Accolade '}' manquante...",
        "Erreur: type inconnu...",
        "Accolade fermante sans accolade ouvrante...",
        "Une expression XMLGuide doit se terminer avec un '.' ou un ';'",
        "On doit toujours finir une procédure avec un 'return'",
        "Procédure ou instruction inconnue:",
        "Type de paramètre inconnu:",
        "Cette variable a déjà été déclarée:",
        "Les règles lexicales doivent être précédées d'un numéro de couche ici",
        "On ne peut utiliser de variables de noeuds entre crochets de structure de traits [..]",
        "Type de vecteur impossible",
        "Il manque un '.' dans cette variable struct",
        "script",
        "Le 'if' ne peut être utilisé au sein des règles de script",
        "Le 'iftest' ne peut être utilisé au sein des règles de déduction",
        "Les instructions de boucle sont interdites au sein des règles de déduction",
        "Une dépendance peut seulement être créee au sein des règles de déduction",
        "Une suite d'instruction peut seulement être utilisée au sein d'un script",
        "final",
        "On attend une ',' ou un ';' ici",
        "Attention. Cette dépendance est déjà déclarée:",
        "Champ inconnu dans un fichier grammaire:",
        "Erreur... Cette variable est déjà soit une catégorie soit une dépendance soit une instruction: ",
        "Erreur... Partie manquante dans la formule",
        "Erreur... Cette version de XIP ne peut lire des expressions XML",
        "Erreur... Opérateur manquant",
        "enchargeant",
        "initial",
        "Parenthèse manquante dans un #ifdef",
        "#endif ou #else manquant",
        "#endif manquant pour ce #else",
        "#else sans #ifdef",
        "multimots",
        "Cette expression a déjà été utilisée",
        "Erreur: Cette chaîne est trop longue",
        "Erreur: Cette règle est mal écrite et inapplicable",
        "encodageutf8lexique",
        "Interface manquante pour un appel Python",
        "Il n'y a pas de nom de fonction Python correspondant à l'interface",
        "Fonction Python inconnue",
        "Erreur, on attend un noeud fictif ici: ##CAT[traits]",
        "Erreur, cette variable ne peut être une racine. Elle ne pointe pas sur un seul noeud.",
        "ATTENTION. Ce module Python a déjà été chargé",
		"Erreur: Le code est supérieur à 255",
		"définitioncatégorie",
		"découpecatégorie",
		"Cette valeur a déjà été déclarée pour cet attribut",
		"Encodage inconnu (valeurs acceptées: 'utf8' ou 'latin')",
		"Numéro de couche manquant pour ce type de règle.",
		"Partie droite de cette règle de reconstruction manquante ou erronée",
		"Catégorie manquante devant une '{'",
		"La partie droite d'une règle de séquence ne peut contenir de sous-noeuds",
		"Expression ontologique inconnue",
		"Erreur... L'opérateur '-' ne peut être utilisé qu'en fin de séquence",
		"multilemmes",
		"Racine de l'espace de nom inconnu. Vérifiez que la première partie de votre nom d'espace soit la même que toutes vos autres définitions",
		"Instruction de format inconnu",
		"Fermeture de commentaire: '\\' manquante",
		"Le champ guesserfeature n'a pas été défini dans votre fichier de langue. Le test sur langue est impossible",
		"définitiontraits",
		"expressionfinphrase",
		"\" de fermeture manquant",
		"Il manque un '.' à la fin de cette règle multimots",
		"génération",
		"génèretraits",
		"Règle génèretraits incorrecte",
		"Flux manquant",
		"Lemme manquant",
		"Traits manquants",
		"'.' manquant à la fin de cette dépendance",
		"noeuds",
		"Seules des fonctions déclarées comme NOEUDS sont acceptées comme résultat ici",
		"Pas de formule autorisée dans ce contexte",
		"Déclaration de dépendances erronée",
		"ordre",
		"Seuls des NOEUDS sont valides dans une telle expression",
		"Seuls des NOEUDS peuvent être associés à des variables $#",
		"affichagegénération",
		"Fichier de probabilités inconnu",
		"Fichier de probabilités corrompu"]

english =["semantic",
	    "terms",
        "reshuffling",
        "Failure on feature percolation",
        "VERSION_XIP",
        "Change with deduction rule",
        "Destruction with deduction rule",
        " yield: ",
        " with ",
        "Right-side of the rule does not match",
        "A test has already been written with IF",
        "A variable is needed to test features",
        "A file name should comprise a '.'",
        "Unknown Answer: ",
        "tagging",
        "Missing Field: 'NUMBER'",
        "Missing Field: 'DOUBLE'",
        "negation",
        "alluppercase",
        "rule",
        "rules",
        "idrules",
        "heads",
        "marker",
        "predfs",
        "prefcr",
        "alias",
        "dependencyrules",
        "Error: field unknown, expected value is: 'marker'",
        "Error: Rule should contain ';' or '&' or ')'",
        "Error: Rule should contain '('",
        "alias",
        "The variable in this function does not match any variables in the test",
        "Marking Rules should start with a layer number. ex: 1> ",
        "Error: Rule should contain '='",
        "Error: This rule should contain '{'",
        "Error: this character is invalid:",
        "Error: Default Rule should contain '&'",
        "",
        "Error: Default Rule should contain ',' or '}'",
        "default",
        "wordsize",
        "",
        "'=' expected",
        "definitions",
        "One value only for this definition",
        "Error: Rule should contain ',' or '='",
        "zones",
        "layerfilter",
        "split",
        "Only one POS permitted in the right-hand side of this disambiguation rule",
        "pos",
        " Feature Definition Required",
        "lprules",
        "Missing arrow",
        "Missing '('",
        "Error while reading a semantic rule...",
        "The last category cannot be a '?'",
        "Layer Filtering discard layer:",
        "The right-side of an affectation should be enclosed between {}",
        "Missing ')'",
        "Unknown alias",
        "No '(' here",
        "Feature Value required after a '='",
        "Warning: Multiple POS Affectation for a lexicon entry -> Defined POS is: ",
        "default",
        "There is no default rule for this feature",
        "Error, Longuest Match requires a cut ('!')",
        "Error: this feature has already been instantiated",
        "Errors in the right-side of that rule",
        " does not have a feature definition",
        "This layer has already been associated with a filter.",
        "Rule:",
        "Only a starting tag can be associated with this sort of features",
        "Too many doubles in this rule, increase the value of DOUBLES",
        "No rules",
        "A layer number must be given to that layer filter.",
        "Unknown Operator: ",
        "This extraction rule starts with a too complexe structure...",
        "Only one solution can be produced at a time, when a dependency is to be modified",
        ":We select the rule ",
        "We create ",
        ":Failure on feature comparison",
        ":Stop Searching",
        "Error: Feature Percolation",
        "Error:Absent Default Rule. Contexte:",
        "Error negation: ",
        "Error, the dependency should be enclosed between '<...>'",
        "Too many name definitions: Update the NUMBER field in your language.xip file",
        "Error reading zone",
        "functiondisplay",
        "Warning, only one function can be marked at a time",
        "Only a ';' can be used in this case",
        "Error. A '*' or a '+' is missing after the parentheses",
        "Error: Incorrect Code Name :",
        "Unknown File: ",
        "no 'lexicons' field possible in this file",
        "boundaries",
        "trace",
        "tracebis",
        "number",
        "doubles",
        "Cannot utilize variable #0, affected by default to the word under disambiguation.",
        "Keyword 'where' expected",
        "indentation",
        "Layer number is in [1-1000]",
        "features",
        "lexicons",
        "vocabulary",
        "Missing '['",
        "Missing ',' or ']'",
        "Unknown feature ---> ",
        "display",
        "No display filter",
        "Missing ']'",
        "Missing '<'",
        " is an unknown value for ",
        " is not a possible value for ",
        "postdfs",
        "postfcr",
        "When no POS defined, use operator '+='",
        "Missing '='",
        " is an unknown attribute",
        "In an affectation: left variable with features or missing features for right variable",
        "variables in a test must be associated with features",
        "A variable in the right-side does not belong to the left-side.",
        "lemma",
        "Only node variables are accepted here (#1,#2 etc.)",
        "Use <features> to test on local feature definitions for a lexical entry",
        "Missing ',' or '}'",
        "Missing ',' or '.'",
        "Missing ',' or ')'",
        "Missing ',' or ']'",
        "Missing ':'",
        "Only one value is possible in the LEMMA field",
        "A value must be specified for each attribute in a LP rule.",
        "Unknown word --> ",
        "A rule cannot have an empty right-hand side.",
        "errors.err",
        "Too many POS",
        "Tree",
        "[c]",
        "Error when applying FCR:",
        "on ",
        "ID-rule. Layer: ",
        ":Base:",
        ":isolate:",
        ":searching again:",
        "Waiting ",
        "Increase the value of DOUBLES",
        "Error in file:",
        " line:",
        "No memory.",
        "LP-rule failure: ",
        "Time: ",
        "Missing starting character",
        "No value for this attribute",
        "indented",
        "The following features are absent on this node: ",
        "We try to associate this node with: ",
        "Mismatch between this node and the rule",
        "Rule element: ",
        "Alias already defined : ",
        "Unknown alias : ",
        "Error while reading the maximum iteration value for a rule element",
        "surface",
        "No test on values allowed here",
        "The rule imposes that the node has the following feature values: ",
        "Error while reading alias:",
        "locale",
        "The exact form is : ..{ ",
        "Wrong Feature Definition : ",
        "Sequence Rule. Layer: ",
        "nodedisplay",
        "  Cannot delete the only intepretation: ",
        " we delete: ",
        " Delete in a context. ",
        "uppercase",
        " Simplification. Layer: ",
        "tag",
        "Before simplification.",
        "Unknown TAG:",
        "number",
        "Missing number field",
        "After simplification.",
        "We replace the entry",
        "translation",
        "Missing '.' or '['",
        "Maximum number of rules in parameter file reached (Limited Mode)",
        "The XPath index name should be followed with '('",
        "functions",
        ": unknown POS",
        "Mismatch between the arguments of the function and its right-hand side",
        "Extraction Succeeded",
        "hidden",
        "A rule cannot start with an optional POS",
        "Missing size of the display matrix (X or Y)",
        "Error, This layer already contains Disambiguation Rules",
        "Unknown Function: ",
        "extraction",
        "sequence",
        "Extraction Failed",
        "Error... Right context to occur before the final '.' ",
        "Error... Left context does not apply",
        "Error... Right context does not apply",
        "Error on lemma field :",
        "Error, This layer already contains another type of rule= ",
        "Marking rule. Failure",
        "Error, Missing '}' ",
        "Error, Affectation rules are only available within a layer",
        "Error, This layer already contains ID Rules= ",
        "Error, Missing layer number",
        "Error, Mismatch LP-rules (no ID-rules to link to)",
        "Error, Too many POS bear the feature: 'last' in this rule",
        "Error, Too many POS bear the feature: 'first' in this rule",
        "Error, Unkown field: ",
        "xmlcoding",
        "Only one attribute at a time in this structure...",
        "Only one dependency can be generated at a time in this contexte...",
        "doublereduction",
        "Rule has applied",
        "Failure on context application or on features comparison",  
        "Error, missing field...",
        "A variable $xxx is expected with the '^' operator.",
        "Non valid index... Please rebuild the index.",
        "The '\"' caracter should always be preceded by the escape caracter: \\\" ",
        "This rule deletes all readings from:",
        ". It cannot apply.",
        "> Sequence Rule Failure:",
        " starting at node: ",
        "> Sequence Rule:",
        "Error, infinite loop...",
        "Extraction Rule: ",
        "Dependency Rule: ",
        "Success: ",
        " on node:",
        "Marking Rule: ",
        "Reshuffling Rule: ",
        "Application of Reshuffling rule: ",
        "keep",
        "This node in the reshuffling rule may cause the lost of words in the chunk tree",
        "Warning: Above sentence took too much time...",
        "Error: This attribute has never been declared before.",
        "Error: Only a node (#num) can be used here.",
        "Missing XML field.",
        "Error in XML formula.",
        "Unknown method.",
        "A handmade node cannot be assigned to a variable already used in the formula",
        "The DTD is not well-formed",
        "This field does not correspond to DTD XIP action",
        "This feature item should have at two possible values in its description field",
        "This procedure has already been declared",
        "A procedure cannot be the result of a deduction rule",
        "This procedure does not have any body",
        "'_goto' must be unique",
        "Label already used",
        "Parsing Space exhausted (number of loops to large, check your grammar)",
        "Parameter file does not exist",
        "Trace activated",
        "Grammar Loading",
        "PARSER INITIALISATION",
        "Cannot read parameter files in mode: limited...",
        "XIP expression should be enclosed between '!'",
        "Unknown action: ",
        "Unknown Default action",
        "Unknown function (possible types include: analyze,merge,feature or skip)",
        "Wrong number of argument for a feature transformation",
        "Missing parameter.\nPossible actions:\n\tskip=text|all\n\tanalyze=token|chunk|dependency\n\tfeature=string,string,(token|chunk|dependency).",
        "Unknown parameter for _display",
        "Missing '}' in a 'WHILE' loop",
        "The 'WHILE' is missing for that '}'",
        "This label does not exist",
        "You cannot affect a valeur preceded with a negation",
        "Error in your vocabulary definition: Missing parenthesis.",
        "Error in your vocabulary definition: Missing square bracket.",
        "Error in your vocabulary definition: The negation cannot precede a parenthesis).",
        "maxword",
        "The maximum number of words has been reached",
        "Missing ',' or ';' or '}' or '|' in this rule",
        "To use the '*' or the '+', you must first define the maximum category window: Cat#max",        
        "Negation can only applies to categories.",
        "The '?-' operator must be at the end of a rule.",
        "The comma is wrongly used in this regular expression",
        "A '*' or a '+' cannot apply here",
        "Mismatched parenthesis ()",
        "Mismatched square bracket []",
        "fragment",
        "Regular expressions variables should occur in increasing order 1,2,3..",
        "Only the instantiation sign ('=') is accepted in front of a XIP variable in a XML node creation...",
        "After a '|' we expect: 'if', 'iftest', 'compute' or '{'",
        "Error while compiling the dependency rule: ",
        "Unknown ontology concept",
        "This ontological path is incoherent",
        "ontologydisplay",
        "Error: The alias name is missing in this XML instruction.",
        "Error: A string or a vector should always start with a '_'.",
        "Error: An indice is needed for that vector.",
        "Error: This '}' does not match any 'for'.",
        "Error: A '}' is missing for a 'for' statement.",
        "Error: Wrong 'iftest' statement.",
        "Error: Mismatched '{...}'.",
        "Error: Unknown variable type...",
        "Mismatched curly bracket {}",
        "An XMLGuide expression should end with a '.' or a ';'",
        "A return should always terminate a procedure",
        "Unknown procedure or instruction:",
        "Unknown parameter type:",
        "This variable has already been declared:",
        "The lexicon rules should be preceded by a layer number in this file",
        "A node variable cannot be used within feature brackets [...]",
        "Impossible vector type",
        "A '.' is missing in this struct variable",
        "script",
        "The 'if' cannot be used within the script rules",
        "The 'iftest' cannot be used within the dependency rules",
        "No 'loop' instruction in a dependency rule section",
        "A dependency can only be created within the dependency rule section",
        "An instruction set '{...}' can only be used within a script section",
        "final",
        "Expecting a ',' or a ';'",
        "Warning. This dependency has already been declared:",
        "Unknown GRAMMAR file field:",
        "Error... This variable is already a category or a dependency or an instruction: ",
        "Error... Missing part in the formula",
        "Error... This version of XIP cannot handle XML expressions",
        "Error... Missing operator in the test",
        "loading",
        "initial",
        "Missing parenthesis in a #ifdef statement",
        "Missing #endif or #else for a #ifdef statement",
        "Missing #endif for a #else statement",
        "#else without #ifdef",
        "multiwords",
        "Error: This expression has already been declared",
        "Error: This string is too long",
        "Error: This rule is not correct. Check the commas and the parentheses",
        "utf8lexiconencoding",
        "Missing interface in a Python call",
        "There is no python function corresponding to the interface",
        "Unknown Python function",
        "Error. A fictive node is expected here:: ##CAT[features]",
        "Error. This variable cannot be used as a root. It does not point to a unique node.",
        "Warning... This Python module has already been loaded...",
		"Error: Code is superior to 255",
		"categorydefinition",
		"categorysplit",
		"Value already declared for that attribute",
		"Unknown charset: valid values are 'latin' or 'utf8'",
		"Missing layer number for this sort of rule.",
		"Missing or wrong right-side of reshuffling rule.",
		"Missing category definition in front of a '{'",
		"The right-side of a sequence rule cannot contain sub-nodes",
		"Unknown ontological expression",
		"Error... The '-' operator can only be used at the end of a sequence",
		"multilemmas",
		"Unknown space name root. Check that the first string of your space name matches the other spacename definitions.",
		"Format Instruction Unknown",
		"Missing closing comment character: '\\'",
		"The field 'guesserfeature' is missing in your language file. Language testing is impossible",
		"featuredefinition",
		"regularboundaries",
		"Missing closing quote: \"",
		"A '.' is missing in this multiword expression",
		"generation",
		"generatefeatures",
		"Incorrect GenerateFeatures rule",
		"Missing stream",
		"Missing Lemma",
		"Missing Features",
		"Missing '.' at the end of this dependency",
		"nodes",
		"Only NODES functions are valid as a result here",
		"Formulas are invalid in this context",
		"Wrong dependency declaration",
		"order",
		"Only NODES are valid in this section",
		"Only NODES can be associated to a $# variable",
		"generationdisplay",
		"Wrong probability file",
		"Probability File is corrupted"]

dicos={}

a=iter(english)
for f in francais:
    s=a.next()
    test=True
    for i in s:
        if not estlettre(i):
            test=False
            break
    if test:        
        if s==f:
            continue
        dicos[f+":"]=s+":"

def charge():
    chemin=sys.path[0]
    a=os.listdir(chemin)
    try:
        os.stat(chemin+"\\CONVERSION")
    except:
        os.makedirs(chemin+"\\CONVERSION")

    modifs=open(chemin+"\\CONVERSION\\modifsInXip.txt","w")
    modifs.write(sys.version+"\n\n\n")
    for c in a:
        if c[-4:]==".xip":
            if not "~" in c:
                nom=chemin+"\\"+c                
                f=open(nom,"r")
                premier=True
                ln=0
                codes=""
                for s in f:
                    xcd=s.lower().strip()
                    test=False
                    if ":" in xcd:
                        test=True
                        cd=""
                        for i in xcd:
                            cd+=i
                            if i==":":
                                break
                            if not estlettre(i):
                                test=False
                                break


                        if cd=="":
                            test=False
                        if test:
                            test=False
                            if cd=="language:":
                                codes+="language: english\n"
                                if premier:
                                    print "in:"+nom
                                    modifs.write("In: "+nom+"\n")
                                premier=False
                                print ln,s,cd
                                modifs.write("Line:"+str(ln)+" = "+s+" --> "+cd+"\n")
                                test=True
                                
                            if cd in dicos:                                
                                res=cd
                                ps=xcd.find(cd)
                                if ps==0:
                                    cd=dicos[cd]+xcd[ps+len(cd):]                                
                                    codes+=cd
                                    if premier:
                                        print "in:"+nom
                                        modifs.write("In: "+nom+"\n")
                                    premier=False
                                    print "Chgt:",ln,res,cd
                                    modifs.write("Line:"+str(ln)+" = "+res+" --> "+cd+"\n")
                                    test=True

                    if not test:
                        codes+=s
                    elif codes[-1]!="\n":
                        codes+="\n"
                    ln+=1
                if not premier:
                    print
                    modifs.write("\n")
                f.close()
                nouveau=chemin+"\\CONVERSION\\"+c
                f=open(nouveau,"w")
                f.write(codes)
                f.close()
                
    modifs.close()
charge()

