#!/bin/sh
set -x
rm -rf Test.class

GRAM=../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm

JAR=../../dist/jxip.jar

javac -classpath $JAR Test.java 
java  -classpath $JAR:. Test $GRAM  "Peter is happy"
rm -rf Test.class
