/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 *
 * Copyright (C) 2010 - 2011 Xerox Corporation, XRCE-Grenoble, All Rights Reserved.
 * This file can only be used with the KiF library, 
 * it should not and cannot be used otherwise.
 */
/* --- CONTENTS ---
   Project    : KiF
   Version    : 1.00
   filename   : kifinit.h
   Date       : 09/09/2010
   Purpose    : Implementation of the KiF language: External methods
   Programmer : Claude ROUX
   Reviewer   : 
*/

#ifndef kifinit_h
#define kifinit_h


KifElement* PrePredicateWeight(KifElement* pattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreRange(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePushFirst(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePushLast(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePopFirst(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePopLast(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFirst(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGetc(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGetSTD(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGetERR(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreComplement(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTrace(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMode(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreXipReplaceRgx(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreXipRegex(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreParse(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLisp(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTags(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreReplaceRgx(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRegex(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSplitRegex(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreQuery(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreStore(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePredicateDump(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRetractAll(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRemove(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFind(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCount(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTest(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRFind(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSplit(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSplitKeepEmptyStrings(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreTokenize(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSTokenize(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreHash(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGCSize(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertVector(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEvaluationMap(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetSeeds(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWaitOn(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreAddToWaitOn(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreTrigger(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreConvertMap(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertString(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreJSon(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertFloat(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertInteger(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertLong(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertBoolean(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMethods(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreInfos(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreUTF8ToLatin(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLatinToUTF8(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreToDOS(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreDOSToUTF8(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreLeft(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreBytePosition(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCharacterPosition(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRight(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMid(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsLower(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsUpper(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsDigit(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsAlpha(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsPunctuation(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLower(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreUpper(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsEmoji(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreEmoji(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreTrim(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreTrimright(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreTrimleft(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreName(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreType(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreResetTime(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetDate(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDate(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreYear(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDay(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWeekDay(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreYearDay(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreHour(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMinute(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSecond(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMonth(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCatch(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRaise(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTypeIs(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreBase(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrime(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrimefactors(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreMath(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePadding(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFill(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOrd(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreBytes(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFlatten(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreHTMLEncoding(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreXMLEncoding(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreMin(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreMax(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreChr(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreKill(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCast(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWait(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWaiting(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreVersion(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreExit(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEmojis(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrint(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintLN(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintJoin(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintJoinErr(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintJoinLN(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintJoinErrLN(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrintFlush(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePrinterr(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePrinterrLN(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSeek(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTell(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWrite(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWriteLN(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWriteBin(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRead(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreReadOneLine(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreClose(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOpenReadfile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetSignature(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGetSignature(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEndOfFile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOpenWritefile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOpenSearchfile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFlushFile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreInsert(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreJoin(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreUnique(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSort(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreItems(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePermute(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreShuffle(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSortInt(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSortFloat(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSortLong(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSortString(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSum(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreValues(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreKeys(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreInkey(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreProduct(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreApply(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreClear(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeRemove(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeIsolate(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreExtract(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeNext(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreePrevious(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeParent(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeChild(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeLast(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeDepth(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeAddChild(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeAddNext(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTreeAddPrevious(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSize(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreReverse(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRemovefirst(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRemovelast(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreUnGet(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFormat(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreRadian(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreEven(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreOdd(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreDegree(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PrePause(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreEval(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOpenSession(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCloseSession(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCompile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRun(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRunEnd(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRunStart(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRunAsThread(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSleep(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreBegin(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEnd(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreNend(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIteratorKey(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreValue(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreValueType(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreValueTypeIs(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreReplace(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreNext(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLoad(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLoadDouble(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetcodefeat(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDump(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreAddword(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLook(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* Prespotfinalstate(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLoadCompact(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetmodel(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePush(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePop(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreMerge(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLast(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSet(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGet(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PostEval(KifCode* kifcode,string& code,KifElement* contextualpattern,KifDomain* dom);
KifElement* PreThreadId(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreParentThreadId(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreOpenAppendfile(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreRandom(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFractionSwitch(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDenominator(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreNumerator(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEuclidian(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreFractionSimplify(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreNumeratorDenominator(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreConvertFraction(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWaitOnFalse(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreWaitOnJoin(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLock(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLockRec(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreUnlock(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePartOf(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEvaluateMeta(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PrePredicate(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreErrorOnKey(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGarbageSurvey(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTestUTF8(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreParentThreadId(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreId(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDuplicate(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGCSize(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreExposed(KifElement* pattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreGetInfoStackOnId(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTheStack(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreTheVariables(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCurrentFilename(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreCloseKifCodeDebugFunction(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetKifCodeDebugFunction(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetDebugFunction(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetDebugData(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDebugClose(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreLevenshtein(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsConsonants(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreIsVowels(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreDeaccentuate(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreEditDistance(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreResize(KifElement* contextualpattern,KifDomain* dom,KifCallFunction* callfunc,int idthread);
KifElement* PreSetpath(KifElement* pattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreNGRAMS(KifElement* pattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreCompilergx(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreLookup(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreLookdown(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreBuild(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);
KifElement* PreProcess(KifElement* contextualpattern, KifDomain* dom, KifCallFunction* callfunc, int idthread);

#endif

