#!/bin/sh
set -x
rm -rf build
mkdir build
jar1=../libExt/commons-io-2.0.1.jar
jar2=../../dist/jxip.jar
jar3=/opt/ParSem/bin/xip-10.01-79/java/jxip.jar
jars=$jar1:$jar2
gramEn=../GRAMMARS/ENGLISH/GRMFILES/GRAM_NORM/gram_norm_entit.grm
gramPor=../GRAMMARS/PORTUGUESE/GRMFILES/portuguese.grm

javac -cp $jars -d build CallBack1.java

#java -Xmx512m -cp $jars:build testCallBack1.CallBack1 $gramEn en1 any
#java -Xmx512m -cp $jars:build testCallBack1.CallBack1 $gramPor por1 utf8
#java -Xmx512m -cp $jars:build testCallBack1.CallBack1 ../GRAMMARS/ITALIAN/CELI_090313/italian.grm ita1 utf8
java -Xmx512m -cp $jars:build testCallBack1.CallBack1 ../GRAMMARS/GERMAN/BASIC/german.grm ger1 utf8
#java -Xmx512m -cp $jars:build testCallBack1.CallBack1 
