if ("`uname`" == "Linux") then
	# Lines until ------- MUST be at the beginning of all .cshrc
	# It allows 2 things:
	# 1- set the environment variables for a clean use of cns-gnome/linux
	# 2- csh need the variables to be initialized, so we set it to the empty string to avoid an error

	if ($?G_PATH) then
		# We use cns-gnome
		setenv PATH $G_PATH
	else if ($?PATH) then
		# We don't use gnome but PATH has anyway be set (for instance,a textual(mingetty)i login 
		#In this case, don't change anything
	else
		#No path : not good : let's presume we're on Linux
		set path=(/usr/kerberos/bin /usr/local/bin /bin /usr/bin /usr/X11R6/bin)
	endif

	#add by GR:
	set path=(/usr/kerberos/bin /usr/local/bin /bin /usr/bin /usr/X11R6/bin)

	if ($?G_LD_LIBRARY_PATH) then
		# We use cns-gnome
		setenv LD_LIBRARY_PATH ${G_LD_LIBRARY_PATH}
	else if($?LD_LIBRARY_PATH) then
		# We don't use gnome but LD_LIBRARY_PATH has anyway be set 
		#So, in this case, we don't change it
	else
		#No LD_LIBRARY_PATH...soit...(pronounce "swat")
		setenv LD_LIBRARY_PATH ""
	endif
endif

#--------------------------------------
# @(#)cshrc 1.11 89/11/29 SMI
umask 022
setenv OPENWINHOME /usr/openwin

# no beep
set nobeep

set path=($path  /opt/gnu/bin )

setenv LD_LIBRARY_PATH /usr/local/lib:/usr/lib:/lib:/opt/Linux/lib:/opt/Misc/lib:/opt/gnu/lib:.

if ( $?prompt ) then
        set history=164
	alias ls ls -F
        if $?tcsh then
                set prompt='%m{%h} '
        endif
endif

# Printers
setenv PRINTER studio
setenv LPDEST studio
#---------------- CVS ---------------
setenv CVSROOT /opt/ParSem/cvs_repo
#setenv CVSROOT /opt/DS/CVSMASTER
#---------------- tomcat ---------------
#setenv CATALINA_HOME /home/grondeau/tools/apache/jakarta-tomcat-5.0.25
setenv CATALINA_HOME /opt/ParSem/tools/tomcat/6.0.20
setenv TOMCAT_HOME  $CATALINA_HOME 
set path=( $CATALINA_HOME/bin $path )
#---------------- ant ---------------
# with fedora FC5 it's mandatory to use /usr/bin/ant otherwise there is an error:
# No supported regular expression matcher found
setenv ANT_HOME /opt/ParSem/tools/ant/1.8.2
set path=($ANT_HOME/bin $path)
#---------------- gradle ---------------
setenv GRADLE_HOME /opt/ParSem/tools/gradle/1.0-milestone-8a
set path=($GRADLE_HOME/bin $path)
#---------------- apache ---------------
setenv HTTPD_HOME /home/grondeau/tools/apache/httpd-2.0.49
set path=( $HTTPD_HOME/bin $path )
#---------------- AXIS2 ---------------
#setenv AXIS2_HOME /opt/ParSem/tools/axis2/1.4.1
#set path=( $AXIS2_HOME/bin $path )
#---------------- MAVEN ---------------
setenv M2_HOME /opt/ParSem/tools/maven/apache-maven-2.2.1
set path=( $M2_HOME/bin $path )
#---------------- jax-ws ---------------
setenv JAXWS_HOME /opt/ParSem/tools/jax-ws/2.2
set path=( $JAXWS_HOME/bin $path )
#---------------- groovy ---------------
setenv GROOVY_HOME /opt/ParSem/tools/groovy/1.8.0
set path=( $GROOVY_HOME/bin $path )
#---------------- SUNOS ---------------
if ("`uname`" == "SunOS") then
	setenv CLASSPATH .
	if ("`hostname`" == "lautaret" ) then
		setenv JAVA_HOME /opt/java/jdk1.6.0
		set path=($JAVA_HOME/bin $path)
		# pour le compilo g++
		set path=(/opt/STools/bin $path)
		# pour ar 
		set path=(/usr/xpg4/bin $path)
	endif
	if ("`hostname`" == "oisans" ) then
		setenv DISPLAY avoriaz:0.0
		setenv JAVA_HOME /usr/jdk/instances/jdk1.6.0
		set path=($JAVA_HOME/bin $path)
		# pour le compilo g++: keep this order
		set path=($path /usr/sfw/bin)
		set path=($path /opt/STools/bin)
		# pour ar 
		set path=(/usr/xpg4/bin $path)
	endif
endif
#---------------- LINUX ---------------
if ("`uname`" == "Linux") then
	# pour Xming: si pb de demarrage Xming il faut l'arreter et le redemarer: start->all programa->xming
	if ("`hostname -s`" == "cochette" | "`hostname -s`" == "mlir-5"  ) then
		setenv DISPLAY avoriaz:0.0
	else
		setenv DISPLAY avoriaz:0.0
	endif
	# pour le compilo g++
	set path=(/opt/STools/bin $path)
	# xip
	set path=($path /opt/ParSem/bin/linux)
	#if ("`hostname -s`" == "cochette" | "`hostname -s`" == "mlir-5" ) then
	if ("$MACHTYPE" == "x86_64") then
		#echo "64 bits"
		setenv JAVA_HOME /opt/ParSem/tools/jdk/1.6.0_25-64bits
		set path=($JAVA_HOME/bin $path)
		setenv CLASSPATH .
		# 64bits
		setenv PYTHONHOME /opt/STools/python/2.6.4-x86_64
		set path=($PYTHONHOME/bin $path)
		setenv LD_LIBRARY_PATH $PYTHONHOME/lib:$PYTHONHOME/lib/mysql:$LD_LIBRARY_PATH
	else
		#no beep
		xset -b
		#echo "32 bits"
		setenv JAVA_HOME /opt/ParSem/tools/jdk/1.6.0_25
		set path=($JAVA_HOME/bin $path)
		setenv CLASSPATH .
		setenv PYTHONHOME /opt/STools/python/2.6.4-i386
		set path=($PYTHONHOME/bin $path)
		setenv LD_LIBRARY_PATH /opt/ParSem/users/grondeau/parSem/python/2.6/linux/lib:$PYTHONHOME/lib:$PYTHONHOME/lib/mysql:$LD_LIBRARY_PATH
	endif
	setenv JAVAFX_HOME /opt/ParSem/tools/javafx/1.3.1
        set path=($JAVAFX_HOME/bin $path)
endif
#--------------- general ------------
# priority to the script dir (in case of conflict name or version)
set path=(~/scripts $path)
set path=(. $path)
setenv http_proxy http://cornillon.grenoble.xrce.xerox.com:8000
limit coredumpsize 0
setenv PARSEM /opt/ParSem/users/grondeau/parSem
alias par cd $PARSEM
alias com cd $PARSEM/common
alias dev cd $PARSEM/xip/dev
alias del cd $PARSEM/xip/delivery
alias gram cd $PARSEM/xip/dev/GRAMMARS
alias jav cd $PARSEM/xip/dev/java
alias xui cd $PARSEM/xip/dev/xipui
alias web cd $PARSEM/xip/dev/web/server
alias ws  cd $PARSEM/xip/dev/webService/xipWS
alias ala  cd $PARSEM/aladin
alias esp  cd $PARSEM/esp
alias eer  cd $PARSEM/eerqi
