#!/bin/sh
set -x
rm -f main.o main

g++ -fno-common -c -isysroot /Developer/SDKs/MacOSX10.4u.sdk -arch ppc -arch i386 main.cpp
gcc -v "-Wl -syslibroot /Developer/SDKs/MacOSX10.4u.sdk -arch ppc "  -o main main.o -lstdc++
main
file main
gcc -v "-Wl -syslibroot /Developer/SDKs/MacOSX10.4u.sdk -arch i386"  -o main main.o -lm -lpthread -lz -lgcc_s.10.4 -lstdc++

main

file main*
