#! /bin/tcsh


#set GRMLOC=/home/chagege/parSem/xip/dev/GRAMMARS/ENGLISH/GRMFILES/GRAM_TEMP
set GRMLOC=/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/EERQI/data

/opt/ParSem/bin/linux/xips -depfeatval -grm $GRMLOC/gram_temp.grm -tr -f  $1 $2 $3 $4 $5 $6 $7 
#/opt/ParSem/bin/linux/xip -grm $GRMLOC/gram_temp.grm -tr -f -depfeatval $1 $2 $3 $4 $5 $6 $7 | sed -e 's/:+//g'

#/home/roux/XIPCVS/parSem/xip/dev/bin/linux/xips -grm $GRMLOC/gram_temp.grm -tr -f $1 $2 $3 $4 $5 $6 $7





