#!/bin/sh
set -x

#XIP_HOME=../../..
XIP_HOME=../..
LD_LIBRARY_PATH=$XIP_HOME/lib/linux/sharedLib
export LD_LIBRARY_PATH

rm -f sample  errors.err output

g++ -o sample -I$XIP_HOME/include -L$LD_LIBRARY_PATH -lxip sample.cxx

#./sample $XIP_HOME/grammar/english/entity/gram_gen_entit.grm input.xml
./sample $XIP_HOME/GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm input.txt

