#!/bin/sh
#set -x

GRM=../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
#GRM=../../../GRAMMARS/GERMAN/GRMFILES/german.grm
JAR=../../../java/dist/jxip.jar
rm -rf Test.class
javac -classpath $JAR Test.java 
java -mx512m -classpath $JAR:. Test $GRM "Peter is happy" 
rm -rf Test.class errors.err

