#!/bin/sh
set -x

XIP_HOME=../..

UNAME=`uname`
if [ "$UNAME" = "Linux" ]; then
	CC=g++
	LIB=xip
	LD_LIBRARY_PATH=$XIP_HOME/lib/linux/sharedLib
else
	CC=g++
	LIB=xip
	LD_LIBRARY_PATH=$XIP_HOME/lib/solaris/sharedLib
fi
export LD_LIBRARY_PATH

rm -f sample  errors.err output

$CC -o sample -I$XIP_HOME/include -L$LD_LIBRARY_PATH -l$LIB sample.cxx

./sample $XIP_HOME/GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm input.txt

