#!/bin/sh
set -x
rm -rf build
mkdir build

# 32 bits arch
LIBROOT=../../lib/linux
DEFINES="-DXMLINPUT -DXIPSTLUSE -DXIPSTLAPI -DUNIX -DXIPSTDC"

# 64 bits arch
#LIBROOT=../../lib/linux64
#DEFINES=-"DXMLINPUT -DXIPSTLUSE -DXIPSTLAPI -DUNIX -DXIPSTDC -DNOUNSIGNEDINT -DARCH64"

g++ -c -o build/derivation.o -O3 $DEFINES -I../../include derivation.cxx
g++ -c -o build/main.o -O3 $DEFINES -I../../include main.cxx
g++ -mt -o build/derivation build/derivation.o build/main.o -L$LIBROOT/staticLib -lxip -lm -lpthread -lz -lstdc++

build/derivation