#!/bin/sh
set -x
rm -rf build
mkdir build
jar=../../../dist/jxip.jar
grm=../../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
javac -cp $jar  -d build src/Test.java
java -Xmx512m -cp $jar:build Test ../corpus/input 
