#define yy_create_buffer propio__create_buffer
#define yy_delete_buffer propio__delete_buffer
#define yy_scan_buffer propio__scan_buffer
#define yy_scan_string propio__scan_string
#define yy_scan_bytes propio__scan_bytes
#define yy_flex_debug propio__flex_debug
#define yy_init_buffer propio__init_buffer
#define yy_flush_buffer propio__flush_buffer
#define yy_load_buffer_state propio__load_buffer_state
#define yy_switch_to_buffer propio__switch_to_buffer
#define yyin propio_in
#define yyleng propio_leng
#define yylex propio_lex
#define yyout propio_out
#define yyrestart propio_restart
#define yytext propio_text
#define yywrap propio_wrap

#line 20 "prop-io.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /opt/ParSem/cvs_repo/parSem/fst/dev/src/fst/prop-io.lex.c,v 1.4 2005/03/04 15:45:25 grondeau Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 21
#define YY_END_OF_BUFFER 22
static yyconst short int yy_acclist[154] =
    {   0,
       22,   13,   19,   21,16396,    1,   21,    2,   21,    2,
       21,    3,   13,   19,   21,16396,   21,   19,   21,   21,
       15,   21,   16,   21,   13,   19,   21,16396,   21,   21,
       13,   19,   21,   17,   21,   18,   21,   13,   19,   21,
    16396,   13,   19,16396,   19,   13,16396,    4,   19,    1,
        2,    3,   13,   19,16396,    3,    3,    3,   19,    3,
       13,16396,    3,    4,   19,    6,    6,    5,    6,   13,
       19,16396,   13,16396,   10,   10,   10,    8,   13,16396,
       11,   11,   13,16396,   13,   19,   14,   19,   13,   19,
       13,   19,16396,    4,   13,16396,    4, 8204,   19,   19,

        3,    4,    3,   13,16396,    3,    3,    4,    3, 8204,
       19,    3,   19,    3,    3,   19,   10,   10,    7,   11,
       11,   13,16396,   13,   19,16396, 8204, 8204,   19,   19,
     8204,    3, 8204,    3,    3, 8204,   19,    3,   19,    3,
     8204,   10,   10,    9,   13,   19,16396, 8204,    3, 8204,
        3,   20,   20
    } ;

static yyconst short int yy_accept[104] =
    {   0,
        1,    1,    1,    2,    6,    8,   10,   12,   17,   18,
       20,   21,   23,   25,   29,   30,   31,   34,   36,   38,
       42,   45,   45,   46,   48,   50,   51,   52,   56,   57,
       58,   60,   63,   66,   67,   68,   69,   70,   73,   75,
       76,   77,   78,   79,   81,   82,   82,   82,   85,   87,
       88,   89,   90,   91,   94,   95,   97,   97,   98,  100,
      101,  101,  103,  106,  107,  109,  112,  114,  115,  117,
      117,  118,  119,  120,  120,  121,  124,  124,  127,  128,
      128,  130,  131,  132,  134,  135,  138,  140,  142,  143,
      144,  145,  145,  148,  149,  149,  151,  152,  152,  152,

      153,  154,  154
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    8,    9,
       10,    1,   11,   12,   13,    1,    1,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
        1,   18,    1,    1,    1,    1,    1,   19,   20,    1,
        1,    1,    1,    1,    1,    1,    1,   21,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       22,    1,   22,    1,    1,    1,    1,    1,    1,   23,

       20,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   24,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[25] =
    {   0,
        1,    2,    3,    4,    1,    5,    6,    7,    8,    8,
        1,    8,    1,    9,   10,    1,    8,    8,    1,    1,
        1,    8,    1,    1
    } ;

static yyconst short int yy_base[125] =
    {   0,
        0,    0,  143,   23,  140,  866,  125,   38,   60,   67,
       89,  866,  866,   96,  866,  111,  134,  866,  866,   12,
      106,   26,  148,  169,   87,  107,  866,    0,   27,    0,
      184,  208,  232,  254,  866,  866,    0,   91,  260,  273,
      866,    0,  866,  280,  866,    0,    0,    0,  303,  866,
      317,   88,    0,   13,  866,    0,  336,   92,   93,  357,
      112,    0,    0,   66,  379,  403,  427,    0,  451,  473,
      478,    0,  866,  484,  102,    0,  491,  123,  126,  512,
      131,  533,  137,  555,   61,    0,  579,    0,  601,    0,
      866,  607,  614,  154,  627,    0,   30,  647,  654,  866,

       28,  866,  669,  679,  689,  699,  709,  719,  729,  737,
      743,  751,  758,  768,  777,  787,  796,  806,  816,  824,
      831,  840,  848,  855
    } ;

static yyconst short int yy_def[125] =
    {   0,
      102,    1,  102,  103,  102,  102,  102,  102,  104,  102,
      105,  102,  102,  103,  102,  102,  106,  102,  102,   14,
       14,  102,  103,  107,  108,  102,  102,    8,  109,  109,
      102,  102,  102,  104,  102,  102,  110,   14,  107,  111,
      102,  112,  102,   39,  102,  113,   16,   39,  106,  102,
      106,  114,  115,   14,  102,   39,  107,  116,  117,  108,
      116,  109,   32,  118,  102,  102,  102,   65,  102,  104,
      119,  120,  102,  111,  102,   39,  114,   14,  121,  116,
      117,  117,  121,  102,  122,   66,  102,   84,  119,  123,
      102,  119,   14,  121,  121,   84,  124,  119,  102,  102,

      102,    0,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102
    } ;

static yyconst short int yy_nxt[891] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   14,   16,   17,    4,   18,   19,    4,   20,
        4,   15,    4,    4,   22,   24,   24,   22,   29,   23,
      100,   78,   54,   94,   54,   78,   24,   25,   28,   29,
       55,   62,   28,   30,   31,   30,   30,   30,   28,   30,
       28,   32,   33,   28,   30,   30,   28,   28,   28,   30,
       28,   28,   35,   35,   79,   36,   37,   38,   39,   56,
       39,   38,   39,   38,   39,   39,   39,   38,   39,   38,
       39,   38,   38,   39,   39,   38,   38,   38,   39,   38,
       38,   41,   41,   60,   77,   42,   43,   22,   80,   82,

       61,   53,   23,   22,   24,   61,   83,   53,   26,   44,
       25,   39,   45,   45,   45,   39,   55,   46,   80,   24,
       45,   39,   45,   39,   47,   61,   39,   27,   45,   39,
       39,   39,   95,   39,   48,   50,   24,   82,   93,   83,
       51,   26,  102,   95,   83,   53,  102,   52,   53,   56,
       83,   56,  102,   56,  102,   56,   56,   56,  102,   56,
       95,   56,  102,  102,   56,   56,  102,   83,  102,   56,
       22,  102,  102,  102,  102,   57,  102,  102,  102,  102,
      102,  102,   24,   58,   28,   63,  102,   56,   28,   63,
       28,   63,   63,   63,   28,   63,   28,   63,   28,   28,

       63,   63,   28,   28,   28,   63,   28,   28,   63,   29,
      102,  102,   63,   30,   64,   30,   30,   30,   63,   30,
       63,   32,   65,   63,   30,   30,   63,   63,   63,   30,
       63,   63,   66,   30,  102,  102,   66,   30,   67,   30,
       30,   30,   66,   30,   66,   68,   69,   66,   30,   30,
       66,   66,   66,   30,   66,   66,   35,   35,  102,   36,
       37,   22,  102,  102,  102,  102,   57,  102,  102,  102,
      102,  102,  102,   24,   58,   41,   41,  102,  102,   72,
       73,   75,   45,   45,  102,  102,  102,  102,  102,   45,
      102,   45,  102,   44,  102,  102,  102,   45,  102,  102,

      102,  102,  102,   76,  102,  102,  102,  102,  102,   51,
      102,  102,  102,  102,  102,  102,   52,   53,   52,  102,
       52,  102,   52,  102,   52,   52,   52,  102,   52,  102,
       52,  102,  102,   52,   52,  102,  102,  102,   52,   56,
      102,   56,  102,   56,   56,   56,  102,   56,  102,  102,
      102,  102,   56,   56,  102,  102,  102,   56,   79,  102,
       79,  102,   79,  102,   79,   79,   79,  102,   79,  102,
       79,  102,  102,   79,   79,  102,  102,  102,   79,   84,
       30,  102,  102,   84,   30,   85,   30,   30,   30,   84,
       30,   84,   68,   30,   84,   30,   30,   84,   84,   84,

       30,   84,   84,   86,   30,  102,  102,   86,   30,   87,
       30,   30,   30,   86,   30,   86,   88,   69,   86,   30,
       30,   86,   86,   86,   30,   86,   86,   66,   84,  102,
       79,   66,   84,   66,   84,   84,   84,   66,   84,   66,
       84,   66,   66,   84,   84,   66,   66,   66,   84,   66,
       66,   69,   30,  102,  102,   69,   30,   69,   30,   30,
       30,   69,   30,   69,   30,   69,   69,   30,   30,   69,
       69,   69,   30,   69,   69,   35,   35,  102,   36,   37,
       41,   41,  102,  102,   90,   91,   41,   41,  102,  102,
       72,   73,   52,  102,   52,  102,   52,  102,   52,   52,

       52,  102,   52,  102,  102,   52,  102,   52,   52,  102,
      102,  102,   52,   79,  102,   79,  102,   79,  102,   79,
       79,   79,  102,   79,  102,  102,   79,  102,   79,   79,
      102,  102,  102,   79,   94,  102,   94,  102,   94,  102,
       94,   94,   94,  102,   94,  102,   94,  102,  102,   94,
       94,  102,  102,  102,   94,   96,   30,  102,  102,   96,
       30,   97,   30,   30,   30,   96,   30,   96,   88,   30,
       96,   30,   30,   96,   96,   96,   30,   96,   96,   86,
       96,  102,   94,   86,   96,   86,   96,   96,   96,   86,
       96,   86,   96,   86,   86,   96,   96,   86,   86,   86,

       96,   86,   86,   41,   41,  102,  102,   90,   91,   41,
       41,  102,  102,   90,   91,   99,  100,  101,  102,  102,
      102,  102,  102,  102,  102,  102,  102,   24,   94,  102,
       94,  102,   94,  102,   94,   94,   94,  102,   94,  102,
      102,   94,  102,   94,   94,  102,  102,  102,   94,   41,
       41,  102,  102,   90,   91,   99,  100,  101,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,   55,   21,
       21,  102,  102,  102,   21,  102,  102,   21,   21,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   49,

       49,  102,  102,  102,   49,  102,  102,   49,   49,   56,
       56,  102,  102,  102,   56,  102,  102,   56,   56,   59,
      102,  102,  102,  102,   59,  102,  102,   59,   59,   30,
       30,  102,  102,   30,   30,   30,   30,   30,   30,   70,
       70,   70,   70,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   74,   74,  102,   74,   74,   39,   39,
      102,   39,   39,   39,   39,   39,   39,   39,   52,  102,
      102,  102,  102,   52,  102,  102,   52,   53,  102,  102,
      102,  102,   53,  102,  102,  102,   53,   79,  102,  102,
      102,  102,   79,  102,  102,   79,   81,  102,  102,  102,

      102,   81,  102,  102,   81,   81,   63,   63,  102,   63,
       63,   63,   63,   63,   63,   63,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   92,   92,  102,   92,
       92,   94,  102,  102,  102,  102,   94,  102,  102,   94,
       84,   84,  102,   84,   84,   84,   84,   84,   84,   84,
       98,   98,  102,   98,   98,   96,   96,  102,   96,   96,
       96,   96,   96,   96,   96,    3,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102
    } ;

static yyconst short int yy_chk[891] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,   20,   54,   22,   29,    4,
      101,   54,   20,   97,   20,   54,    4,    4,    8,    8,
       22,   29,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    9,    9,   85,    9,    9,   10,   10,   64,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   11,   11,   25,   52,   11,   11,   14,   58,   59,

       25,   25,   14,   75,   38,   58,   59,   59,   26,   14,
       14,   16,   16,   16,   16,   16,   75,   16,   61,   21,
       16,   16,   16,   16,   16,   61,   16,    7,   16,   16,
       16,   16,   79,   16,   16,   17,   78,   81,   78,   79,
       17,    5,    3,   83,   81,   81,    0,   17,   17,   23,
       83,   23,    0,   23,    0,   23,   23,   23,    0,   23,
       94,   23,    0,    0,   23,   23,    0,   94,    0,   23,
       24,    0,    0,    0,    0,   24,    0,    0,    0,    0,
        0,    0,   24,   24,   31,   31,    0,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   32,   32,
        0,    0,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   33,   33,    0,    0,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   34,   34,    0,   34,
       34,   39,    0,    0,    0,    0,   39,    0,    0,    0,
        0,    0,    0,   39,   39,   40,   40,    0,    0,   40,
       40,   44,   44,   44,    0,    0,    0,    0,    0,   44,
        0,   44,    0,   44,    0,    0,    0,   44,    0,    0,

        0,    0,    0,   44,   49,    0,    0,    0,    0,   49,
        0,    0,    0,    0,    0,    0,   49,   49,   51,    0,
       51,    0,   51,    0,   51,   51,   51,    0,   51,    0,
       51,    0,    0,   51,   51,    0,    0,    0,   51,   57,
        0,   57,    0,   57,   57,   57,    0,   57,    0,    0,
        0,    0,   57,   57,    0,    0,    0,   57,   60,    0,
       60,    0,   60,    0,   60,   60,   60,    0,   60,    0,
       60,    0,    0,   60,   60,    0,    0,    0,   60,   65,
       65,    0,    0,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   66,   66,    0,    0,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   67,   67,    0,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   69,   69,    0,    0,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   70,   70,    0,   70,   70,
       71,   71,    0,    0,   71,   71,   74,   74,    0,    0,
       74,   74,   77,    0,   77,    0,   77,    0,   77,   77,

       77,    0,   77,    0,    0,   77,    0,   77,   77,    0,
        0,    0,   77,   80,    0,   80,    0,   80,    0,   80,
       80,   80,    0,   80,    0,    0,   80,    0,   80,   80,
        0,    0,    0,   80,   82,    0,   82,    0,   82,    0,
       82,   82,   82,    0,   82,    0,   82,    0,    0,   82,
       82,    0,    0,    0,   82,   84,   84,    0,    0,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   87,
       87,    0,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   87,   87,   89,   89,    0,    0,   89,   89,   92,
       92,    0,    0,   92,   92,   93,   93,   93,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   93,   95,    0,
       95,    0,   95,    0,   95,   95,   95,    0,   95,    0,
        0,   95,    0,   95,   95,    0,    0,    0,   95,   98,
       98,    0,    0,   98,   98,   99,   99,   99,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   99,  103,
      103,    0,    0,    0,  103,    0,    0,  103,  103,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  106,

      106,    0,    0,    0,  106,    0,    0,  106,  106,  107,
      107,    0,    0,    0,  107,    0,    0,  107,  107,  108,
        0,    0,    0,    0,  108,    0,    0,  108,  108,  109,
      109,    0,    0,  109,  109,  109,  109,  109,  109,  110,
      110,  110,  110,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  112,  112,    0,  112,  112,  113,  113,
        0,  113,  113,  113,  113,  113,  113,  113,  114,    0,
        0,    0,    0,  114,    0,    0,  114,  115,    0,    0,
        0,    0,  115,    0,    0,    0,  115,  116,    0,    0,
        0,    0,  116,    0,    0,  116,  117,    0,    0,    0,

        0,  117,    0,    0,  117,  117,  118,  118,    0,  118,
      118,  118,  118,  118,  118,  118,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  120,  120,    0,  120,
      120,  121,    0,    0,    0,    0,  121,    0,    0,  121,
      122,  122,    0,  122,  122,  122,  122,  122,  122,  122,
      123,  123,    0,  123,  123,  124,  124,    0,  124,  124,
      124,  124,  124,  124,  124,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "prop-io.l"
#define INITIAL 0
/* $Id: prop-io.lex.c,v 1.4 2005/03/04 15:45:25 grondeau Exp $ */
/* Copyright (c) 1994 by the Xerox Corporation.  All rights reserved */
/***********************************************************
*
*			    PROP-IO.L
*
*	LEX grammar for Properties file
*
*			Hervé Poirier
*			Feb 4, 1994
*
***********************************************************/
#line 15 "prop-io.l"
/*	The following characters are special.  They can be used
	as ordinary characters only immediately after the ESCAPE
	character '%', '0', '?', and '=' are special only when they
	are not adjacent to a letter, a non-special symbol, or a digit.
	%		ESCAPE character
	'		CHARACTER delimiter (single quote)
	"		STRING delimiter (double quote)
	!		COMMENT character
	[]	        OBJECT delimiters
	()	        LIST delimiters
	<>		ARRAY delimiters
	:		SYMBOL

	The syntactic rules for forming symbols are:

	Examples:

		Specification		Symbol name

*/
/* unput is not used, don't generate the code it */
#define YY_NO_UNPUT

#ifdef __GNUC__
static char rcsid[] __attribute__ ((unused)) = "$Id: prop-io.lex.c,v 1.4 2005/03/04 15:45:25 grondeau Exp $";
#endif

/* #include "fst/flex-modif.h"     Not needed anymore 1999-08-09 LK */
#include <stdlib.h>
#include <string.h>
#ifdef MAC_OS
#include <unix.h>	/* Maybe necessary for WIN32, too.  LK 98-09-25 */
#endif

#if defined _WINDOWS
#include <windows.h>
#include <io.h>
#ifndef __GNUC__
#include <direct.h>
#endif
#endif

#include "fst/types.h"
#include "fst/prop-io.h"
#include "fst/prop-io.tab.h"
#include "fst/utf8_fatstr_util.h"
#include "fst/fst-types.h"

#ifndef SLIM_FST /* Only a minimal set of functions is
	            compiled when SLIM_FST is defined. */ 

#define yylval propio_lval

void rem_escapes(char *str);

/* delimiters */
#line 716 "prop-io.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 103 "prop-io.l"


#line 870 "prop-io.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 103 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 866 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 105 "prop-io.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 106 "prop-io.l"
{ increment_prop_io_line_count() ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 108 "prop-io.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "prop-io.l"
{
    rem_escapes((char *)yytext);
    yytext[strlen((char *)yytext) - 1] = '\0';                  /* remove last : */    
    yylval.fat_string = FST_thin_to_fat((char *)yytext);
    return(PR_PROPNAME);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 117 "prop-io.l"
{
    rem_escapes((char *)&yytext[1]);
    yytext[strlen((char *)yytext) - 1] = '\0';                  /* remove last " */
    yylval.fat_string = FST_thin_to_fat((char *)&yytext[1]);
    return(STRING);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "prop-io.l"
{ return(STRING_ERROR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 126 "prop-io.l"
{
    CHARSET(&yylval.fat_character) = '\0';
    if (yyleng > 3)
        CHARNUM(&yylval.fat_character) = yytext[2];
    else
	CHARNUM(&yylval.fat_character) = yytext[1];
    return(CHARACTER);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 135 "prop-io.l"
{ return(CHARACTER_ERROR); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "prop-io.l"
{ return(CHARACTER_ERROR); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "prop-io.l"
{ return(CHARACTER_ERROR); }
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 139 "prop-io.l"
{
    yylval.integer = strtol((char *)yytext, NULL, 10);
    return(INTEGER);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 144 "prop-io.l"
{
    rem_escapes((char *)yytext);
    yylval.fat_string = FST_thin_to_fat((char *)yytext);
    return(SYMBOL_PACKAGE);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 150 "prop-io.l"
{
    rem_escapes((char *)yytext);
    if (yytext[0] == ':')
	yylval.fat_string = FST_thin_to_fat((char *)&yytext[1]);
    else
	yylval.fat_string = FST_thin_to_fat((char *)yytext);
    return(SYMBOL_NAME);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 159 "prop-io.l"
return(SYMBOL_ERROR);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "prop-io.l"
return(PR_START_LIST);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "prop-io.l"
return(PR_END_LIST);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 163 "prop-io.l"
return(PR_START_ARRAY);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "prop-io.l"
return(PR_END_ARRAY);
	YY_BREAK
/* {sep_item}		return(PR_SEQ_SEPARATOR); */
case 19:
YY_RULE_SETUP
#line 167 "prop-io.l"
return(UNKNOWN_ERROR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "prop-io.l"
{ increment_prop_io_line_count(); return(QUIT);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 170 "prop-io.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1114 "prop-io.lex.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 103 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 103 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 102);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 170 "prop-io.l"


/* This is not needed anymore: The macro yyterminate do it for us.

<<EOF>>		{
    yyin = NULL;
    YY_NEW_FILE;
    yyterminate();
}
*/

void rem_escapes(char *str)
{
    char *p,*q;

    for (p = q = str; *q != '\0'; q++, p++)
    {
        if (*q == '%')
            q++;
        if (p != q)
            *p = *q;
    }
    *p = '\0';                  /* mark en of text */
}

int yywrap(void)
{
  return(1);
}

#endif /* SLIM_FST */
