#!/bin/sh
set -x
rm -rf res res.html errors.err

USER=`whoami`
if [ "$USER" = "grondeau" ]; then
	XIP_HOME=$HOME/projets/parSem/xip/dev
else
	XIP_HOME=$HOME/parSem/xip/dev
fi

ROOT_XIP=$XIP_HOME/GRAMMARS
export ROOT_XIP

GRM=$ROOT_XIP/ENGLISH/APPLICATIONS/COREF/coref.grm

#XIP=$XIP_HOME/bin/linux/xips
XIP=/opt/ParSem/bin/linux/xips

PYTHONHOME=/opt/STools/python/2.4.1
export PYTHONHOME

$XIP -grm $GRM -tr -f -text sampletext $1 $2 $3 $4 $5 $6 $7 $8 $9 

diff res.html res.html.ref
#rm -rf res res.html
