#!/bin/sh
#set -x

get_proc=`ps -e -o pid= -o command= | grep tomcat | grep -v grep`
echo $get_proc > get_it
get_pid=`gawk -F" " '{ print $1 }' get_it`
rm -f get_it
echo $get_pid
if [ -n "$get_pid" ]
then
	kill -9 $get_pid
fi

rm -rf $CATALINA_HOME/logs/*
rm -rf $CATALINA_HOME/webapps/advancedUI 
rm -rf $CATALINA_HOME/webapps/advancedUI.war 
rm -rf $CATALINA_HOME/work/Catalina/localhost/advancedUI
rm -rf /cacao/h2/h2DB/*
