#!/bin/sh
set -x
dbdir=/cacao/h2/h2DB
mkdir -p $dbdir
cd $dbdir
param1="-Dhttp.proxyHost=cornillon.grenoble.xrce.xerox.com -Dhttp.proxyPort=8000"
param2="-webAllowOthers"

echo ------------------------------------
echo  http://makalu.xrce.xerox.com:8082
echo ------------------------------------
/cacao/tools/jdk/1.6.0_13/bin/java $param1 -Xmx512m -classpath /cacao/h2/h2.jar org.h2.tools.Server $param2 -baseDir  $dbdir




