#!/bin/sh

startt: start tomcat on makalu
stopt: stop tomcat on makalu

echo "http://makalu.xrce.xerox.com:8080/mamager/html"

echo "attention http://makalu:8080 ... ne marche pas parceque makalu n'est pas sur grenoble.xrce.xerox.com"
