#!/bin/sh
set -x
JAR=../../dist/jxip.jar
GRM=../../../GRAMMARS/ENGLISH/APPLICATIONS/SCOOP/GRMFILES/scoop-complete.grm
rm -f XipParser.class
javac -classpath $JAR XipParser.java
java -classpath $JAR:. XipParser $GRM

