#!/bin/sh
set -x
#usage:
#	echo "this is a test" | ./xipparse
#	./xipparse -text fileNameToParse


rm -f errors.err

XIP_HOME=`pwd`/../..

ROOT_XIP=$XIP_HOME/GRAMMARS
export ROOT_XIP

GRMFILE=`pwd`/gram_gen_entit_dev.grm

$XIP_HOME/bin/linux/xip -grm $GRMFILE -tr -f -t $1 $2 $3 $4 $5
