#!/bin/sh
set -x
LD_LIBRARY_PATH=/home/grondeau/projets/parSem/xip/dev/lib/linux/sharedLib
export LD_LIBRARY_PATH

ROOT_XIP=/home/grondeau/projets/parSem/xip/dev/GRAMMARS
export ROOT_XIP

bin/linux/sampleD /home/grondeau/projets/parSem/xip/dev/GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm

