#!/bin/sh
set -x

LD_LIBRARY_PATH=$LIBDIR;export LD_LIBRARY_PATH
ROOT_XIP=`pwd`/../../GRAMMARS;export ROOT_XIP
/home/grondeau/tools/valgrind/3.0.1/bin/valgrind --tool=memcheck --leak-check=yes -v --num-callers=10 --log-file=res ./test
