/* soapKIF_USCOREBinding0Service.h
   Generated by gSOAP 2.8.22 from kifwebservice.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapKIF_USCOREBinding0Service_H
#define soapKIF_USCOREBinding0Service_H
#include "soapH.h"
class SOAP_CMAC KIF_USCOREBinding0Service
{ public:
	struct soap *soap;
	bool soap_own;
	/// Variables globally declared in kifwebservice.h (non-static)
	/// Constructor
	KIF_USCOREBinding0Service();
	/// Constructor to use/share an engine state
	KIF_USCOREBinding0Service(struct soap*);
	/// Constructor with engine input+output mode control
	KIF_USCOREBinding0Service(soap_mode iomode);
	/// Constructor with engine input and output mode control
	KIF_USCOREBinding0Service(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~KIF_USCOREBinding0Service();
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void KIF_USCOREBinding0Service_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	KIF_USCOREBinding0Service *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error or SOAP_OK)
	virtual	int dispatch();
	virtual	int dispatch(struct soap *soap);

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///
	void* data;

	/// Web service operation 'callKIF0' (returns error code or SOAP_OK)
	virtual	int callKIF0(std::string name, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'callKIF1' (returns error code or SOAP_OK)
	virtual	int callKIF1(std::string name, std::string param1, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'callKIF2' (returns error code or SOAP_OK)
	virtual	int callKIF2(std::string name, std::string param1, std::string param2, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'callKIF3' (returns error code or SOAP_OK)
	virtual	int callKIF3(std::string name, std::string param1, std::string param2, std::string param3, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'callKIF4' (returns error code or SOAP_OK)
	virtual	int callKIF4(std::string name, std::string param1, std::string param2, std::string param3, std::string param4, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'callKIF5' (returns error code or SOAP_OK)
	virtual	int callKIF5(std::string name, std::string param1, std::string param2, std::string param3, std::string param4, std::string param5, std::string &returned) SOAP_PURE_VIRTUAL;

	/// Web service operation 'MethodsResponse' (returns error code or SOAP_OK)
	virtual	int MethodsResponse(std::string &returned) SOAP_PURE_VIRTUAL;
};
#endif
