#!/bin/sh
set -x

g++ -I../../include -L../../lib/linux -lSTLnhxXipL test.cxx
LD_LIBRARY_PATH=../../lib/linux;export LD_LIBRARY_PATH
GRMDIR=`pwd`/../../grammar/english/entity;export GRMDIR
./a.out
rm -f a.out
