#!/bin/sh
set -x

#LD_LIBRARY_PATH=/home/grondeau/projets/parSem/xip/dev/java/build/lib/jXip/linux/sharedLib
LD_LIBRARY_PATH=/tmp/grondeau/1165568079105
export LD_LIBRARY_PATH

g++ -c -O3 -I/home/grondeau/projets/parSem/xip/dev/include sample.cxx

gcc -o sampleD sample.o -L$LD_LIBRARY_PATH -Wl,-Bdynamic -ljXip -Wl,-Bdynamic -lm -lpthread -lz -lstdc++

ROOT_XIP=/home/grondeau/projets/parSem/xip/dev/GRAMMARS
export ROOT_XIP

sampleD /home/grondeau/projets/parSem/xip/dev/GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
