#!/bin/sh
#set -x

find . -name *.*~ -print -exec rm -r {} \; >/dev/null  2>/dev/null
find . -name *.class -print -exec rm -r {} \; >/dev/null  2>/dev/null
find . -name core* -print -exec rm -r {} \; >/dev/null  2>/dev/null
