#!/bin/sh
set -x
cp /opt/ParSem/Corpora/ENGLISH/REUTERSEXPANDED/news-00001.txt input
cp /opt/ParSem/Corpora/ENGLISH/REUTERSEXPANDED/news-00002.txt input
cp /opt/ParSem/Corpora/ENGLISH/REUTERSEXPANDED/news-00003.txt input
