#!/bin/sh
set -x
XIP_HOME=`pwd`/../../..
GRM=$ROOT_XIP/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
JAR=$XIP_HOME/GRAMMARS/ENGLISH/APPLICATIONS/JCOREF/dist/coref.jar
rm -rf Test.class
javac -classpath $JAR Test.java 
CORPUS=/opt/ParSem/Corpora/ENGLISH/REUTERSEXPANDED
#CORPUS=input
java -Xmx256m -classpath $JAR:. Test $GRM $CORPUS
rm -rf Test.class errors.err
