#!/bin/sh
set -x
LD_LIBRARY_PATH=../../../../xipFst/lib/linux/sharedLib
export LD_LIBRARY_PATH
rm -f test
g++ -o test -I../../../../include -L$LD_LIBRARY_PATH -lxip test.cxx
./test ../../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm ../corpus/input
