/* soapKIF_USCOREBindingService.cpp
   Generated by gSOAP 2.8.22 from kifwebservice.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapKIF_USCOREBindingService.h"

KIF_USCOREBindingService::KIF_USCOREBindingService()
{	this->soap = soap_new();
	this->soap_own = true;
	KIF_USCOREBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

KIF_USCOREBindingService::KIF_USCOREBindingService(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	KIF_USCOREBindingService_init(_soap->imode, _soap->omode);
}

KIF_USCOREBindingService::KIF_USCOREBindingService(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	KIF_USCOREBindingService_init(iomode, iomode);
}

KIF_USCOREBindingService::KIF_USCOREBindingService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	KIF_USCOREBindingService_init(imode, omode);
}

KIF_USCOREBindingService::~KIF_USCOREBindingService()
{	if (this->soap_own)
		soap_free(this->soap);
}

void KIF_USCOREBindingService::KIF_USCOREBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"kifws", "urn:kifservice", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void KIF_USCOREBindingService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void KIF_USCOREBindingService::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	KIF_USCOREBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
KIF_USCOREBindingService *KIF_USCOREBindingService::copy()
{	KIF_USCOREBindingService *dup = SOAP_NEW_COPY(KIF_USCOREBindingService);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

int KIF_USCOREBindingService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int KIF_USCOREBindingService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int KIF_USCOREBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int KIF_USCOREBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int KIF_USCOREBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int KIF_USCOREBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void KIF_USCOREBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void KIF_USCOREBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *KIF_USCOREBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void KIF_USCOREBindingService::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *KIF_USCOREBindingService::soap_header()
{	return this->soap->header;
}

int KIF_USCOREBindingService::run(int port)
{	if (soap_valid_socket(this->soap->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				break;
			soap_destroy(this->soap);
			soap_end(this->soap);
		}
	}
	return this->soap->error;
}

SOAP_SOCKET KIF_USCOREBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET KIF_USCOREBindingService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int KIF_USCOREBindingService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif

int KIF_USCOREBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->soap->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->soap->max_keep_alive > 0 && !--k)
			this->soap->keep_alive = 0;
#endif

		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if (dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_kifws__callKIF(struct soap*, KIF_USCOREBindingService*);

int KIF_USCOREBindingService::dispatch()
{	return dispatch(this->soap);
}

int KIF_USCOREBindingService::dispatch(struct soap* soap)
{	KIF_USCOREBindingService_init(soap->imode, soap->omode);
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "kifws:callKIF"))
		return serve_kifws__callKIF(soap, this);
	return soap->error = SOAP_NO_METHOD;
}

static int serve_kifws__callKIF(struct soap *soap, KIF_USCOREBindingService *service)
{	struct kifws__callKIF soap_tmp_kifws__callKIF;
	struct kifws__callKIFResponse soap_tmp_kifws__callKIFResponse;
	soap_default_kifws__callKIFResponse(soap, &soap_tmp_kifws__callKIFResponse);
	soap_default_kifws__callKIF(soap, &soap_tmp_kifws__callKIF);
	if (!soap_get_kifws__callKIF(soap, &soap_tmp_kifws__callKIF, "kifws:callKIF", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->callKIF(soap_tmp_kifws__callKIF.name, soap_tmp_kifws__callKIF.param1, soap_tmp_kifws__callKIF.param2, soap_tmp_kifws__callKIF.param3, soap_tmp_kifws__callKIFResponse.returned);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_kifws__callKIFResponse(soap, &soap_tmp_kifws__callKIFResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_kifws__callKIFResponse(soap, &soap_tmp_kifws__callKIFResponse, "kifws:callKIFResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_kifws__callKIFResponse(soap, &soap_tmp_kifws__callKIFResponse, "kifws:callKIFResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
