#!/bin/sh
set -x

cd xip-ge
rm -f text.html text.out
cat SAMPLES/text.txt | txtparse > text.out
perl color.pl text.out text.html
diff text.out SAMPLES/text.out
diff text.html SAMPLES/text.html
rm -f text.html text.out
