#!/bin/sh
set -x
rm -rf doc doxy.log log
# copy scr and include in code directory
rm -rf code
mkdir code
cp ../../src/*.cxx ../../include/*.h code
../../../tools/doxygen/1.3.5/linux/bin/doxygen config.cfg 1> doxy.log 2>&1 
