#!/bin/sh
set -x

XIP_HOME=../..
#GRM=$XIP_HOME/GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
GRM=toyGram/english.grm
#JAR=build/jxip.jar
JAR=$XIP_HOME/java/dist/jxip.jar

rm -f hs_err_pid*.*
javac -classpath $JAR -d build Test.java 
java  -classpath $JAR:build Test $GRM

