#!/bin/sh
set -x
#usage:
#	echo "this is a test" | ./xipparse
#	./xipparse -text fileNameToParse

XIP_HOME=`pwd`/..

ROOT_XIP=$XIP_HOME/GRAMMARS
export ROOT_XIP
GRMFILE=$ROOT_XIP/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm

$XIP_HOME/bin/linux/xip -grm $GRMFILE -tr -f $1 $2 $3 $4 $5
