#!/bin/sh
set -x

XIP_HOME=../../..
LD_LIBRARY_PATH=$XIP_HOME/lib/linux/sharedLib
export LD_LIBRARY_PATH

rm -f sample  errors.err output*.xml input-*.xml

g++ -o sample -I$XIP_HOME/include -L$LD_LIBRARY_PATH -lxip sample.cxx

./sample 

