#!/bin/csh

setenv ROOT_XIP /home/ait/parSem/xip/dev/GRAMMARS
setenv XIPBINDIR /opt/ParSem/bin/linux
#setenv XIPCOREFDIR $ROOT_XIP/ENGLISH/APPLICATIONS/DATOPS


$XIPBINDIR/xips -grm $ROOT_XIP/ENGLISH/APPLICATIONS/COREF/coref.grm -tr -f $1 $2 $3 $4 $5 $6 $7 $8 $9
