#!/bin/sh
#set -x
for file in `ls win32/*.bat`
do
	echo $file
	diff -wb $file /home/grondeau/scripts/win32
done
for file in `ls win64/*.bat`
do
	echo $file
	diff -wb $file /home/grondeau/scripts/win64
done
