//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xipwin.rc
//
#define IDEdit                          3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_XIPWINTYPE                  129
#define IDR_RESTYPE                     130
#define IDD_OPTIONSXIP                  133
#define IDD_createrule                  135
#define IDD_Limit                       136
#define IDD_seerule                     137
#define IDD_inforule                    138
#define IDD_parameterfile               139
#define IDD_search                      140
#define IDD_featuretree                 141
#define IDD_variableaccess              142
#define IDD_grammarfiletree             143
#define IDD_Filenameinput               144
#define IDD_ListeVariables              149
#define IDD_help_script                 150
#define IDD_DIALOG1                     151
#define IDC_whoami                      1000
#define IDC_lemme                       1001
#define IDC_surface                     1002
#define IDC_sentence                    1003
#define IDC_full                        1004
#define IDC_cetegories                  1005
#define IDC_reduit                      1006
#define IDC_offset                      1007
#define IDC_wordnumb                    1008
#define IDC_utf8                        1009
#define IDC_dependency                  1010
#define IDC_maths                       1011
#define IDC_byname                      1012
#define IDC_bynode                      1013
#define IDC_bycreation                  1014
#define IDC_displayfeaturevaluedep      1015
#define IDC_tree                        1016
#define IDC_treephrase                  1017
#define IDC_notree                      1018
#define IDC_resultat                    1023
#define IDC_valueselection              1024
#define IDC_EDIT1                       1026
#define IDC_dependencies                1027
#define IDC_EDIT2                       1027
#define IDC_focus                       1028
#define IDC_EDIT3                       1028
#define IDC_editonfocus                 1029
#define IDC_EDIT4                       1029
#define IDC_EDIT5                       1030
#define IDC_depname                     1035
#define IDC_depsize                     1036
#define IDC_clearfocus                  1037
#define IDC_catdep                      1038
#define IDC_BUTTON3                     1039
#define IDC_clearselection              1039
#define IDC_rulenumber                  1040
#define IDC_limitlast                   1041
#define IDC_breakpoint                  1042
#define IDC_BUTTONRUN                   1043
#define IDC_runbar                      1045
#define IDC_WINDOWREADING               1047
#define IDC_addone                      1048
#define IDC_minusone                    1049
#define IDC_nextsentence                1050
#define IDC_previoussentence            1051
#define IDC_layers                      1053
#define IDC_info                        1054
#define IDC_ruletext                    1055
#define IDC_viewbloc                    1056
#define IDC_select                      1057
#define IDC_editrule                    1058
#define IDC_remove_comment              1059
#define IDC_addrule                     1060
#define IDC_dependencyrule              1062
#define IDC_sequencerule                1063
#define IDC_taggingrule                 1064
#define IDC_toggledepcat                1065
#define IDC_leftcontext                 1070
#define IDC_rightcontext                1071
#define IDC_selectrule                  1072
#define IDC_headtagging                 1073
#define IDC_idrule                      1074
#define IDC_ruletype                    1075
#define IDC_LISTSUBPART                 1076
#define IDC_addinfile                   1077
#define IDC_numsentence                 1079
#define IDC_renumber                    1080
#define IDC_STATICDEP                   1082
#define IDC_catdeplist                  1083
#define IDC_rule                        1084
#define IDC_load                        1086
#define IDC_listfilename                1089
#define IDC_clearrulegeneration         1090
#define IDC_find                        1091
#define IDC_findnext                    1092
#define IDC_searchstring                1093
#define IDC_featuredisplay              1094
#define IDC_TREEfeatures                1095
#define IDC_focusmessage                1096
#define IDC_termrule                    1100
#define IDC_markingrule                 1101
#define IDC_longestmatch                1102
#define IDC_lastwordindex               1103
#define IDC_numvar                      1104
#define IDC_variablevalue               1105
#define ID_printvalue                   1106
#define IDC_variablename                1107
#define IDC_seefiles                    1109
#define IDC_pathfiletree                1111
#define IDC_newfile                     1113
#define IDC_filename                    1114
#define IDC_deleterulefile              1115
#define IDC_fileadding                  1116
#define IDC_inpututf8                   1117
#define IDC_deleterule                  1118
#define IDC_ntmversion                  1120
#define IDC_LIST                        1123
#define IDC_appliedrules                1124
#define IDC_Layernumber                 1125
#define IDC_outof                       1126
#define IDC_detectlanguage              1127
#define IDC_listevar                    1128
#define IDC_LISTTYPES                   1129
#define IDC_ListeVariables              1130
#define IDC_seerules                    1131
#define IDC_instruction                 1132
#define IDC_debugmode                   1133
#define IDC_pythondebug                 1134
#define IDC_modulepython                1137
#define IDC_pythonline                  1138
#define IDC_CHECK1                      1139
#define IDC_tagger_mode                 1139
#define IDC_EDITTEST                    1140
#define IDC_EDITTESTVALEUR              1141
#define IDC_COMBO1                      1142
#define IDC_tagger_mode2                1142
#define IDC_COMBO2                      1143
#define IDC_CHECK2                      1143
#define IDC_COMBO3                      1144
#define IDC_CHECK3                      1144
#define IDC_MULTWRDDISPLAY              1144
#define IDC_COMBO4                      1145
#define IDC_COMBO5                      1146
#define ID_ANALYSE_PARSE                32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_ANALYZIS_RELOADGRAMMAR       32777
#define ID_BUTTON32779                  32779
#define ID_EDIT_OPTIONS                 32787
#define ID_BUTTONXML                    32788
#define ID_BUTTONTXT                    32789
#define ID_PARSING_PARSETEXTTOXML       32790
#define id_createrule                   32791
#define ID_setlimit                     32793
#define ID_rule_number                  32794
#define ID_SEARCHINRULE                 32795
#define ID_SEARCHAGAIN                  32796
#define ID_FINDRULENUMBER               32797
#define ID_loadanothergrammar           32799
#define ID_VIEW_GRAMMAR1                32800
#define ID_VIEW_GRAMMAR2                32801
#define ID_VIEW_GRAMMAR3                32802
#define ID_VIEW_GRAMMAR4                32803
#define id_help_scripting               32804
#define ID_PARSING_PARSEFILE            32805
#define ID_XML_INPUT                    32807
#define ID_NTM_ONLY                     32809
#define ID_RULE_DEBUGFROM0              32810
#define ID_BUTTONMOINS                  32814
#define ID_BUTTONPLUS                   32816
#define ID_Menu                         32822
#define ID_RELOAD_AND_PARSE             32826
#define ID_DEPENDANCE_ANALYSE           32833
#define ID_DEBUGDEP                     32838
#define ID_PARSING_DEBUGDEPENDENCY      32839
#define ID_PARSING_DEBUGDEP             32840
#define ID_INDICATOR_LIGNE              33333

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
