/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 * GoldminerSetup.java
 *
 * Created on September 5, 2006, 1:49 PM
 */
package com.xerox.xrce.xipui.goldminer.ui;

import com.xerox.xrce.xipui.goldminer.GoldminerEngine;
import com.xerox.xrce.xipui.modules.DialogModule;
import com.xerox.xrce.xipui.modules.ModuleContext;

/**
 *
 * @author  vgrassau
 */
public class GoldminerSetup extends DialogModule {

    private SetupConnection setupConnection;
    private SetupTypeElement setupTypes;
    private SetupRelationElement setupRelations;

    /** Creates new form GoldminerSetup
     * @param context 
     */
    public GoldminerSetup(ModuleContext context) {
        super(context);
        initComponents();
        setModal(true);
        setSize(640, 480);
        setupConnection = new SetupConnection(getModuleContext());
        setupTypes = new SetupTypeElement(getModuleContext());
        setupRelations = new SetupRelationElement(getModuleContext());
        setupTab.addTab("Connection", null, setupConnection, "Set the connection parameters");
        setupTab.addTab("Types", null, setupTypes, "Set the types(Dependency with one parameter) to use");
        setupTab.addTab("Relations", null, setupRelations, "Set the relations(Dependency with two parameters or more) to use");
    }

    /**
     * 
     */
    private void reload() {
        setupConnection = new SetupConnection(getModuleContext());
        setupTypes = new SetupTypeElement(getModuleContext());
        setupRelations = new SetupRelationElement(getModuleContext());
        setupTab.setComponentAt(0, setupConnection);
        setupTab.setComponentAt(1, setupTypes);
        setupTab.setComponentAt(2, setupRelations);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelButton = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        setupTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        panelButton.add(okButton);

        cancelButton.setFont(new java.awt.Font("Arial", 0, 11));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panelButton.add(cancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(panelButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("<html> <body> <p><center>Setup</center></p> \n<li><u> Connection</u> :  to describe the database to use,        All elements depends of this connection. </li> \n<li> <u>Types</u> :  to define the types (Dependency with one parameter) to use</li> \n<li><u> Relations</u> :  to define the relations(Dependency with two parameters or more) to use</li> \n</body> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jSeparator1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        setupTab.setBackground(new java.awt.Color(255, 255, 255));
        setupTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setupTabStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(setupTab, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_setupTabStateChanged
//       if ( setupConnection.connectionChanged()) {
//           warning("<p>Connection changed !!!</p><p>Goldminer needs to be reloaded</p>");
//            GoldminerEngine engine = (GoldminerEngine)getProperty("goldminerEngine");
//            if ( engine.reload()) {
//                GoldminerRequest request = (GoldminerRequest)getProperty("goldminerRequest");
//                request.reLoad();
//                reload();
//            }
//       }
    }//GEN-LAST:event_setupTabStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if ((setupConnection.connectionChanged()) || (setupRelations.apply() && setupTypes.apply())) {
            GoldminerEngine engine = (GoldminerEngine) getProperty("goldminerEngine");
            if (engine.reload()) {
                GoldminerRequest request = (GoldminerRequest) getProperty("goldminerRequest");
                request.reLoad();
                dispose();
            } else {
                warning("Can't apply your changes...");
            }
        } else {
            warning("Can't apply your changes...");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void close() {
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel panelButton;
    private javax.swing.JTabbedPane setupTab;
    // End of variables declaration//GEN-END:variables
}
