#!/bin/sh
set -x
rm -rf xxxx

GRAM=`pwd`/../GRAMMARS
#GRAM=`pwd`/../../delivery/xip-9.53/grammar/english/entity
#GRAM=`pwd`/../../delivery/xip-9.53/grammar/french

#GRM=$GRAM/ENGLISH/GRMFILES/GRAM_GEN/gram_gen.grm
GRM=$GRAM/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
#GRM=$GRAM/ENGLISH/GRMFILES/GRAM_NORM/gram_norm_entit.grm
#GRM=$GRAM/ENGLISH/GRMFILES/GRAM_TEMP/gram_temp.grm
#GRM=$GRAM/ENGLISH/APPLICATIONS/XipTriplets/GRMFILES_trip/gram_norm_trip_pron.grm
#GRM=$GRAM/ENGLISH/APPLICATIONS/COREF/coref.grm
#GRM=toyGram/english.grm
#GRM=$GRAM/FRENCH/BASIC/french.grm
#GRM=$GRAM/FRENCH/BASIC/french_entity.grm
#GRM=$GRAM/GERMAN/GRMFILES/german.grm
#GRM=$GRAM/SPANISH/GRMFILES/spanish.grm
#GRM=$GRAM/ITALIAN/GRMFILES/italian.grm
#GRM=$GRAM/PORTUGUESE/GRMFILES/portuguese.grm
#GRM=$GRAM/gram_gen_entit.grm
#GRM=$GRAM/french.grm
#GRM=gram_temporalExp.grm

#CLASS=com.xerox.jxip.JXip
#CLASS=com.xerox.jxip.JXip2
CLASS=com.xerox.jxip.XipResultManager
#CLASS=com.xerox.jxip.RuleLoadedManager
#CLASS=com.xerox.jxip.XipParser

#SENT="Peter is happy. He is a nice boy."
#SENT="Je suis content."
#SENT="Ein Kommentar unseres Pariser Korrespondenten Michael Moenninger."
#SENT="Die Vereinigten Staaten senden sieben Abgeordnete nach Berlin."
#SENT="Er kommt an."
#SENT="Co me llames más."
#SENT="Cállate ya."
#SENT="mañana iré a verte."
#SENT="input"
#SENT="input.xml"
SENT="The market has fallen today."


#JAR=dist/jxip.jar
JAR=dist/jxipPy.jar
#JAR=../../delivery/xip-9.59-43/java/dist/jxipPy.jar

#java -cp $JAR $CLASS $GRM "$SENT"
java -verbose:jni -cp $JAR $CLASS $GRM "$SENT"
