#!/bin/sh
#set -x
ROOT_XIP=`pwd`/../GRAMMARS
#ROOT_XIP=`pwd`/../../delivery/xip-9.53/grammar/english/entity
#ROOT_XIP=`pwd`/../../delivery/xip-9.53/grammar/french
export ROOT_XIP

#GRM=$ROOT_XIP/ENGLISH/GRMFILES/GRAM_GEN/gram_gen.grm
GRM=$ROOT_XIP/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
#GRM=$ROOT_XIP/ENGLISH/APPLICATIONS/XipTriplets/GRMFILES_trip/gram_norm_trip_pron.grm
#GRM=$ROOT_XIP/ENGLISH/APPLICATIONS/COREF/coref.grm
#GRM=toyGram/english.grm
#GRM=$ROOT_XIP/gram_gen_entit.grm
#GRM=$ROOT_XIP/FRENCH/BASIC/french.grm
#GRM=$ROOT_XIP/french.grm
#GRM=$ROOT_XIP/GERMAN/GRMFILES/german.grm
#GRM=$ROOT_XIP/SPANISH/GRMFILES/spanish.grm

#CLASS=com.xerox.jxip.JXip
CLASS=com.xerox.jxip.JXip2
#CLASS=com.xerox.jxip.XipResultManager
#CLASS=com.xerox.jxip.RuleLoadedManager
#CLASS=com.xerox.jxip.XipParser

SENT="Peter is happy. He is a nice boy."
#SENT="Je suis content."
#SENT="Ein Kommentar unseres Pariser Korrespondenten Michael Moenninger."
#SENT="Die Vereinigten Staaten senden sieben Abgeordnete nach Berlin."
#SENT="Er kommt an."
#SENT="Co me llames más."
#SENT="Cállate ya."
#SENT="mañana iré a verte."
#SENT="input"
#SENT="input.xml"

#PYTHONHOME=/opt/STools/lib/python2.3
#PYTHONHOME=/home/roux/cvsxip/python/Python-2.4.1
#export PYTHONHOME
#to accept:" import sys" (or any basic module)
#PYTHONPATH=$PYTHONHOME
#to accept:" import math"
#PYTHONPATH=$PYTHONPATH:$PYTHONHOME/lib-dynload
#to accept:" import xips"
#PYTHONPATH=$PYTHONHPATH:/home/grondeau/projets/parSem/xip/dev/lib/linux/sharedLibPy
#PYTHONPATH=$PYTHONHOME:$PYTHONHOME/lib-dynload:/home/grondeau/projets/parSem/xip/dev/lib/linux/sharedLibPy
#PYTHONPATH=/home/roux/cvsxip/python/Python-2.4.1/Lib:/home/roux/cvsxip/python/Python-2.4.1/build/lib.linux-i686-2.4:/home/roux/cvsxip/python/Python-2.4.1/Lib/plat-linux2:/home/roux/cvsxip/python/Python-2.4.1/Lib/site-packages
#export PYTHONPATH

#LD_LIBRARY_PATH=/home/grondeau/projets/parSem/python/2.4.1/linux/shared
#LD_LIBRARY_PATH=/tmp/$USER/linux/sharedLib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH

JAR=dist/jxip.jar
#JAR=dist/jxipPy.jar
#JAR=../../delivery/xip-9.59-43/java/dist/jxipPy.jar

java -cp $JAR $CLASS $GRM "$SENT"
