#! /bin/tcsh

set GRM=/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/FINANCE/GRM_mda/gram_finance_mda.grm


/opt/ParSem_db/bin/linux64/xip -grm  $GRM -tr -f -sentence -sentencenum -inpututf8 $1 $2 $3 $4 $5 $6 $7















