#!/bin/sh
set -x
rm -rf Test.class

#GRAM=../../../grammar/english/entity/englishEntity.grm
REM set GRAM=..\..\..\GRAMMARS\ENGLISH\GRMFILES\GRAM_GEN\gram_gen_entit.grm
set GRAM=..\..\..\GRAMMARS\ENGLISH\GRMFILES\GRAM_NORM\gram_norm_entit.grm

JAR=../../dist/jxip.jar

javac -classpath $JAR Test.java 
java  -classpath $JAR:. Test $GRAM  "A bottle of water on my table"
rm -rf Test.class
