#!/bin/sh
set -x

# set XIP_HOME to the installation directory of XIP
# set XIP_HOME to an absolute path if you want to launch xipparse from anywhere
XIP_HOME=`pwd`/../../../..

XIP=/opt/ParSem/bin/linux/xip

ROOT_XIP=$XIP_HOME/GRAMMARS
export ROOT_XIP

GRMFILE=$ROOT_XIP/ENGLISH/APPLICATIONS/GE/gram_ge.grm

$XIP -sentence -sentencenum -tr -f -math -grm $GRMFILE $1 $2 $3 $4 $5 $6 $7 $8 $9 
