#!/bin/sh
set -x
rm -f a.out
ROOT=../..
g++ -I$ROOT/include -L$ROOT/lib/linux -lSTLnhxXipL test.cxx
LD_LIBRARY_PATH=$ROOT/lib/linux;export LD_LIBRARY_PATH
GRMDIR=`pwd`/../../grammar/english/basic;export GRMDIR

/home/grondeau/projets/xip/xip/tools/valgrind/valgrind-2.2.0/bin/valgrind --tool=memcheck --leak-check=yes -v --num-callers=10 --log-file=res a.out 

rm -f a.out
