#!/bin/sh
set -x
rm -f a.out
ROOT=../..
g++ -I$ROOT/include -L$ROOT/lib/linux -lSTLnhxXipL test.cxx
LD_LIBRARY_PATH=$ROOT/lib/linux;export LD_LIBRARY_PATH
GRMDIR=`pwd`/../../grammar/english/basic;export GRMDIR
./a.out
rm -f a.out
