#!/bin/sh
set -x
rm -f res
GRM=/opt/ParSem/users/grondeau/parSem/xip/dev/GRAMMARS/SPANISH/GRMFILES/spanish.grm
XIP=/opt/ParSem/users/grondeau/parSem/xip/dev/bin/linux64/xip
XIPCMD="$XIP -grm $GRM -tr -f -text input.txt"

VALGRIND=/opt/ParSem/tools/valgrind/3.3.1/linux-64/bin/valgrind

#$XIPCMD

$VALGRIND --tool=memcheck --leak-check=yes -v --num-callers=10 --log-file=res $XIPCMD


