/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2005 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ui.editor;

/**
 *
 * @author  vgrassau
 */
public class Status extends javax.swing.JPanel {

    /** Creates new form Status */
    public Status() {
        initComponents();
    }

    public void setLine(int line) {
        setLine(String.valueOf(line));
    }

    public void setLine(String line) {
        lineNumber.setText(line);
        lineNumber.setToolTipText("line : " + line);
    }

    public void setPosition(int pos) {
        setPosition(String.valueOf(pos));
    }

    public void setFile(String url) {
        file.setText(url);
        file.setToolTipText(url);
    }

    public void setPosition(String pos) {
        positionNumber.setText(pos);
        positionNumber.setToolTipText("position : " + pos);
    }

    public void setDivers(String txt) {
        divers.setText(txt);
        divers.setToolTipText(txt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lineNumber = new javax.swing.JLabel();
        separatorNumber = new javax.swing.JLabel();
        positionNumber = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        file = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        divers = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lineNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lineNumber.setFocusTraversalPolicyProvider(true);
        lineNumber.setFocusable(false);
        lineNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lineNumber.setMaximumSize(new java.awt.Dimension(70, 14));
        lineNumber.setMinimumSize(new java.awt.Dimension(70, 14));
        lineNumber.setPreferredSize(new java.awt.Dimension(70, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(lineNumber, gridBagConstraints);

        separatorNumber.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(separatorNumber, gridBagConstraints);

        positionNumber.setMaximumSize(new java.awt.Dimension(70, 14));
        positionNumber.setMinimumSize(new java.awt.Dimension(70, 14));
        positionNumber.setPreferredSize(new java.awt.Dimension(70, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(positionNumber, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(jSeparator1, gridBagConstraints);

        file.setForeground(new java.awt.Color(153, 51, 0));
        file.setMaximumSize(new java.awt.Dimension(300, 14));
        file.setMinimumSize(new java.awt.Dimension(150, 14));
        file.setPreferredSize(new java.awt.Dimension(150, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(file, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(jSeparator2, gridBagConstraints);

        divers.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(divers, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel divers;
    private javax.swing.JLabel file;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lineNumber;
    private javax.swing.JLabel positionNumber;
    private javax.swing.JLabel separatorNumber;
    // End of variables declaration//GEN-END:variables
}
