#!/bin/sh
set -x
JAR=lib/jxip.jar
rm -rf XipParser.class
rm -rf build
rm -rf resXIP.xml
mkdir build

javac -d build -classpath $JAR src/XipParser.java

#java -mx128m -classpath $JAR:build XipParser  corpus/input.txt
java -mx128m -classpath $JAR:build XipParser corpus/revueNote0-0.xml