/* soapkifrestPOSTProxy.cpp
   Generated by gSOAP 2.8.22 from kifrest.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapkifrestPOSTProxy.h"

kifrestPOSTProxy::kifrestPOSTProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	kifrestPOSTProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

kifrestPOSTProxy::kifrestPOSTProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	kifrestPOSTProxy_init(_soap->imode, _soap->omode);
}

kifrestPOSTProxy::kifrestPOSTProxy(const char *url)
{	this->soap = soap_new();
	this->soap_own = true;
	kifrestPOSTProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

kifrestPOSTProxy::kifrestPOSTProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	kifrestPOSTProxy_init(iomode, iomode);
}

kifrestPOSTProxy::kifrestPOSTProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	kifrestPOSTProxy_init(iomode, iomode);
	soap_endpoint = url;
}

kifrestPOSTProxy::kifrestPOSTProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	kifrestPOSTProxy_init(imode, omode);
}

kifrestPOSTProxy::~kifrestPOSTProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void kifrestPOSTProxy::kifrestPOSTProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "urn:kifrest", NULL, NULL},
	{"kifREST", "http://websrv.cs.fsu.edu/~engelen/kifrest.wsdl", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void kifrestPOSTProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void kifrestPOSTProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	kifrestPOSTProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void kifrestPOSTProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *kifrestPOSTProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *kifrestPOSTProxy::soap_fault()
{	return this->soap->fault;
}

const char *kifrestPOSTProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *kifrestPOSTProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int kifrestPOSTProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int kifrestPOSTProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void kifrestPOSTProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void kifrestPOSTProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *kifrestPOSTProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int kifrestPOSTProxy::call(const char *endpoint, const char *soap_action, ns1__quadruplet *ns1__call, std::string &ns1__callResponse)
{	struct soap *soap = this->soap;
	struct __kifREST__call soap_tmp___kifREST__call;
	struct __kifREST__callResponse *soap_tmp___kifREST__callResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/kifrestserver.cgi";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___kifREST__call.ns1__call = ns1__call;
	soap_set_version(soap, 0); /* no SOAP */
	soap_serialize___kifREST__call(soap, &soap_tmp___kifREST__call);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_put___kifREST__call(soap, &soap_tmp___kifREST__call, "-kifREST:call", NULL)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	soap->http_content = "text/xml";
	if (soap_connect_command(soap, SOAP_POST_FILE, soap_url(soap, soap_endpoint, soap_action), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_put___kifREST__call(soap, &soap_tmp___kifREST__call, "-kifREST:call", NULL)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__callResponse)
		return soap_closesock(soap);
	soap_default_std__string(soap, &ns1__callResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___kifREST__callResponse = soap_get___kifREST__callResponse(soap, NULL, "-kifREST:callResponse", NULL);
	if (!soap_tmp___kifREST__callResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	ns1__callResponse = soap_tmp___kifREST__callResponse->ns1__callResponse;
	return soap_closesock(soap);
}
/* End of client proxy code */
