/* soapkifrestPOSTProxy.h
   Generated by gSOAP 2.8.22 from kifrest.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapkifrestPOSTProxy_H
#define soapkifrestPOSTProxy_H
#include "soapH.h"

class SOAP_CMAC kifrestPOSTProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'kifrestPOSTProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in kifrest.h (non-static)
	/// Constructor
	kifrestPOSTProxy();
	/// Constructor to use/share an engine state
	kifrestPOSTProxy(struct soap*);
	/// Constructor with endpoint URL
	kifrestPOSTProxy(const char *url);
	/// Constructor with engine input+output mode control
	kifrestPOSTProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	kifrestPOSTProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	kifrestPOSTProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~kifrestPOSTProxy();
	/// Initializer used by constructors
	virtual	void kifrestPOSTProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'call' (returns error code or SOAP_OK)
	virtual	int call(ns1__quadruplet *ns1__call, std::string &ns1__callResponse) { return this->call(NULL, NULL, ns1__call, ns1__callResponse); }
	virtual	int call(const char *endpoint, const char *soap_action, ns1__quadruplet *ns1__call, std::string &ns1__callResponse);
};
#endif
