#!/bin/sh
set -x
valgrind=/opt/ParSem/tools/valgrind/3.6.1/linux/bin/valgrind 
progToAnalyse="java -Xmx512m -cp dist/jxip.jar:testAna/testMem1/build testMem1.Test ../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm input-10"
genSupFile=suppressionGen.supp
log1=valgrind-1.log
log2=valgrind-2.log
xipSupFile=suppressionXip.supp
xipLeakSupFile=suppressionXipLeak.supp
javaSupFile=suppressionJava.supp
javaLeakSupFile=suppressionJavaLeak.supp
ntmSupFile=suppressionNtm.supp
options0="-v --tool=memcheck --leak-check=full --show-reachable=yes --error-limit=no"
options2="--track-origins=yes --trace-children=yes --num-callers=20"
options3="--gen-suppressions=all"
options4="--suppressions=$javaSupFile --suppressions=$ntmSupFile --suppressions=$xipSupFile --suppressions=$javaLeakSupFile --suppressions=$xipLeakSupFile"
options5="--suppressions=$genSupFile"
options6="--demangle=yes"

#get the suppression file use in versionC++
cp testAna/testMem1/versionC++/suppressionXipLeak.supp .
cp testAna/testMem1/versionC++/suppressionNtm.supp .

rm -rf $log1 $log2
#generate suppression file
options1="--log-file=$log1"
$valgrind $options0 $options1 $options2 $options3 $options4 $progToAnalyse
cat $log1 | ./generateSuppressionFile.sh >$genSupFile

#rerun with the use of the suppression file generated
options1="--log-file=$log2"
$valgrind $options0 $options1 $options2 $options3 $options4 $options5 $options6 $progToAnalyse

grep Leak $genSupFile | wc -l
grep Memcheck $genSupFile | wc -l

grep Memcheck $log2 | wc -l

#==19061== LEAK SUMMARY:
#==19061==    definitely lost: 4,810 bytes in 80 blocks
#==19061==    indirectly lost: 1,988 bytes in 11 blocks
#==19061==      possibly lost: 302,880 bytes in 7,190 blocks
#==19061==    still reachable: 30,199,154 bytes in 445,557 blocks
#==19061==         suppressed: 0 bytes in 0 blocks
#==19061==
#==19061== ERROR SUMMARY: 258 errors from 258 contexts (suppressed: 262454 from 879)
