#!/bin/sh
#set -x
# il faut changer dans le fichier grm "grammar:" par "gram:"
GRAM=$1

echo "grammar file: $GRAM"
echo "-------------------------------------------"
grep '^License:' $GRAM
grep '^Modules:' $GRAM
grep '^Expiration:' $GRAM
echo "-------------------------------------------"

rm -f clef
g++  -I ../include -DLINUX -o clef ../src/clef.cxx

./clef $GRAM 2>key
nkey=`cat key |awk '{print $2}'`
ckey=`cat $GRAM| awk '/^Code:/{print $2}'`
rm -f key
if [ $ckey != $nkey ]; then
        echo "You have to update the Code field in the file: $GRAM"
        echo "by Code:$nkey"
        exit -1
fi
exit 0

