SPACES:
        \09 \10 \13 \32 

SEPARATORS:
        . ? ! ; : , " ' `  ( ) * % ^ $ % # { } [ ] | / < > « » & -

spec		/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/HYPER/NTM_biotip/lex-spec-nosgml.fst
spec2		/opt/Mltt/BioTIP/ntm-1.2/data/lex-spec2.fst
spec3		/opt/ParSem/users/sandor/biotip/NTM/guess-spec.fst
bioenglish	/opt/ParSem/users/sandor/biotip/NTM/lex-bioenglish1.fst
guess1		/opt/Mltt/BioTIP/ntm-1.2/data/guess-english.fst
guess2		/opt/ParSem/users/sandor/biotip/NTM/guess-biotip-forhyper.fst
open		/opt/Mltt/BioTIP/ntm-1.2/data/guess-open.fst
init		/opt/Mltt/BioTIP/ntm-1.2/data/norm-init.fst
namb		/opt/Mltt/BioTIP/ntm-1.2/data/norm-ambig.fst
allcap		/opt/Mltt/BioTIP/ntm-1.2/data/norm-allcap.fst

spec
spec3
namb bioenglish
allcap bioenglish
init spec2
init guess2
init guess1
open
