#!/bin/sh

BASIC=`pwd`/BASICS
SYNT=`pwd`/FORSYNTAX

fst -s $BASIC/lex-1.fst -e "unoptimize" -l $BASIC/remove-words.xfst -l $SYNT/add-s_tags.xfst -e "save $SYNT/temp.fst" -e 'regex ~$[ %_ ?+ %+Verb ];' -e "compose" -e "save  $SYNT/lex_nouv.fst" -stop

