#!/bin/sh
#set -x

# update JAVA_HOME to your environment

XIP_HOME=`pwd`/../../..

JAR=$XIP_HOME/java/dist/jxip.jar
rm -rf Test.class
javac -classpath $JAR Test.java 
java -mx128m -classpath $JAR:. Test $XIP_HOME/grammar/english/norm/gram_norm_entit.grm
rm -rf Test.class errors.err

