# Solaris fst binary is located in /opt/Mltt/bin .  Don't know if
# there's a linux one around anywhere.  For the time being run make on
# a solaris machine, e.g. lautaret.
balises.fst: balises.xfst
	fst -l balises.xfst -e 'save balises.fst' -stop
