#!/bin/sh
set -x
GRMFILE=../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
JAR=../../../java/dist/jxip.jar
rm -rf Test.class
javac -classpath $JAR Test.java 
CORPUS=/opt/ParSem/Corpora/ENGLISH/REUTERSEXPANDED
#CORPUS=input
java -Xmx256m -classpath $JAR:./build Test $GRMFILE $CORPUS
rm -rf *.class errors.err
