#!/bin/sh

BASIC=`pwd`/basics
SYNT=`pwd`/forsyntax

fst -s $BASIC/lex-1.fst -e "unoptimize" -l $SYNT/add-s_tags.xfst -e "save $SYNT/temp.fst" -e "regex ~$[ %_ ?+ %+Verb ];" -e "compose" -e "save  $SYNT/lex_nouv.fst" -stop

