#!/bin/sh
set -x

GRM=../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
JAR=../../../java/dist/jxip.jar
rm -rf Test.class
javac -classpath $JAR Test.java 
java -Xmx256m -classpath $JAR:. Test $GRM input 
rm -rf Test.class errors.err

