/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2005 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ui.corpus;

import com.xerox.xrce.xipui.modules.ModuleContext;
import com.xerox.xrce.xipui.ui.AbstractStep;
import java.awt.event.KeyEvent;

/**
 *
 * @author  Vianney Grassaud
 */
public class AddCorpusStep extends AbstractStep {

    /**
     * Creates new form AddCorpusStep
     * @param properties 
     */
    public AddCorpusStep(ModuleContext properties) {
        super(properties);
        setDescription("add Corpus");
        initComponents();
        this.couldFinish = true;
    }

    public void initStepManager() {
    }

    public void close() {
        removeAll();
        this.isClosed = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        label = new javax.swing.JLabel();
        infoName = new javax.swing.JLabel();
        corpusSetName = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setPreferredSize(new java.awt.Dimension(400, 280));
        label.setBackground(new java.awt.Color(153, 255, 153));
        label.setFont(new java.awt.Font("Arial", 0, 11));
        label.setText("Add a new Corpus");
        label.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 51)));
        label.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(label, gridBagConstraints);

        infoName.setFont(new java.awt.Font("Arial", 0, 11));
        infoName.setForeground(new java.awt.Color(153, 51, 0));
        infoName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(infoName, gridBagConstraints);

        corpusSetName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                corpusSetNameKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(corpusSetName, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void corpusSetNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corpusSetNameKeyReleased
        if (evt.getID() == KeyEvent.KEY_RELEASED) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                isValide();
            }
        }
    }//GEN-LAST:event_corpusSetNameKeyReleased

    public boolean isValide() {
        if (getProject().getCorpusSet(this.corpusSetName.getText()) != null) {
            warning(this.corpusSetName.getText() + " already exists , please change the name!!");
            this.corpusSetName.setText("");
            return false;
        } else {
            return true;
        }
    }

    /**
     *Renvoie le nom du CorpusSet
     *@return nom du corpusSet
     */
    public String getCorpusSetName() {
        return this.corpusSetName.getText();
    }

    /**
     *Initialise le nom du CorpusSet a rajouter
     *@param name nom du CorpusSet
     *
     */
    public void setCorpusSetName(String name) {
        this.corpusSetName.setText(name);
    }

    public void loadModePolicy(short mode) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField corpusSetName;
    private javax.swing.JLabel infoName;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
