/*
 * Xerox Research Centre Europe - Grenoble Laboratory
 * 
 * Copyright (c) 2006 - 2007 Xerox Corporation.  All Rights Reserved.
 * 
 ****************************************************************************************
 * Copyright (c) 2006 Xerox Corporation                                                 *
 * Xerox Research Centre Europe - Grenoble                                              *
 * All Rights Reserved                                                                  *
 * Copyright protection claimed includes all forms and matters of copyrightable         *
 * material and information now allowed by statutory or judicial law or                 *
 * hereinafter granted, including without limitation, material generated from           *
 * the software programs which are displayed on the screen such as icons,               *
 * screen display looks, etc. All rights reserved. No part of this document             *
 * may be reproduced, stored in a retrieval system, or transmitted, in any              *
 * form or by any means, electronic, mechanical, photocopied, recorded, or              *
 * otherwise, without prior written consent from XEROX corporation.                     *
 ****************************************************************************************
 */
package com.xerox.xrce.xipui.ui.corpus;

import com.xerox.xrce.xipui.ui.corpus.AddCorpusSetAction;
import com.xerox.xrce.xipui.ui.NewFileAction;
import com.xerox.xrce.xipui.ui.FileStepManager;
import com.xerox.xrce.xipui.modules.ModuleContext;
import com.xerox.xrce.xipui.modules.PanelModule;
import com.xerox.xrce.xipui.ui.RunManager;
import com.xerox.xrce.xipui.ui.Viewer;
import com.xerox.xrce.xipui.ui.XIPUIUtilities;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  vgrassau
 */
public class CorpusManager extends PanelModule {

    static public final String TITLE = "Corpus";
    static public final String addCorpusSet_action = "addCorpusSet_action";
    static public final String newCorpusFile_action = "newCorpusFile_action";
    private CorpusViewer corpusSource;

    /**
     * Creates new form CorpusManager
     * @param properties 
     */
    public CorpusManager(ModuleContext properties) {
        super(properties);
        //this method must be called before the instanciation of corpusSource field
        initActionsAndCorpusMenu();
        corpusSource = new CorpusViewer(properties);
        corpusSource.loadTree();
        initComponents();
        add(corpusSource, BorderLayout.CENTER);
        setProperty(module_corpus, this);
        log.info("corpus manager was correctly loaded");
    }

    /**
     *@return the Viewer
     */
    public Viewer getViewer() {
        return this.corpusSource;
    }

    private void initActionsAndCorpusMenu() {
        // action for a new CorpusSet
        AddCorpusSetAction addCorpusSetAction = new AddCorpusSetAction(getModuleContext());
        //action to create a new corpus file
        NewFileAction newCorpusFileAction = new NewFileAction(getModuleContext(), FileStepManager.CORPUS_ONLY);
        newCorpusFileAction.setLabelAction(XIPUIUtilities.getApplicationResource("action.new.corpus.file"));
        setProperty(newCorpusFile_action, newCorpusFileAction);
        setProperty(addCorpusSet_action, addCorpusSetAction);
        JMenuBar menu = (JMenuBar) getProperty(MENUBAR);
        boolean stop = false;
        for (int i = 0; i < menu.getMenuCount() && !stop; i++) {
            JMenu subMenu = menu.getMenu(i);
            if (subMenu.getText().equals("Corpus")) {
                subMenu.add(addCorpusSetAction);
                subMenu.add(newCorpusFileAction);
                stop = true;
            }
        }
    }

    public void close() {
        this.removeAll();
        corpusSource.close();
        isClosed = true;
    }

    public void reload() {
        this.corpusSource.refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

    }// </editor-fold>//GEN-END:initComponents
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        //we must select the corpus option
        RunManager runner = (RunManager) getProperty(module_run);
        if (runner != null) {
            runner.setFromInput(false);
        }
    }//GEN-LAST:event_formFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
