#!/bin/sh
set -x
java -Xmx128m -classpath /opt/ParSem/users/Roux/xip/parSem/xip/dev/java/dist/jxip.jar:build Test /opt/ParSem/users/Roux/xip/parSem/xip/dev/GRAMMARS/FRENCH/BASIC/french.grm test.kif


  







