#!/bin/sh
set -x
/opt/ParSem/tools/jdk/1.6.0_21/jre/bin/java -Xmx128m -classpath /opt/ParSem/users/grondeau/parSem/xip/dev/java/dist/jxip.jar:build Test /opt/ParSem/users/grondeau/parSem/xip/dev/GRAMMARS/GERMAN/APPLICATIONS/EERQI/data/german_eerqi.grm in1

