#!/bin/sh
set -x
rm -rf build
mkdir build
jar=../../dist/jxip.jar
grm=../../../GRAMMARS/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm
javac -cp $jar  -d build Test.java
java -Xmx1023m -cp $jar:build testMem1.Test 
