s/\+ADJ/\+hmm_ADJ/g
s/\+ADV_PART/\+hmm_ADVPART/g
s/\+ADV/\+hmm_ADV/g
s/\+ART/\+hmm_ART/g
s/\+AUX/\+hmm_AUX/g
s/\+CM/\+hmm_CM/g
s/\+CONJ/\+hmm_CONJ/g
s/\+DEICT_PRON_*/\+hmm_DPRON/g
s/\+FUT_PART_*/\+hmm_FPART/g
s/\+GENE_PRON_*/\+hmm_GPRON/g
s/\+INDEF_PRON_*/\+hmm_IPRON/g
s/\+INF/\+hmm_INF/g
s/\+INTERJ/\+hmm_INTERJ/g
s/\+LS/\+hmm_LS/g
s/\+MEA/\+hmm_MEA/g
s/\+NADJ_*/\+hmm_NA/g
s/\+NOUN_*/\+hmm_N/g
s/\+NUM_PRON_*/\+hmm_NP/g
s/\+NUM_*/\+hmm_NUM/g
s/\+NUMBER/\+hmm_NUMBER/g
s/\+ORD_NUMBER/\+hmm_ORD/g
s/\+PAST_PART_*/\+hmm_PP/g
s/\+PERS_PRON/\+hmm_PPRON/g
s/\+POSTPOS/\+hmm_POSTPOS/g
s/\+PREFIX/\+hmm_PREFIX/g
s/\+PRES_PART_*/\+hmm_PR/g
s/\+PRON_*/\+hmm_PRON/g
s/\+PROPN_*/\+hmm_PN/g
s/\+PUNCT/\+hmm_PUNCT/g
s/\+REFL_PRON_*/\+hmm_RF/g
s/\+REL_PRON_*/\+hmm_RPRON/g
s/\+ROM_NUMBER/\+hmm_ROM/g
s/\+SPEC/\+hmm_SPEC/g
s/\+SUFF/\+hmm_SUFF/g
s/\+TRUNC/\+hmm_TRUNC/g
s/\+VERB/\+hmm_VERB/g
