#!/bin/sh
set -x
UNAME=`uname`
USER=`whoami`
if [ "$UNAME" = "Darwin" ]; then
        DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/private/t
        export DYLD_LIBRARY_PATH
fi
if [ "$UNAME" = "Linux" ]; then
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/grondeau/projets/parSem/xip/dev/lib/linux.debug/sharedLib
        export LD_LIBRARY_PATH
fi


ROOT_XIP=`pwd`/../../GRAMMARS
export ROOT_XIP

GRM=$ROOT_XIP/ENGLISH/GRMFILES/GRAM_GEN/gram_gen_entit.grm

bin/linux/sampleD $GRM

