#!/bin/sh
set -x
JAR=../../dist/jxip.jar
GRM="../../../GRAMMARS/ENGLISH/APPLICATIONS/SCOOP/GRMFILES/scoop-complete.grm";
rm -rf XipParser.class
javac -classpath $JAR XipParser.java 
java -mx256m -classpath $JAR:. XipParser $GRM
