#!/bin/sh
set -x
JAR=/opt/ParSem/bin/xip-13.00-23/java/jxip.jar
GRM="../../../GRAMMARS/ENGLISH/APPLICATIONS/SCOOP/GRMFILES/scoop-complete.grm";
rm -rf XipParser.class
javac -classpath $JAR XipParser.java 
java -mx256m -classpath $JAR:. XipParser $GRM
