#!/bin/sh
set -x
#JAR=../../dist/jxip.jar
#JAR=/opt/ParSem/bin/xip-10.02-07/java/jxip.jar
JAR=../../dist/jxip.jar
#JAR=jxip-10.00-44.jar

rm -rf *.log
rm -rf TestLoadGram.class
javac -classpath $JAR TestLoadGram.java 
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
java  -classpath $JAR:. TestLoadGram  
rm -rf TestLoadGram.class
