#!/bin/sh
set -x

XIP_HOME=`pwd`/../../..

UNAME=`uname`
if [ "$UNAME" = "Linux" ]; then
	XIP=$XIP_HOME/bin/linux/xip
else
	XIP=$XIP_HOME/bin/solaris/xip
fi

$XIP -grm sample.grm -tr -f $1 $2 $3 $4 $5

