#! /bin/tcsh

set GRM=/opt/FSG_sec/FEII-SIGIR-Challenge-2017/PreProcessedData/2ndRun/TrainingData/SIGIR4AGNES/script/SEC/APPLICATIONS/FINANCE/GRM_fei/gram_fei.grm



/opt/ParSem_db/bin/linux64/xip -grm  $GRM -tr -f -sentence -sentencenum -inpututf8 $1 $2 $3 $4 $5 $6 $7













