#!/bin/csh

setenv XIPBINDIR /opt/ParSem/bin/linux

\rm -r english ;

cp -r english_dev english ;

cd english ;

\rm *.fst ;
\rm *.xml ;
\rm *.xtr ;
\rm *.diff ;
\rm *.old* ;
\rm *.out ;
\rm *~ ;


mv new_pred.xip new_pred.sauver ;


$XIPBINDIR/xips -l ../english_dev/english.xip -crypte . ;

ls -1 *.crypte | gawk '{ch=$0;sub(".crypte","",ch); print "mv " $0 " " ch;}' | sh ;


mv new_pred.sauver new_pred.xip ;

cp ../english_dev/english.grm.pour.cryp english.grm ;

cp ../english_dev/vikef.py vikef.py ;
cp ../english_dev/vikeffinal.py vikeffinal.py ;
cp ../english_dev/vikefmain2.py vikefmain2.py ;


\rm controls.xip ;




