#! /bin/tcsh

#./lexicon-rule.sh

set GRM=/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/SALIENT/grm-refl//home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/SALIENT/DATA_refl/english_refl-xml.grm

#/home/sandor/parSem/xip/dev/GRAMMARS/ENGLISH/APPLICATIONS/PUBMED/data/gener-lexicon.pl


/opt/ParSem/bin/linux64/xip \
-sentence -sentencenum -tr \
-grm $GRM\
-xmltext 2 $1 $2 $3 $4 $5 $6 $7 $8 $9 | egrep "^TITLE|<title>|<abstract>|<body>|^CONCEPT_|^SENT|^REFLSENT|^IMP|^SUMMARY|> "


